// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "sobel_accel.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const int sobel_accel::C_S_AXI_DATA_WIDTH = "100000";
const int sobel_accel::C_S_AXI_WSTRB_WIDTH = "100";
const int sobel_accel::C_S_AXI_ADDR_WIDTH = "100000";
const sc_logic sobel_accel::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<24> sobel_accel::ap_const_lv24_0 = "000000000000000000000000";
const sc_lv<3> sobel_accel::ap_const_lv3_0 = "000";
const sc_lv<1> sobel_accel::ap_const_lv1_0 = "0";
const sc_logic sobel_accel::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> sobel_accel::ap_const_lv2_0 = "00";
const sc_lv<2> sobel_accel::ap_const_lv2_1 = "1";
const bool sobel_accel::ap_const_boolean_1 = true;

sobel_accel::sobel_accel(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sobel_accel_CONTROL_BUS_s_axi_U = new sobel_accel_CONTROL_BUS_s_axi<C_S_AXI_CONTROL_BUS_ADDR_WIDTH,C_S_AXI_CONTROL_BUS_DATA_WIDTH>("sobel_accel_CONTROL_BUS_s_axi_U");
    sobel_accel_CONTROL_BUS_s_axi_U->AWVALID(s_axi_CONTROL_BUS_AWVALID);
    sobel_accel_CONTROL_BUS_s_axi_U->AWREADY(s_axi_CONTROL_BUS_AWREADY);
    sobel_accel_CONTROL_BUS_s_axi_U->AWADDR(s_axi_CONTROL_BUS_AWADDR);
    sobel_accel_CONTROL_BUS_s_axi_U->WVALID(s_axi_CONTROL_BUS_WVALID);
    sobel_accel_CONTROL_BUS_s_axi_U->WREADY(s_axi_CONTROL_BUS_WREADY);
    sobel_accel_CONTROL_BUS_s_axi_U->WDATA(s_axi_CONTROL_BUS_WDATA);
    sobel_accel_CONTROL_BUS_s_axi_U->WSTRB(s_axi_CONTROL_BUS_WSTRB);
    sobel_accel_CONTROL_BUS_s_axi_U->ARVALID(s_axi_CONTROL_BUS_ARVALID);
    sobel_accel_CONTROL_BUS_s_axi_U->ARREADY(s_axi_CONTROL_BUS_ARREADY);
    sobel_accel_CONTROL_BUS_s_axi_U->ARADDR(s_axi_CONTROL_BUS_ARADDR);
    sobel_accel_CONTROL_BUS_s_axi_U->RVALID(s_axi_CONTROL_BUS_RVALID);
    sobel_accel_CONTROL_BUS_s_axi_U->RREADY(s_axi_CONTROL_BUS_RREADY);
    sobel_accel_CONTROL_BUS_s_axi_U->RDATA(s_axi_CONTROL_BUS_RDATA);
    sobel_accel_CONTROL_BUS_s_axi_U->RRESP(s_axi_CONTROL_BUS_RRESP);
    sobel_accel_CONTROL_BUS_s_axi_U->BVALID(s_axi_CONTROL_BUS_BVALID);
    sobel_accel_CONTROL_BUS_s_axi_U->BREADY(s_axi_CONTROL_BUS_BREADY);
    sobel_accel_CONTROL_BUS_s_axi_U->BRESP(s_axi_CONTROL_BUS_BRESP);
    sobel_accel_CONTROL_BUS_s_axi_U->ACLK(ap_clk);
    sobel_accel_CONTROL_BUS_s_axi_U->ARESET(ap_rst_n_inv);
    sobel_accel_CONTROL_BUS_s_axi_U->ACLK_EN(ap_var_for_const0);
    sobel_accel_CONTROL_BUS_s_axi_U->ap_start(ap_start);
    sobel_accel_CONTROL_BUS_s_axi_U->interrupt(interrupt);
    sobel_accel_CONTROL_BUS_s_axi_U->ap_ready(ap_ready);
    sobel_accel_CONTROL_BUS_s_axi_U->ap_done(ap_done);
    sobel_accel_CONTROL_BUS_s_axi_U->ap_idle(ap_idle);
    Block_proc_U0 = new Block_proc("Block_proc_U0");
    Block_proc_U0->ap_clk(ap_clk);
    Block_proc_U0->ap_rst(ap_rst_n_inv);
    Block_proc_U0->ap_start(Block_proc_U0_ap_start);
    Block_proc_U0->start_full_n(start_for_AddWeighted_U0_full_n);
    Block_proc_U0->ap_done(Block_proc_U0_ap_done);
    Block_proc_U0->ap_continue(Block_proc_U0_ap_continue);
    Block_proc_U0->ap_idle(Block_proc_U0_ap_idle);
    Block_proc_U0->ap_ready(Block_proc_U0_ap_ready);
    Block_proc_U0->start_out(Block_proc_U0_start_out);
    Block_proc_U0->start_write(Block_proc_U0_start_write);
    Block_proc_U0->src_rows_V_out_din(Block_proc_U0_src_rows_V_out_din);
    Block_proc_U0->src_rows_V_out_full_n(src_rows_V_c_full_n);
    Block_proc_U0->src_rows_V_out_write(Block_proc_U0_src_rows_V_out_write);
    Block_proc_U0->src_cols_V_out_din(Block_proc_U0_src_cols_V_out_din);
    Block_proc_U0->src_cols_V_out_full_n(src_cols_V_c_full_n);
    Block_proc_U0->src_cols_V_out_write(Block_proc_U0_src_cols_V_out_write);
    Block_proc_U0->sobel_g_rows_V_out_din(Block_proc_U0_sobel_g_rows_V_out_din);
    Block_proc_U0->sobel_g_rows_V_out_full_n(sobel_g_rows_V_c_full_n);
    Block_proc_U0->sobel_g_rows_V_out_write(Block_proc_U0_sobel_g_rows_V_out_write);
    Block_proc_U0->sobel_g_cols_V_out_din(Block_proc_U0_sobel_g_cols_V_out_din);
    Block_proc_U0->sobel_g_cols_V_out_full_n(sobel_g_cols_V_c_full_n);
    Block_proc_U0->sobel_g_cols_V_out_write(Block_proc_U0_sobel_g_cols_V_out_write);
    AXIvideo2Mat_U0 = new AXIvideo2Mat("AXIvideo2Mat_U0");
    AXIvideo2Mat_U0->ap_clk(ap_clk);
    AXIvideo2Mat_U0->ap_rst(ap_rst_n_inv);
    AXIvideo2Mat_U0->ap_start(AXIvideo2Mat_U0_ap_start);
    AXIvideo2Mat_U0->start_full_n(start_for_CvtColor_1_U0_full_n);
    AXIvideo2Mat_U0->ap_done(AXIvideo2Mat_U0_ap_done);
    AXIvideo2Mat_U0->ap_continue(AXIvideo2Mat_U0_ap_continue);
    AXIvideo2Mat_U0->ap_idle(AXIvideo2Mat_U0_ap_idle);
    AXIvideo2Mat_U0->ap_ready(AXIvideo2Mat_U0_ap_ready);
    AXIvideo2Mat_U0->start_out(AXIvideo2Mat_U0_start_out);
    AXIvideo2Mat_U0->start_write(AXIvideo2Mat_U0_start_write);
    AXIvideo2Mat_U0->INPUT_STREAM_TDATA(INPUT_STREAM_TDATA);
    AXIvideo2Mat_U0->INPUT_STREAM_TVALID(INPUT_STREAM_TVALID);
    AXIvideo2Mat_U0->INPUT_STREAM_TREADY(AXIvideo2Mat_U0_INPUT_STREAM_TREADY);
    AXIvideo2Mat_U0->INPUT_STREAM_TKEEP(INPUT_STREAM_TKEEP);
    AXIvideo2Mat_U0->INPUT_STREAM_TSTRB(INPUT_STREAM_TSTRB);
    AXIvideo2Mat_U0->INPUT_STREAM_TUSER(INPUT_STREAM_TUSER);
    AXIvideo2Mat_U0->INPUT_STREAM_TLAST(INPUT_STREAM_TLAST);
    AXIvideo2Mat_U0->INPUT_STREAM_TID(INPUT_STREAM_TID);
    AXIvideo2Mat_U0->INPUT_STREAM_TDEST(INPUT_STREAM_TDEST);
    AXIvideo2Mat_U0->img_rows_V_dout(src_rows_V_c_dout);
    AXIvideo2Mat_U0->img_rows_V_empty_n(src_rows_V_c_empty_n);
    AXIvideo2Mat_U0->img_rows_V_read(AXIvideo2Mat_U0_img_rows_V_read);
    AXIvideo2Mat_U0->img_cols_V_dout(src_cols_V_c_dout);
    AXIvideo2Mat_U0->img_cols_V_empty_n(src_cols_V_c_empty_n);
    AXIvideo2Mat_U0->img_cols_V_read(AXIvideo2Mat_U0_img_cols_V_read);
    AXIvideo2Mat_U0->img_data_stream_0_V_din(AXIvideo2Mat_U0_img_data_stream_0_V_din);
    AXIvideo2Mat_U0->img_data_stream_0_V_full_n(src_data_stream_0_V_full_n);
    AXIvideo2Mat_U0->img_data_stream_0_V_write(AXIvideo2Mat_U0_img_data_stream_0_V_write);
    AXIvideo2Mat_U0->img_data_stream_1_V_din(AXIvideo2Mat_U0_img_data_stream_1_V_din);
    AXIvideo2Mat_U0->img_data_stream_1_V_full_n(src_data_stream_1_V_full_n);
    AXIvideo2Mat_U0->img_data_stream_1_V_write(AXIvideo2Mat_U0_img_data_stream_1_V_write);
    AXIvideo2Mat_U0->img_data_stream_2_V_din(AXIvideo2Mat_U0_img_data_stream_2_V_din);
    AXIvideo2Mat_U0->img_data_stream_2_V_full_n(src_data_stream_2_V_full_n);
    AXIvideo2Mat_U0->img_data_stream_2_V_write(AXIvideo2Mat_U0_img_data_stream_2_V_write);
    AXIvideo2Mat_U0->img_rows_V_out_din(AXIvideo2Mat_U0_img_rows_V_out_din);
    AXIvideo2Mat_U0->img_rows_V_out_full_n(src_rows_V_c22_full_n);
    AXIvideo2Mat_U0->img_rows_V_out_write(AXIvideo2Mat_U0_img_rows_V_out_write);
    AXIvideo2Mat_U0->img_cols_V_out_din(AXIvideo2Mat_U0_img_cols_V_out_din);
    AXIvideo2Mat_U0->img_cols_V_out_full_n(src_cols_V_c23_full_n);
    AXIvideo2Mat_U0->img_cols_V_out_write(AXIvideo2Mat_U0_img_cols_V_out_write);
    CvtColor_1_U0 = new CvtColor_1("CvtColor_1_U0");
    CvtColor_1_U0->ap_clk(ap_clk);
    CvtColor_1_U0->ap_rst(ap_rst_n_inv);
    CvtColor_1_U0->ap_start(CvtColor_1_U0_ap_start);
    CvtColor_1_U0->start_full_n(start_for_GaussianBlur_U0_full_n);
    CvtColor_1_U0->ap_done(CvtColor_1_U0_ap_done);
    CvtColor_1_U0->ap_continue(CvtColor_1_U0_ap_continue);
    CvtColor_1_U0->ap_idle(CvtColor_1_U0_ap_idle);
    CvtColor_1_U0->ap_ready(CvtColor_1_U0_ap_ready);
    CvtColor_1_U0->start_out(CvtColor_1_U0_start_out);
    CvtColor_1_U0->start_write(CvtColor_1_U0_start_write);
    CvtColor_1_U0->p_src_rows_V_dout(src_rows_V_c22_dout);
    CvtColor_1_U0->p_src_rows_V_empty_n(src_rows_V_c22_empty_n);
    CvtColor_1_U0->p_src_rows_V_read(CvtColor_1_U0_p_src_rows_V_read);
    CvtColor_1_U0->p_src_cols_V_dout(src_cols_V_c23_dout);
    CvtColor_1_U0->p_src_cols_V_empty_n(src_cols_V_c23_empty_n);
    CvtColor_1_U0->p_src_cols_V_read(CvtColor_1_U0_p_src_cols_V_read);
    CvtColor_1_U0->p_src_data_stream_0_V_dout(src_data_stream_0_V_dout);
    CvtColor_1_U0->p_src_data_stream_0_V_empty_n(src_data_stream_0_V_empty_n);
    CvtColor_1_U0->p_src_data_stream_0_V_read(CvtColor_1_U0_p_src_data_stream_0_V_read);
    CvtColor_1_U0->p_src_data_stream_1_V_dout(src_data_stream_1_V_dout);
    CvtColor_1_U0->p_src_data_stream_1_V_empty_n(src_data_stream_1_V_empty_n);
    CvtColor_1_U0->p_src_data_stream_1_V_read(CvtColor_1_U0_p_src_data_stream_1_V_read);
    CvtColor_1_U0->p_src_data_stream_2_V_dout(src_data_stream_2_V_dout);
    CvtColor_1_U0->p_src_data_stream_2_V_empty_n(src_data_stream_2_V_empty_n);
    CvtColor_1_U0->p_src_data_stream_2_V_read(CvtColor_1_U0_p_src_data_stream_2_V_read);
    CvtColor_1_U0->p_dst_data_stream_V_din(CvtColor_1_U0_p_dst_data_stream_V_din);
    CvtColor_1_U0->p_dst_data_stream_V_full_n(gray_data_stream_0_s_full_n);
    CvtColor_1_U0->p_dst_data_stream_V_write(CvtColor_1_U0_p_dst_data_stream_V_write);
    GaussianBlur_U0 = new GaussianBlur("GaussianBlur_U0");
    GaussianBlur_U0->ap_clk(ap_clk);
    GaussianBlur_U0->ap_rst(ap_rst_n_inv);
    GaussianBlur_U0->ap_start(GaussianBlur_U0_ap_start);
    GaussianBlur_U0->start_full_n(start_for_Duplicate_U0_full_n);
    GaussianBlur_U0->ap_done(GaussianBlur_U0_ap_done);
    GaussianBlur_U0->ap_continue(GaussianBlur_U0_ap_continue);
    GaussianBlur_U0->ap_idle(GaussianBlur_U0_ap_idle);
    GaussianBlur_U0->ap_ready(GaussianBlur_U0_ap_ready);
    GaussianBlur_U0->start_out(GaussianBlur_U0_start_out);
    GaussianBlur_U0->start_write(GaussianBlur_U0_start_write);
    GaussianBlur_U0->p_src_data_stream_V_dout(gray_data_stream_0_s_dout);
    GaussianBlur_U0->p_src_data_stream_V_empty_n(gray_data_stream_0_s_empty_n);
    GaussianBlur_U0->p_src_data_stream_V_read(GaussianBlur_U0_p_src_data_stream_V_read);
    GaussianBlur_U0->p_dst_data_stream_V_din(GaussianBlur_U0_p_dst_data_stream_V_din);
    GaussianBlur_U0->p_dst_data_stream_V_full_n(blurred_data_stream_s_full_n);
    GaussianBlur_U0->p_dst_data_stream_V_write(GaussianBlur_U0_p_dst_data_stream_V_write);
    Duplicate_U0 = new Duplicate("Duplicate_U0");
    Duplicate_U0->ap_clk(ap_clk);
    Duplicate_U0->ap_rst(ap_rst_n_inv);
    Duplicate_U0->ap_start(Duplicate_U0_ap_start);
    Duplicate_U0->start_full_n(Duplicate_U0_start_full_n);
    Duplicate_U0->ap_done(Duplicate_U0_ap_done);
    Duplicate_U0->ap_continue(Duplicate_U0_ap_continue);
    Duplicate_U0->ap_idle(Duplicate_U0_ap_idle);
    Duplicate_U0->ap_ready(Duplicate_U0_ap_ready);
    Duplicate_U0->start_out(Duplicate_U0_start_out);
    Duplicate_U0->start_write(Duplicate_U0_start_write);
    Duplicate_U0->src_data_stream_V_dout(blurred_data_stream_s_dout);
    Duplicate_U0->src_data_stream_V_empty_n(blurred_data_stream_s_empty_n);
    Duplicate_U0->src_data_stream_V_read(Duplicate_U0_src_data_stream_V_read);
    Duplicate_U0->dst1_data_stream_V_din(Duplicate_U0_dst1_data_stream_V_din);
    Duplicate_U0->dst1_data_stream_V_full_n(gray1_data_stream_0_full_n);
    Duplicate_U0->dst1_data_stream_V_write(Duplicate_U0_dst1_data_stream_V_write);
    Duplicate_U0->dst2_data_stream_V_din(Duplicate_U0_dst2_data_stream_V_din);
    Duplicate_U0->dst2_data_stream_V_full_n(gray2_data_stream_0_full_n);
    Duplicate_U0->dst2_data_stream_V_write(Duplicate_U0_dst2_data_stream_V_write);
    Sobel_U0 = new Sobel("Sobel_U0");
    Sobel_U0->ap_clk(ap_clk);
    Sobel_U0->ap_rst(ap_rst_n_inv);
    Sobel_U0->ap_start(Sobel_U0_ap_start);
    Sobel_U0->ap_done(Sobel_U0_ap_done);
    Sobel_U0->ap_continue(Sobel_U0_ap_continue);
    Sobel_U0->ap_idle(Sobel_U0_ap_idle);
    Sobel_U0->ap_ready(Sobel_U0_ap_ready);
    Sobel_U0->p_src_data_stream_V_dout(gray1_data_stream_0_dout);
    Sobel_U0->p_src_data_stream_V_empty_n(gray1_data_stream_0_empty_n);
    Sobel_U0->p_src_data_stream_V_read(Sobel_U0_p_src_data_stream_V_read);
    Sobel_U0->p_dst_data_stream_V_din(Sobel_U0_p_dst_data_stream_V_din);
    Sobel_U0->p_dst_data_stream_V_full_n(sobel_x_data_stream_s_full_n);
    Sobel_U0->p_dst_data_stream_V_write(Sobel_U0_p_dst_data_stream_V_write);
    Sobel_1_U0 = new Sobel_1("Sobel_1_U0");
    Sobel_1_U0->ap_clk(ap_clk);
    Sobel_1_U0->ap_rst(ap_rst_n_inv);
    Sobel_1_U0->ap_start(Sobel_1_U0_ap_start);
    Sobel_1_U0->ap_done(Sobel_1_U0_ap_done);
    Sobel_1_U0->ap_continue(Sobel_1_U0_ap_continue);
    Sobel_1_U0->ap_idle(Sobel_1_U0_ap_idle);
    Sobel_1_U0->ap_ready(Sobel_1_U0_ap_ready);
    Sobel_1_U0->p_src_data_stream_V_dout(gray2_data_stream_0_dout);
    Sobel_1_U0->p_src_data_stream_V_empty_n(gray2_data_stream_0_empty_n);
    Sobel_1_U0->p_src_data_stream_V_read(Sobel_1_U0_p_src_data_stream_V_read);
    Sobel_1_U0->p_dst_data_stream_V_din(Sobel_1_U0_p_dst_data_stream_V_din);
    Sobel_1_U0->p_dst_data_stream_V_full_n(sobel_y_data_stream_s_full_n);
    Sobel_1_U0->p_dst_data_stream_V_write(Sobel_1_U0_p_dst_data_stream_V_write);
    AddWeighted_U0 = new AddWeighted("AddWeighted_U0");
    AddWeighted_U0->ap_clk(ap_clk);
    AddWeighted_U0->ap_rst(ap_rst_n_inv);
    AddWeighted_U0->ap_start(AddWeighted_U0_ap_start);
    AddWeighted_U0->start_full_n(start_for_CvtColor_U0_full_n);
    AddWeighted_U0->ap_done(AddWeighted_U0_ap_done);
    AddWeighted_U0->ap_continue(AddWeighted_U0_ap_continue);
    AddWeighted_U0->ap_idle(AddWeighted_U0_ap_idle);
    AddWeighted_U0->ap_ready(AddWeighted_U0_ap_ready);
    AddWeighted_U0->start_out(AddWeighted_U0_start_out);
    AddWeighted_U0->start_write(AddWeighted_U0_start_write);
    AddWeighted_U0->src1_data_stream_V_dout(sobel_x_data_stream_s_dout);
    AddWeighted_U0->src1_data_stream_V_empty_n(sobel_x_data_stream_s_empty_n);
    AddWeighted_U0->src1_data_stream_V_read(AddWeighted_U0_src1_data_stream_V_read);
    AddWeighted_U0->src2_data_stream_V_dout(sobel_y_data_stream_s_dout);
    AddWeighted_U0->src2_data_stream_V_empty_n(sobel_y_data_stream_s_empty_n);
    AddWeighted_U0->src2_data_stream_V_read(AddWeighted_U0_src2_data_stream_V_read);
    AddWeighted_U0->dst_rows_V_dout(sobel_g_rows_V_c_dout);
    AddWeighted_U0->dst_rows_V_empty_n(sobel_g_rows_V_c_empty_n);
    AddWeighted_U0->dst_rows_V_read(AddWeighted_U0_dst_rows_V_read);
    AddWeighted_U0->dst_cols_V_dout(sobel_g_cols_V_c_dout);
    AddWeighted_U0->dst_cols_V_empty_n(sobel_g_cols_V_c_empty_n);
    AddWeighted_U0->dst_cols_V_read(AddWeighted_U0_dst_cols_V_read);
    AddWeighted_U0->dst_data_stream_V_din(AddWeighted_U0_dst_data_stream_V_din);
    AddWeighted_U0->dst_data_stream_V_full_n(sobel_g_data_stream_s_full_n);
    AddWeighted_U0->dst_data_stream_V_write(AddWeighted_U0_dst_data_stream_V_write);
    AddWeighted_U0->dst_rows_V_out_din(AddWeighted_U0_dst_rows_V_out_din);
    AddWeighted_U0->dst_rows_V_out_full_n(sobel_g_rows_V_c24_full_n);
    AddWeighted_U0->dst_rows_V_out_write(AddWeighted_U0_dst_rows_V_out_write);
    AddWeighted_U0->dst_cols_V_out_din(AddWeighted_U0_dst_cols_V_out_din);
    AddWeighted_U0->dst_cols_V_out_full_n(sobel_g_cols_V_c25_full_n);
    AddWeighted_U0->dst_cols_V_out_write(AddWeighted_U0_dst_cols_V_out_write);
    CvtColor_U0 = new CvtColor("CvtColor_U0");
    CvtColor_U0->ap_clk(ap_clk);
    CvtColor_U0->ap_rst(ap_rst_n_inv);
    CvtColor_U0->ap_start(CvtColor_U0_ap_start);
    CvtColor_U0->start_full_n(start_for_Mat2AXIvideo_U0_full_n);
    CvtColor_U0->ap_done(CvtColor_U0_ap_done);
    CvtColor_U0->ap_continue(CvtColor_U0_ap_continue);
    CvtColor_U0->ap_idle(CvtColor_U0_ap_idle);
    CvtColor_U0->ap_ready(CvtColor_U0_ap_ready);
    CvtColor_U0->start_out(CvtColor_U0_start_out);
    CvtColor_U0->start_write(CvtColor_U0_start_write);
    CvtColor_U0->p_src_rows_V_dout(sobel_g_rows_V_c24_dout);
    CvtColor_U0->p_src_rows_V_empty_n(sobel_g_rows_V_c24_empty_n);
    CvtColor_U0->p_src_rows_V_read(CvtColor_U0_p_src_rows_V_read);
    CvtColor_U0->p_src_cols_V_dout(sobel_g_cols_V_c25_dout);
    CvtColor_U0->p_src_cols_V_empty_n(sobel_g_cols_V_c25_empty_n);
    CvtColor_U0->p_src_cols_V_read(CvtColor_U0_p_src_cols_V_read);
    CvtColor_U0->p_src_data_stream_V_dout(sobel_g_data_stream_s_dout);
    CvtColor_U0->p_src_data_stream_V_empty_n(sobel_g_data_stream_s_empty_n);
    CvtColor_U0->p_src_data_stream_V_read(CvtColor_U0_p_src_data_stream_V_read);
    CvtColor_U0->p_dst_data_stream_0_V_din(CvtColor_U0_p_dst_data_stream_0_V_din);
    CvtColor_U0->p_dst_data_stream_0_V_full_n(dst_data_stream_0_V_full_n);
    CvtColor_U0->p_dst_data_stream_0_V_write(CvtColor_U0_p_dst_data_stream_0_V_write);
    CvtColor_U0->p_dst_data_stream_1_V_din(CvtColor_U0_p_dst_data_stream_1_V_din);
    CvtColor_U0->p_dst_data_stream_1_V_full_n(dst_data_stream_1_V_full_n);
    CvtColor_U0->p_dst_data_stream_1_V_write(CvtColor_U0_p_dst_data_stream_1_V_write);
    CvtColor_U0->p_dst_data_stream_2_V_din(CvtColor_U0_p_dst_data_stream_2_V_din);
    CvtColor_U0->p_dst_data_stream_2_V_full_n(dst_data_stream_2_V_full_n);
    CvtColor_U0->p_dst_data_stream_2_V_write(CvtColor_U0_p_dst_data_stream_2_V_write);
    Mat2AXIvideo_U0 = new Mat2AXIvideo("Mat2AXIvideo_U0");
    Mat2AXIvideo_U0->ap_clk(ap_clk);
    Mat2AXIvideo_U0->ap_rst(ap_rst_n_inv);
    Mat2AXIvideo_U0->ap_start(Mat2AXIvideo_U0_ap_start);
    Mat2AXIvideo_U0->ap_done(Mat2AXIvideo_U0_ap_done);
    Mat2AXIvideo_U0->ap_continue(Mat2AXIvideo_U0_ap_continue);
    Mat2AXIvideo_U0->ap_idle(Mat2AXIvideo_U0_ap_idle);
    Mat2AXIvideo_U0->ap_ready(Mat2AXIvideo_U0_ap_ready);
    Mat2AXIvideo_U0->img_data_stream_0_V_dout(dst_data_stream_0_V_dout);
    Mat2AXIvideo_U0->img_data_stream_0_V_empty_n(dst_data_stream_0_V_empty_n);
    Mat2AXIvideo_U0->img_data_stream_0_V_read(Mat2AXIvideo_U0_img_data_stream_0_V_read);
    Mat2AXIvideo_U0->img_data_stream_1_V_dout(dst_data_stream_1_V_dout);
    Mat2AXIvideo_U0->img_data_stream_1_V_empty_n(dst_data_stream_1_V_empty_n);
    Mat2AXIvideo_U0->img_data_stream_1_V_read(Mat2AXIvideo_U0_img_data_stream_1_V_read);
    Mat2AXIvideo_U0->img_data_stream_2_V_dout(dst_data_stream_2_V_dout);
    Mat2AXIvideo_U0->img_data_stream_2_V_empty_n(dst_data_stream_2_V_empty_n);
    Mat2AXIvideo_U0->img_data_stream_2_V_read(Mat2AXIvideo_U0_img_data_stream_2_V_read);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TDATA(Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TVALID(Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TREADY(OUTPUT_STREAM_TREADY);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TKEEP(Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TSTRB(Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TUSER(Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TLAST(Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TID(Mat2AXIvideo_U0_OUTPUT_STREAM_TID);
    Mat2AXIvideo_U0->OUTPUT_STREAM_TDEST(Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST);
    src_rows_V_c_U = new fifo_w12_d2_A("src_rows_V_c_U");
    src_rows_V_c_U->clk(ap_clk);
    src_rows_V_c_U->reset(ap_rst_n_inv);
    src_rows_V_c_U->if_read_ce(ap_var_for_const0);
    src_rows_V_c_U->if_write_ce(ap_var_for_const0);
    src_rows_V_c_U->if_din(Block_proc_U0_src_rows_V_out_din);
    src_rows_V_c_U->if_full_n(src_rows_V_c_full_n);
    src_rows_V_c_U->if_write(Block_proc_U0_src_rows_V_out_write);
    src_rows_V_c_U->if_dout(src_rows_V_c_dout);
    src_rows_V_c_U->if_empty_n(src_rows_V_c_empty_n);
    src_rows_V_c_U->if_read(AXIvideo2Mat_U0_img_rows_V_read);
    src_cols_V_c_U = new fifo_w12_d2_A("src_cols_V_c_U");
    src_cols_V_c_U->clk(ap_clk);
    src_cols_V_c_U->reset(ap_rst_n_inv);
    src_cols_V_c_U->if_read_ce(ap_var_for_const0);
    src_cols_V_c_U->if_write_ce(ap_var_for_const0);
    src_cols_V_c_U->if_din(Block_proc_U0_src_cols_V_out_din);
    src_cols_V_c_U->if_full_n(src_cols_V_c_full_n);
    src_cols_V_c_U->if_write(Block_proc_U0_src_cols_V_out_write);
    src_cols_V_c_U->if_dout(src_cols_V_c_dout);
    src_cols_V_c_U->if_empty_n(src_cols_V_c_empty_n);
    src_cols_V_c_U->if_read(AXIvideo2Mat_U0_img_cols_V_read);
    sobel_g_rows_V_c_U = new fifo_w12_d7_A("sobel_g_rows_V_c_U");
    sobel_g_rows_V_c_U->clk(ap_clk);
    sobel_g_rows_V_c_U->reset(ap_rst_n_inv);
    sobel_g_rows_V_c_U->if_read_ce(ap_var_for_const0);
    sobel_g_rows_V_c_U->if_write_ce(ap_var_for_const0);
    sobel_g_rows_V_c_U->if_din(Block_proc_U0_sobel_g_rows_V_out_din);
    sobel_g_rows_V_c_U->if_full_n(sobel_g_rows_V_c_full_n);
    sobel_g_rows_V_c_U->if_write(Block_proc_U0_sobel_g_rows_V_out_write);
    sobel_g_rows_V_c_U->if_dout(sobel_g_rows_V_c_dout);
    sobel_g_rows_V_c_U->if_empty_n(sobel_g_rows_V_c_empty_n);
    sobel_g_rows_V_c_U->if_read(AddWeighted_U0_dst_rows_V_read);
    sobel_g_cols_V_c_U = new fifo_w12_d7_A("sobel_g_cols_V_c_U");
    sobel_g_cols_V_c_U->clk(ap_clk);
    sobel_g_cols_V_c_U->reset(ap_rst_n_inv);
    sobel_g_cols_V_c_U->if_read_ce(ap_var_for_const0);
    sobel_g_cols_V_c_U->if_write_ce(ap_var_for_const0);
    sobel_g_cols_V_c_U->if_din(Block_proc_U0_sobel_g_cols_V_out_din);
    sobel_g_cols_V_c_U->if_full_n(sobel_g_cols_V_c_full_n);
    sobel_g_cols_V_c_U->if_write(Block_proc_U0_sobel_g_cols_V_out_write);
    sobel_g_cols_V_c_U->if_dout(sobel_g_cols_V_c_dout);
    sobel_g_cols_V_c_U->if_empty_n(sobel_g_cols_V_c_empty_n);
    sobel_g_cols_V_c_U->if_read(AddWeighted_U0_dst_cols_V_read);
    src_data_stream_0_V_U = new fifo_w8_d2_A("src_data_stream_0_V_U");
    src_data_stream_0_V_U->clk(ap_clk);
    src_data_stream_0_V_U->reset(ap_rst_n_inv);
    src_data_stream_0_V_U->if_read_ce(ap_var_for_const0);
    src_data_stream_0_V_U->if_write_ce(ap_var_for_const0);
    src_data_stream_0_V_U->if_din(AXIvideo2Mat_U0_img_data_stream_0_V_din);
    src_data_stream_0_V_U->if_full_n(src_data_stream_0_V_full_n);
    src_data_stream_0_V_U->if_write(AXIvideo2Mat_U0_img_data_stream_0_V_write);
    src_data_stream_0_V_U->if_dout(src_data_stream_0_V_dout);
    src_data_stream_0_V_U->if_empty_n(src_data_stream_0_V_empty_n);
    src_data_stream_0_V_U->if_read(CvtColor_1_U0_p_src_data_stream_0_V_read);
    src_data_stream_1_V_U = new fifo_w8_d2_A("src_data_stream_1_V_U");
    src_data_stream_1_V_U->clk(ap_clk);
    src_data_stream_1_V_U->reset(ap_rst_n_inv);
    src_data_stream_1_V_U->if_read_ce(ap_var_for_const0);
    src_data_stream_1_V_U->if_write_ce(ap_var_for_const0);
    src_data_stream_1_V_U->if_din(AXIvideo2Mat_U0_img_data_stream_1_V_din);
    src_data_stream_1_V_U->if_full_n(src_data_stream_1_V_full_n);
    src_data_stream_1_V_U->if_write(AXIvideo2Mat_U0_img_data_stream_1_V_write);
    src_data_stream_1_V_U->if_dout(src_data_stream_1_V_dout);
    src_data_stream_1_V_U->if_empty_n(src_data_stream_1_V_empty_n);
    src_data_stream_1_V_U->if_read(CvtColor_1_U0_p_src_data_stream_1_V_read);
    src_data_stream_2_V_U = new fifo_w8_d2_A("src_data_stream_2_V_U");
    src_data_stream_2_V_U->clk(ap_clk);
    src_data_stream_2_V_U->reset(ap_rst_n_inv);
    src_data_stream_2_V_U->if_read_ce(ap_var_for_const0);
    src_data_stream_2_V_U->if_write_ce(ap_var_for_const0);
    src_data_stream_2_V_U->if_din(AXIvideo2Mat_U0_img_data_stream_2_V_din);
    src_data_stream_2_V_U->if_full_n(src_data_stream_2_V_full_n);
    src_data_stream_2_V_U->if_write(AXIvideo2Mat_U0_img_data_stream_2_V_write);
    src_data_stream_2_V_U->if_dout(src_data_stream_2_V_dout);
    src_data_stream_2_V_U->if_empty_n(src_data_stream_2_V_empty_n);
    src_data_stream_2_V_U->if_read(CvtColor_1_U0_p_src_data_stream_2_V_read);
    src_rows_V_c22_U = new fifo_w12_d2_A("src_rows_V_c22_U");
    src_rows_V_c22_U->clk(ap_clk);
    src_rows_V_c22_U->reset(ap_rst_n_inv);
    src_rows_V_c22_U->if_read_ce(ap_var_for_const0);
    src_rows_V_c22_U->if_write_ce(ap_var_for_const0);
    src_rows_V_c22_U->if_din(AXIvideo2Mat_U0_img_rows_V_out_din);
    src_rows_V_c22_U->if_full_n(src_rows_V_c22_full_n);
    src_rows_V_c22_U->if_write(AXIvideo2Mat_U0_img_rows_V_out_write);
    src_rows_V_c22_U->if_dout(src_rows_V_c22_dout);
    src_rows_V_c22_U->if_empty_n(src_rows_V_c22_empty_n);
    src_rows_V_c22_U->if_read(CvtColor_1_U0_p_src_rows_V_read);
    src_cols_V_c23_U = new fifo_w12_d2_A("src_cols_V_c23_U");
    src_cols_V_c23_U->clk(ap_clk);
    src_cols_V_c23_U->reset(ap_rst_n_inv);
    src_cols_V_c23_U->if_read_ce(ap_var_for_const0);
    src_cols_V_c23_U->if_write_ce(ap_var_for_const0);
    src_cols_V_c23_U->if_din(AXIvideo2Mat_U0_img_cols_V_out_din);
    src_cols_V_c23_U->if_full_n(src_cols_V_c23_full_n);
    src_cols_V_c23_U->if_write(AXIvideo2Mat_U0_img_cols_V_out_write);
    src_cols_V_c23_U->if_dout(src_cols_V_c23_dout);
    src_cols_V_c23_U->if_empty_n(src_cols_V_c23_empty_n);
    src_cols_V_c23_U->if_read(CvtColor_1_U0_p_src_cols_V_read);
    gray_data_stream_0_s_U = new fifo_w8_d2_A("gray_data_stream_0_s_U");
    gray_data_stream_0_s_U->clk(ap_clk);
    gray_data_stream_0_s_U->reset(ap_rst_n_inv);
    gray_data_stream_0_s_U->if_read_ce(ap_var_for_const0);
    gray_data_stream_0_s_U->if_write_ce(ap_var_for_const0);
    gray_data_stream_0_s_U->if_din(CvtColor_1_U0_p_dst_data_stream_V_din);
    gray_data_stream_0_s_U->if_full_n(gray_data_stream_0_s_full_n);
    gray_data_stream_0_s_U->if_write(CvtColor_1_U0_p_dst_data_stream_V_write);
    gray_data_stream_0_s_U->if_dout(gray_data_stream_0_s_dout);
    gray_data_stream_0_s_U->if_empty_n(gray_data_stream_0_s_empty_n);
    gray_data_stream_0_s_U->if_read(GaussianBlur_U0_p_src_data_stream_V_read);
    blurred_data_stream_s_U = new fifo_w8_d2_A("blurred_data_stream_s_U");
    blurred_data_stream_s_U->clk(ap_clk);
    blurred_data_stream_s_U->reset(ap_rst_n_inv);
    blurred_data_stream_s_U->if_read_ce(ap_var_for_const0);
    blurred_data_stream_s_U->if_write_ce(ap_var_for_const0);
    blurred_data_stream_s_U->if_din(GaussianBlur_U0_p_dst_data_stream_V_din);
    blurred_data_stream_s_U->if_full_n(blurred_data_stream_s_full_n);
    blurred_data_stream_s_U->if_write(GaussianBlur_U0_p_dst_data_stream_V_write);
    blurred_data_stream_s_U->if_dout(blurred_data_stream_s_dout);
    blurred_data_stream_s_U->if_empty_n(blurred_data_stream_s_empty_n);
    blurred_data_stream_s_U->if_read(Duplicate_U0_src_data_stream_V_read);
    gray1_data_stream_0_U = new fifo_w8_d2_A("gray1_data_stream_0_U");
    gray1_data_stream_0_U->clk(ap_clk);
    gray1_data_stream_0_U->reset(ap_rst_n_inv);
    gray1_data_stream_0_U->if_read_ce(ap_var_for_const0);
    gray1_data_stream_0_U->if_write_ce(ap_var_for_const0);
    gray1_data_stream_0_U->if_din(Duplicate_U0_dst1_data_stream_V_din);
    gray1_data_stream_0_U->if_full_n(gray1_data_stream_0_full_n);
    gray1_data_stream_0_U->if_write(Duplicate_U0_dst1_data_stream_V_write);
    gray1_data_stream_0_U->if_dout(gray1_data_stream_0_dout);
    gray1_data_stream_0_U->if_empty_n(gray1_data_stream_0_empty_n);
    gray1_data_stream_0_U->if_read(Sobel_U0_p_src_data_stream_V_read);
    gray2_data_stream_0_U = new fifo_w8_d2_A("gray2_data_stream_0_U");
    gray2_data_stream_0_U->clk(ap_clk);
    gray2_data_stream_0_U->reset(ap_rst_n_inv);
    gray2_data_stream_0_U->if_read_ce(ap_var_for_const0);
    gray2_data_stream_0_U->if_write_ce(ap_var_for_const0);
    gray2_data_stream_0_U->if_din(Duplicate_U0_dst2_data_stream_V_din);
    gray2_data_stream_0_U->if_full_n(gray2_data_stream_0_full_n);
    gray2_data_stream_0_U->if_write(Duplicate_U0_dst2_data_stream_V_write);
    gray2_data_stream_0_U->if_dout(gray2_data_stream_0_dout);
    gray2_data_stream_0_U->if_empty_n(gray2_data_stream_0_empty_n);
    gray2_data_stream_0_U->if_read(Sobel_1_U0_p_src_data_stream_V_read);
    sobel_x_data_stream_s_U = new fifo_w8_d2_A("sobel_x_data_stream_s_U");
    sobel_x_data_stream_s_U->clk(ap_clk);
    sobel_x_data_stream_s_U->reset(ap_rst_n_inv);
    sobel_x_data_stream_s_U->if_read_ce(ap_var_for_const0);
    sobel_x_data_stream_s_U->if_write_ce(ap_var_for_const0);
    sobel_x_data_stream_s_U->if_din(Sobel_U0_p_dst_data_stream_V_din);
    sobel_x_data_stream_s_U->if_full_n(sobel_x_data_stream_s_full_n);
    sobel_x_data_stream_s_U->if_write(Sobel_U0_p_dst_data_stream_V_write);
    sobel_x_data_stream_s_U->if_dout(sobel_x_data_stream_s_dout);
    sobel_x_data_stream_s_U->if_empty_n(sobel_x_data_stream_s_empty_n);
    sobel_x_data_stream_s_U->if_read(AddWeighted_U0_src1_data_stream_V_read);
    sobel_y_data_stream_s_U = new fifo_w8_d2_A("sobel_y_data_stream_s_U");
    sobel_y_data_stream_s_U->clk(ap_clk);
    sobel_y_data_stream_s_U->reset(ap_rst_n_inv);
    sobel_y_data_stream_s_U->if_read_ce(ap_var_for_const0);
    sobel_y_data_stream_s_U->if_write_ce(ap_var_for_const0);
    sobel_y_data_stream_s_U->if_din(Sobel_1_U0_p_dst_data_stream_V_din);
    sobel_y_data_stream_s_U->if_full_n(sobel_y_data_stream_s_full_n);
    sobel_y_data_stream_s_U->if_write(Sobel_1_U0_p_dst_data_stream_V_write);
    sobel_y_data_stream_s_U->if_dout(sobel_y_data_stream_s_dout);
    sobel_y_data_stream_s_U->if_empty_n(sobel_y_data_stream_s_empty_n);
    sobel_y_data_stream_s_U->if_read(AddWeighted_U0_src2_data_stream_V_read);
    sobel_g_data_stream_s_U = new fifo_w8_d2_A("sobel_g_data_stream_s_U");
    sobel_g_data_stream_s_U->clk(ap_clk);
    sobel_g_data_stream_s_U->reset(ap_rst_n_inv);
    sobel_g_data_stream_s_U->if_read_ce(ap_var_for_const0);
    sobel_g_data_stream_s_U->if_write_ce(ap_var_for_const0);
    sobel_g_data_stream_s_U->if_din(AddWeighted_U0_dst_data_stream_V_din);
    sobel_g_data_stream_s_U->if_full_n(sobel_g_data_stream_s_full_n);
    sobel_g_data_stream_s_U->if_write(AddWeighted_U0_dst_data_stream_V_write);
    sobel_g_data_stream_s_U->if_dout(sobel_g_data_stream_s_dout);
    sobel_g_data_stream_s_U->if_empty_n(sobel_g_data_stream_s_empty_n);
    sobel_g_data_stream_s_U->if_read(CvtColor_U0_p_src_data_stream_V_read);
    sobel_g_rows_V_c24_U = new fifo_w12_d2_A("sobel_g_rows_V_c24_U");
    sobel_g_rows_V_c24_U->clk(ap_clk);
    sobel_g_rows_V_c24_U->reset(ap_rst_n_inv);
    sobel_g_rows_V_c24_U->if_read_ce(ap_var_for_const0);
    sobel_g_rows_V_c24_U->if_write_ce(ap_var_for_const0);
    sobel_g_rows_V_c24_U->if_din(AddWeighted_U0_dst_rows_V_out_din);
    sobel_g_rows_V_c24_U->if_full_n(sobel_g_rows_V_c24_full_n);
    sobel_g_rows_V_c24_U->if_write(AddWeighted_U0_dst_rows_V_out_write);
    sobel_g_rows_V_c24_U->if_dout(sobel_g_rows_V_c24_dout);
    sobel_g_rows_V_c24_U->if_empty_n(sobel_g_rows_V_c24_empty_n);
    sobel_g_rows_V_c24_U->if_read(CvtColor_U0_p_src_rows_V_read);
    sobel_g_cols_V_c25_U = new fifo_w12_d2_A("sobel_g_cols_V_c25_U");
    sobel_g_cols_V_c25_U->clk(ap_clk);
    sobel_g_cols_V_c25_U->reset(ap_rst_n_inv);
    sobel_g_cols_V_c25_U->if_read_ce(ap_var_for_const0);
    sobel_g_cols_V_c25_U->if_write_ce(ap_var_for_const0);
    sobel_g_cols_V_c25_U->if_din(AddWeighted_U0_dst_cols_V_out_din);
    sobel_g_cols_V_c25_U->if_full_n(sobel_g_cols_V_c25_full_n);
    sobel_g_cols_V_c25_U->if_write(AddWeighted_U0_dst_cols_V_out_write);
    sobel_g_cols_V_c25_U->if_dout(sobel_g_cols_V_c25_dout);
    sobel_g_cols_V_c25_U->if_empty_n(sobel_g_cols_V_c25_empty_n);
    sobel_g_cols_V_c25_U->if_read(CvtColor_U0_p_src_cols_V_read);
    dst_data_stream_0_V_U = new fifo_w8_d2_A("dst_data_stream_0_V_U");
    dst_data_stream_0_V_U->clk(ap_clk);
    dst_data_stream_0_V_U->reset(ap_rst_n_inv);
    dst_data_stream_0_V_U->if_read_ce(ap_var_for_const0);
    dst_data_stream_0_V_U->if_write_ce(ap_var_for_const0);
    dst_data_stream_0_V_U->if_din(CvtColor_U0_p_dst_data_stream_0_V_din);
    dst_data_stream_0_V_U->if_full_n(dst_data_stream_0_V_full_n);
    dst_data_stream_0_V_U->if_write(CvtColor_U0_p_dst_data_stream_0_V_write);
    dst_data_stream_0_V_U->if_dout(dst_data_stream_0_V_dout);
    dst_data_stream_0_V_U->if_empty_n(dst_data_stream_0_V_empty_n);
    dst_data_stream_0_V_U->if_read(Mat2AXIvideo_U0_img_data_stream_0_V_read);
    dst_data_stream_1_V_U = new fifo_w8_d2_A("dst_data_stream_1_V_U");
    dst_data_stream_1_V_U->clk(ap_clk);
    dst_data_stream_1_V_U->reset(ap_rst_n_inv);
    dst_data_stream_1_V_U->if_read_ce(ap_var_for_const0);
    dst_data_stream_1_V_U->if_write_ce(ap_var_for_const0);
    dst_data_stream_1_V_U->if_din(CvtColor_U0_p_dst_data_stream_1_V_din);
    dst_data_stream_1_V_U->if_full_n(dst_data_stream_1_V_full_n);
    dst_data_stream_1_V_U->if_write(CvtColor_U0_p_dst_data_stream_1_V_write);
    dst_data_stream_1_V_U->if_dout(dst_data_stream_1_V_dout);
    dst_data_stream_1_V_U->if_empty_n(dst_data_stream_1_V_empty_n);
    dst_data_stream_1_V_U->if_read(Mat2AXIvideo_U0_img_data_stream_1_V_read);
    dst_data_stream_2_V_U = new fifo_w8_d2_A("dst_data_stream_2_V_U");
    dst_data_stream_2_V_U->clk(ap_clk);
    dst_data_stream_2_V_U->reset(ap_rst_n_inv);
    dst_data_stream_2_V_U->if_read_ce(ap_var_for_const0);
    dst_data_stream_2_V_U->if_write_ce(ap_var_for_const0);
    dst_data_stream_2_V_U->if_din(CvtColor_U0_p_dst_data_stream_2_V_din);
    dst_data_stream_2_V_U->if_full_n(dst_data_stream_2_V_full_n);
    dst_data_stream_2_V_U->if_write(CvtColor_U0_p_dst_data_stream_2_V_write);
    dst_data_stream_2_V_U->if_dout(dst_data_stream_2_V_dout);
    dst_data_stream_2_V_U->if_empty_n(dst_data_stream_2_V_empty_n);
    dst_data_stream_2_V_U->if_read(Mat2AXIvideo_U0_img_data_stream_2_V_read);
    start_for_AddWeigvdy_U = new start_for_AddWeigvdy("start_for_AddWeigvdy_U");
    start_for_AddWeigvdy_U->clk(ap_clk);
    start_for_AddWeigvdy_U->reset(ap_rst_n_inv);
    start_for_AddWeigvdy_U->if_read_ce(ap_var_for_const0);
    start_for_AddWeigvdy_U->if_write_ce(ap_var_for_const0);
    start_for_AddWeigvdy_U->if_din(start_for_AddWeighted_U0_din);
    start_for_AddWeigvdy_U->if_full_n(start_for_AddWeighted_U0_full_n);
    start_for_AddWeigvdy_U->if_write(Block_proc_U0_start_write);
    start_for_AddWeigvdy_U->if_dout(start_for_AddWeighted_U0_dout);
    start_for_AddWeigvdy_U->if_empty_n(start_for_AddWeighted_U0_empty_n);
    start_for_AddWeigvdy_U->if_read(AddWeighted_U0_ap_ready);
    start_for_CvtColowdI_U = new start_for_CvtColowdI("start_for_CvtColowdI_U");
    start_for_CvtColowdI_U->clk(ap_clk);
    start_for_CvtColowdI_U->reset(ap_rst_n_inv);
    start_for_CvtColowdI_U->if_read_ce(ap_var_for_const0);
    start_for_CvtColowdI_U->if_write_ce(ap_var_for_const0);
    start_for_CvtColowdI_U->if_din(start_for_CvtColor_1_U0_din);
    start_for_CvtColowdI_U->if_full_n(start_for_CvtColor_1_U0_full_n);
    start_for_CvtColowdI_U->if_write(AXIvideo2Mat_U0_start_write);
    start_for_CvtColowdI_U->if_dout(start_for_CvtColor_1_U0_dout);
    start_for_CvtColowdI_U->if_empty_n(start_for_CvtColor_1_U0_empty_n);
    start_for_CvtColowdI_U->if_read(CvtColor_1_U0_ap_ready);
    start_for_GaussiaxdS_U = new start_for_GaussiaxdS("start_for_GaussiaxdS_U");
    start_for_GaussiaxdS_U->clk(ap_clk);
    start_for_GaussiaxdS_U->reset(ap_rst_n_inv);
    start_for_GaussiaxdS_U->if_read_ce(ap_var_for_const0);
    start_for_GaussiaxdS_U->if_write_ce(ap_var_for_const0);
    start_for_GaussiaxdS_U->if_din(start_for_GaussianBlur_U0_din);
    start_for_GaussiaxdS_U->if_full_n(start_for_GaussianBlur_U0_full_n);
    start_for_GaussiaxdS_U->if_write(CvtColor_1_U0_start_write);
    start_for_GaussiaxdS_U->if_dout(start_for_GaussianBlur_U0_dout);
    start_for_GaussiaxdS_U->if_empty_n(start_for_GaussianBlur_U0_empty_n);
    start_for_GaussiaxdS_U->if_read(GaussianBlur_U0_ap_ready);
    start_for_Duplicayd2_U = new start_for_Duplicayd2("start_for_Duplicayd2_U");
    start_for_Duplicayd2_U->clk(ap_clk);
    start_for_Duplicayd2_U->reset(ap_rst_n_inv);
    start_for_Duplicayd2_U->if_read_ce(ap_var_for_const0);
    start_for_Duplicayd2_U->if_write_ce(ap_var_for_const0);
    start_for_Duplicayd2_U->if_din(start_for_Duplicate_U0_din);
    start_for_Duplicayd2_U->if_full_n(start_for_Duplicate_U0_full_n);
    start_for_Duplicayd2_U->if_write(GaussianBlur_U0_start_write);
    start_for_Duplicayd2_U->if_dout(start_for_Duplicate_U0_dout);
    start_for_Duplicayd2_U->if_empty_n(start_for_Duplicate_U0_empty_n);
    start_for_Duplicayd2_U->if_read(Duplicate_U0_ap_ready);
    start_for_Sobel_U0_U = new start_for_Sobel_U0("start_for_Sobel_U0_U");
    start_for_Sobel_U0_U->clk(ap_clk);
    start_for_Sobel_U0_U->reset(ap_rst_n_inv);
    start_for_Sobel_U0_U->if_read_ce(ap_var_for_const0);
    start_for_Sobel_U0_U->if_write_ce(ap_var_for_const0);
    start_for_Sobel_U0_U->if_din(start_for_Sobel_U0_din);
    start_for_Sobel_U0_U->if_full_n(start_for_Sobel_U0_full_n);
    start_for_Sobel_U0_U->if_write(Duplicate_U0_start_write);
    start_for_Sobel_U0_U->if_dout(start_for_Sobel_U0_dout);
    start_for_Sobel_U0_U->if_empty_n(start_for_Sobel_U0_empty_n);
    start_for_Sobel_U0_U->if_read(Sobel_U0_ap_ready);
    start_for_Sobel_1zec_U = new start_for_Sobel_1zec("start_for_Sobel_1zec_U");
    start_for_Sobel_1zec_U->clk(ap_clk);
    start_for_Sobel_1zec_U->reset(ap_rst_n_inv);
    start_for_Sobel_1zec_U->if_read_ce(ap_var_for_const0);
    start_for_Sobel_1zec_U->if_write_ce(ap_var_for_const0);
    start_for_Sobel_1zec_U->if_din(start_for_Sobel_1_U0_din);
    start_for_Sobel_1zec_U->if_full_n(start_for_Sobel_1_U0_full_n);
    start_for_Sobel_1zec_U->if_write(Duplicate_U0_start_write);
    start_for_Sobel_1zec_U->if_dout(start_for_Sobel_1_U0_dout);
    start_for_Sobel_1zec_U->if_empty_n(start_for_Sobel_1_U0_empty_n);
    start_for_Sobel_1zec_U->if_read(Sobel_1_U0_ap_ready);
    start_for_CvtColoAem_U = new start_for_CvtColoAem("start_for_CvtColoAem_U");
    start_for_CvtColoAem_U->clk(ap_clk);
    start_for_CvtColoAem_U->reset(ap_rst_n_inv);
    start_for_CvtColoAem_U->if_read_ce(ap_var_for_const0);
    start_for_CvtColoAem_U->if_write_ce(ap_var_for_const0);
    start_for_CvtColoAem_U->if_din(start_for_CvtColor_U0_din);
    start_for_CvtColoAem_U->if_full_n(start_for_CvtColor_U0_full_n);
    start_for_CvtColoAem_U->if_write(AddWeighted_U0_start_write);
    start_for_CvtColoAem_U->if_dout(start_for_CvtColor_U0_dout);
    start_for_CvtColoAem_U->if_empty_n(start_for_CvtColor_U0_empty_n);
    start_for_CvtColoAem_U->if_read(CvtColor_U0_ap_ready);
    start_for_Mat2AXIBew_U = new start_for_Mat2AXIBew("start_for_Mat2AXIBew_U");
    start_for_Mat2AXIBew_U->clk(ap_clk);
    start_for_Mat2AXIBew_U->reset(ap_rst_n_inv);
    start_for_Mat2AXIBew_U->if_read_ce(ap_var_for_const0);
    start_for_Mat2AXIBew_U->if_write_ce(ap_var_for_const0);
    start_for_Mat2AXIBew_U->if_din(start_for_Mat2AXIvideo_U0_din);
    start_for_Mat2AXIBew_U->if_full_n(start_for_Mat2AXIvideo_U0_full_n);
    start_for_Mat2AXIBew_U->if_write(CvtColor_U0_start_write);
    start_for_Mat2AXIBew_U->if_dout(start_for_Mat2AXIvideo_U0_dout);
    start_for_Mat2AXIBew_U->if_empty_n(start_for_Mat2AXIvideo_U0_empty_n);
    start_for_Mat2AXIBew_U->if_read(Mat2AXIvideo_U0_ap_ready);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_AXIvideo2Mat_U0_ap_continue);

    SC_METHOD(thread_AXIvideo2Mat_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_AXIvideo2Mat_U0_ap_ready );

    SC_METHOD(thread_AddWeighted_U0_ap_continue);

    SC_METHOD(thread_AddWeighted_U0_ap_start);
    sensitive << ( start_for_AddWeighted_U0_empty_n );

    SC_METHOD(thread_Block_proc_U0_ap_continue);

    SC_METHOD(thread_Block_proc_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_Block_proc_U0_ap_ready );

    SC_METHOD(thread_CvtColor_1_U0_ap_continue);

    SC_METHOD(thread_CvtColor_1_U0_ap_start);
    sensitive << ( start_for_CvtColor_1_U0_empty_n );

    SC_METHOD(thread_CvtColor_U0_ap_continue);

    SC_METHOD(thread_CvtColor_U0_ap_start);
    sensitive << ( start_for_CvtColor_U0_empty_n );

    SC_METHOD(thread_Duplicate_U0_ap_continue);

    SC_METHOD(thread_Duplicate_U0_ap_start);
    sensitive << ( start_for_Duplicate_U0_empty_n );

    SC_METHOD(thread_Duplicate_U0_start_full_n);
    sensitive << ( start_for_Sobel_U0_full_n );
    sensitive << ( start_for_Sobel_1_U0_full_n );

    SC_METHOD(thread_GaussianBlur_U0_ap_continue);

    SC_METHOD(thread_GaussianBlur_U0_ap_start);
    sensitive << ( start_for_GaussianBlur_U0_empty_n );

    SC_METHOD(thread_INPUT_STREAM_TREADY);
    sensitive << ( AXIvideo2Mat_U0_INPUT_STREAM_TREADY );

    SC_METHOD(thread_Mat2AXIvideo_U0_ap_continue);

    SC_METHOD(thread_Mat2AXIvideo_U0_ap_start);
    sensitive << ( start_for_Mat2AXIvideo_U0_empty_n );

    SC_METHOD(thread_Mat2AXIvideo_U0_start_full_n);

    SC_METHOD(thread_Mat2AXIvideo_U0_start_write);

    SC_METHOD(thread_OUTPUT_STREAM_TDATA);
    sensitive << ( Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA );

    SC_METHOD(thread_OUTPUT_STREAM_TDEST);
    sensitive << ( Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST );

    SC_METHOD(thread_OUTPUT_STREAM_TID);
    sensitive << ( Mat2AXIvideo_U0_OUTPUT_STREAM_TID );

    SC_METHOD(thread_OUTPUT_STREAM_TKEEP);
    sensitive << ( Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP );

    SC_METHOD(thread_OUTPUT_STREAM_TLAST);
    sensitive << ( Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST );

    SC_METHOD(thread_OUTPUT_STREAM_TSTRB);
    sensitive << ( Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB );

    SC_METHOD(thread_OUTPUT_STREAM_TUSER);
    sensitive << ( Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER );

    SC_METHOD(thread_OUTPUT_STREAM_TVALID);
    sensitive << ( Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID );

    SC_METHOD(thread_Sobel_1_U0_ap_continue);

    SC_METHOD(thread_Sobel_1_U0_ap_start);
    sensitive << ( start_for_Sobel_1_U0_empty_n );

    SC_METHOD(thread_Sobel_1_U0_start_full_n);

    SC_METHOD(thread_Sobel_1_U0_start_write);

    SC_METHOD(thread_Sobel_U0_ap_continue);

    SC_METHOD(thread_Sobel_U0_ap_start);
    sensitive << ( start_for_Sobel_U0_empty_n );

    SC_METHOD(thread_Sobel_U0_start_full_n);

    SC_METHOD(thread_Sobel_U0_start_write);

    SC_METHOD(thread_ap_done);
    sensitive << ( Mat2AXIvideo_U0_ap_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( Block_proc_U0_ap_idle );
    sensitive << ( AXIvideo2Mat_U0_ap_idle );
    sensitive << ( CvtColor_1_U0_ap_idle );
    sensitive << ( GaussianBlur_U0_ap_idle );
    sensitive << ( Duplicate_U0_ap_idle );
    sensitive << ( Sobel_U0_ap_idle );
    sensitive << ( Sobel_1_U0_ap_idle );
    sensitive << ( AddWeighted_U0_ap_idle );
    sensitive << ( CvtColor_U0_ap_idle );
    sensitive << ( Mat2AXIvideo_U0_ap_idle );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sync_ready );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_AXIvideo2Mat_U0_ap_ready);
    sensitive << ( AXIvideo2Mat_U0_ap_ready );
    sensitive << ( ap_sync_reg_AXIvideo2Mat_U0_ap_ready );

    SC_METHOD(thread_ap_sync_Block_proc_U0_ap_ready);
    sensitive << ( Block_proc_U0_ap_ready );
    sensitive << ( ap_sync_reg_Block_proc_U0_ap_ready );

    SC_METHOD(thread_ap_sync_continue);

    SC_METHOD(thread_ap_sync_done);
    sensitive << ( Mat2AXIvideo_U0_ap_done );

    SC_METHOD(thread_ap_sync_ready);
    sensitive << ( ap_sync_Block_proc_U0_ap_ready );
    sensitive << ( ap_sync_AXIvideo2Mat_U0_ap_ready );

    SC_METHOD(thread_start_for_AddWeighted_U0_din);

    SC_METHOD(thread_start_for_CvtColor_1_U0_din);

    SC_METHOD(thread_start_for_CvtColor_U0_din);

    SC_METHOD(thread_start_for_Duplicate_U0_din);

    SC_METHOD(thread_start_for_GaussianBlur_U0_din);

    SC_METHOD(thread_start_for_Mat2AXIvideo_U0_din);

    SC_METHOD(thread_start_for_Sobel_1_U0_din);

    SC_METHOD(thread_start_for_Sobel_U0_din);

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    ap_sync_reg_Block_proc_U0_ap_ready = SC_LOGIC_0;
    Block_proc_U0_ap_ready_count = "00";
    ap_sync_reg_AXIvideo2Mat_U0_ap_ready = SC_LOGIC_0;
    AXIvideo2Mat_U0_ap_ready_count = "00";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "sobel_accel_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_AWVALID, "(port)s_axi_CONTROL_BUS_AWVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_AWREADY, "(port)s_axi_CONTROL_BUS_AWREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_AWADDR, "(port)s_axi_CONTROL_BUS_AWADDR");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WVALID, "(port)s_axi_CONTROL_BUS_WVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WREADY, "(port)s_axi_CONTROL_BUS_WREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WDATA, "(port)s_axi_CONTROL_BUS_WDATA");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_WSTRB, "(port)s_axi_CONTROL_BUS_WSTRB");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_ARVALID, "(port)s_axi_CONTROL_BUS_ARVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_ARREADY, "(port)s_axi_CONTROL_BUS_ARREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_ARADDR, "(port)s_axi_CONTROL_BUS_ARADDR");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RVALID, "(port)s_axi_CONTROL_BUS_RVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RREADY, "(port)s_axi_CONTROL_BUS_RREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RDATA, "(port)s_axi_CONTROL_BUS_RDATA");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_RRESP, "(port)s_axi_CONTROL_BUS_RRESP");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_BVALID, "(port)s_axi_CONTROL_BUS_BVALID");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_BREADY, "(port)s_axi_CONTROL_BUS_BREADY");
    sc_trace(mVcdFile, s_axi_CONTROL_BUS_BRESP, "(port)s_axi_CONTROL_BUS_BRESP");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, interrupt, "(port)interrupt");
    sc_trace(mVcdFile, INPUT_STREAM_TDATA, "(port)INPUT_STREAM_TDATA");
    sc_trace(mVcdFile, INPUT_STREAM_TKEEP, "(port)INPUT_STREAM_TKEEP");
    sc_trace(mVcdFile, INPUT_STREAM_TSTRB, "(port)INPUT_STREAM_TSTRB");
    sc_trace(mVcdFile, INPUT_STREAM_TUSER, "(port)INPUT_STREAM_TUSER");
    sc_trace(mVcdFile, INPUT_STREAM_TLAST, "(port)INPUT_STREAM_TLAST");
    sc_trace(mVcdFile, INPUT_STREAM_TID, "(port)INPUT_STREAM_TID");
    sc_trace(mVcdFile, INPUT_STREAM_TDEST, "(port)INPUT_STREAM_TDEST");
    sc_trace(mVcdFile, OUTPUT_STREAM_TDATA, "(port)OUTPUT_STREAM_TDATA");
    sc_trace(mVcdFile, OUTPUT_STREAM_TKEEP, "(port)OUTPUT_STREAM_TKEEP");
    sc_trace(mVcdFile, OUTPUT_STREAM_TSTRB, "(port)OUTPUT_STREAM_TSTRB");
    sc_trace(mVcdFile, OUTPUT_STREAM_TUSER, "(port)OUTPUT_STREAM_TUSER");
    sc_trace(mVcdFile, OUTPUT_STREAM_TLAST, "(port)OUTPUT_STREAM_TLAST");
    sc_trace(mVcdFile, OUTPUT_STREAM_TID, "(port)OUTPUT_STREAM_TID");
    sc_trace(mVcdFile, OUTPUT_STREAM_TDEST, "(port)OUTPUT_STREAM_TDEST");
    sc_trace(mVcdFile, INPUT_STREAM_TVALID, "(port)INPUT_STREAM_TVALID");
    sc_trace(mVcdFile, INPUT_STREAM_TREADY, "(port)INPUT_STREAM_TREADY");
    sc_trace(mVcdFile, OUTPUT_STREAM_TVALID, "(port)OUTPUT_STREAM_TVALID");
    sc_trace(mVcdFile, OUTPUT_STREAM_TREADY, "(port)OUTPUT_STREAM_TREADY");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, ap_start, "ap_start");
    sc_trace(mVcdFile, ap_ready, "ap_ready");
    sc_trace(mVcdFile, ap_done, "ap_done");
    sc_trace(mVcdFile, ap_idle, "ap_idle");
    sc_trace(mVcdFile, Block_proc_U0_ap_start, "Block_proc_U0_ap_start");
    sc_trace(mVcdFile, Block_proc_U0_ap_done, "Block_proc_U0_ap_done");
    sc_trace(mVcdFile, Block_proc_U0_ap_continue, "Block_proc_U0_ap_continue");
    sc_trace(mVcdFile, Block_proc_U0_ap_idle, "Block_proc_U0_ap_idle");
    sc_trace(mVcdFile, Block_proc_U0_ap_ready, "Block_proc_U0_ap_ready");
    sc_trace(mVcdFile, Block_proc_U0_start_out, "Block_proc_U0_start_out");
    sc_trace(mVcdFile, Block_proc_U0_start_write, "Block_proc_U0_start_write");
    sc_trace(mVcdFile, Block_proc_U0_src_rows_V_out_din, "Block_proc_U0_src_rows_V_out_din");
    sc_trace(mVcdFile, Block_proc_U0_src_rows_V_out_write, "Block_proc_U0_src_rows_V_out_write");
    sc_trace(mVcdFile, Block_proc_U0_src_cols_V_out_din, "Block_proc_U0_src_cols_V_out_din");
    sc_trace(mVcdFile, Block_proc_U0_src_cols_V_out_write, "Block_proc_U0_src_cols_V_out_write");
    sc_trace(mVcdFile, Block_proc_U0_sobel_g_rows_V_out_din, "Block_proc_U0_sobel_g_rows_V_out_din");
    sc_trace(mVcdFile, Block_proc_U0_sobel_g_rows_V_out_write, "Block_proc_U0_sobel_g_rows_V_out_write");
    sc_trace(mVcdFile, Block_proc_U0_sobel_g_cols_V_out_din, "Block_proc_U0_sobel_g_cols_V_out_din");
    sc_trace(mVcdFile, Block_proc_U0_sobel_g_cols_V_out_write, "Block_proc_U0_sobel_g_cols_V_out_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_start, "AXIvideo2Mat_U0_ap_start");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_done, "AXIvideo2Mat_U0_ap_done");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_continue, "AXIvideo2Mat_U0_ap_continue");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_idle, "AXIvideo2Mat_U0_ap_idle");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_ready, "AXIvideo2Mat_U0_ap_ready");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_start_out, "AXIvideo2Mat_U0_start_out");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_start_write, "AXIvideo2Mat_U0_start_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_INPUT_STREAM_TREADY, "AXIvideo2Mat_U0_INPUT_STREAM_TREADY");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_rows_V_read, "AXIvideo2Mat_U0_img_rows_V_read");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_cols_V_read, "AXIvideo2Mat_U0_img_cols_V_read");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_0_V_din, "AXIvideo2Mat_U0_img_data_stream_0_V_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_0_V_write, "AXIvideo2Mat_U0_img_data_stream_0_V_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_1_V_din, "AXIvideo2Mat_U0_img_data_stream_1_V_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_1_V_write, "AXIvideo2Mat_U0_img_data_stream_1_V_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_2_V_din, "AXIvideo2Mat_U0_img_data_stream_2_V_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_2_V_write, "AXIvideo2Mat_U0_img_data_stream_2_V_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_rows_V_out_din, "AXIvideo2Mat_U0_img_rows_V_out_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_rows_V_out_write, "AXIvideo2Mat_U0_img_rows_V_out_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_cols_V_out_din, "AXIvideo2Mat_U0_img_cols_V_out_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_cols_V_out_write, "AXIvideo2Mat_U0_img_cols_V_out_write");
    sc_trace(mVcdFile, CvtColor_1_U0_ap_start, "CvtColor_1_U0_ap_start");
    sc_trace(mVcdFile, CvtColor_1_U0_ap_done, "CvtColor_1_U0_ap_done");
    sc_trace(mVcdFile, CvtColor_1_U0_ap_continue, "CvtColor_1_U0_ap_continue");
    sc_trace(mVcdFile, CvtColor_1_U0_ap_idle, "CvtColor_1_U0_ap_idle");
    sc_trace(mVcdFile, CvtColor_1_U0_ap_ready, "CvtColor_1_U0_ap_ready");
    sc_trace(mVcdFile, CvtColor_1_U0_start_out, "CvtColor_1_U0_start_out");
    sc_trace(mVcdFile, CvtColor_1_U0_start_write, "CvtColor_1_U0_start_write");
    sc_trace(mVcdFile, CvtColor_1_U0_p_src_rows_V_read, "CvtColor_1_U0_p_src_rows_V_read");
    sc_trace(mVcdFile, CvtColor_1_U0_p_src_cols_V_read, "CvtColor_1_U0_p_src_cols_V_read");
    sc_trace(mVcdFile, CvtColor_1_U0_p_src_data_stream_0_V_read, "CvtColor_1_U0_p_src_data_stream_0_V_read");
    sc_trace(mVcdFile, CvtColor_1_U0_p_src_data_stream_1_V_read, "CvtColor_1_U0_p_src_data_stream_1_V_read");
    sc_trace(mVcdFile, CvtColor_1_U0_p_src_data_stream_2_V_read, "CvtColor_1_U0_p_src_data_stream_2_V_read");
    sc_trace(mVcdFile, CvtColor_1_U0_p_dst_data_stream_V_din, "CvtColor_1_U0_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, CvtColor_1_U0_p_dst_data_stream_V_write, "CvtColor_1_U0_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, GaussianBlur_U0_ap_start, "GaussianBlur_U0_ap_start");
    sc_trace(mVcdFile, GaussianBlur_U0_ap_done, "GaussianBlur_U0_ap_done");
    sc_trace(mVcdFile, GaussianBlur_U0_ap_continue, "GaussianBlur_U0_ap_continue");
    sc_trace(mVcdFile, GaussianBlur_U0_ap_idle, "GaussianBlur_U0_ap_idle");
    sc_trace(mVcdFile, GaussianBlur_U0_ap_ready, "GaussianBlur_U0_ap_ready");
    sc_trace(mVcdFile, GaussianBlur_U0_start_out, "GaussianBlur_U0_start_out");
    sc_trace(mVcdFile, GaussianBlur_U0_start_write, "GaussianBlur_U0_start_write");
    sc_trace(mVcdFile, GaussianBlur_U0_p_src_data_stream_V_read, "GaussianBlur_U0_p_src_data_stream_V_read");
    sc_trace(mVcdFile, GaussianBlur_U0_p_dst_data_stream_V_din, "GaussianBlur_U0_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, GaussianBlur_U0_p_dst_data_stream_V_write, "GaussianBlur_U0_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, Duplicate_U0_ap_start, "Duplicate_U0_ap_start");
    sc_trace(mVcdFile, Duplicate_U0_start_full_n, "Duplicate_U0_start_full_n");
    sc_trace(mVcdFile, Duplicate_U0_ap_done, "Duplicate_U0_ap_done");
    sc_trace(mVcdFile, Duplicate_U0_ap_continue, "Duplicate_U0_ap_continue");
    sc_trace(mVcdFile, Duplicate_U0_ap_idle, "Duplicate_U0_ap_idle");
    sc_trace(mVcdFile, Duplicate_U0_ap_ready, "Duplicate_U0_ap_ready");
    sc_trace(mVcdFile, Duplicate_U0_start_out, "Duplicate_U0_start_out");
    sc_trace(mVcdFile, Duplicate_U0_start_write, "Duplicate_U0_start_write");
    sc_trace(mVcdFile, Duplicate_U0_src_data_stream_V_read, "Duplicate_U0_src_data_stream_V_read");
    sc_trace(mVcdFile, Duplicate_U0_dst1_data_stream_V_din, "Duplicate_U0_dst1_data_stream_V_din");
    sc_trace(mVcdFile, Duplicate_U0_dst1_data_stream_V_write, "Duplicate_U0_dst1_data_stream_V_write");
    sc_trace(mVcdFile, Duplicate_U0_dst2_data_stream_V_din, "Duplicate_U0_dst2_data_stream_V_din");
    sc_trace(mVcdFile, Duplicate_U0_dst2_data_stream_V_write, "Duplicate_U0_dst2_data_stream_V_write");
    sc_trace(mVcdFile, Sobel_U0_ap_start, "Sobel_U0_ap_start");
    sc_trace(mVcdFile, Sobel_U0_ap_done, "Sobel_U0_ap_done");
    sc_trace(mVcdFile, Sobel_U0_ap_continue, "Sobel_U0_ap_continue");
    sc_trace(mVcdFile, Sobel_U0_ap_idle, "Sobel_U0_ap_idle");
    sc_trace(mVcdFile, Sobel_U0_ap_ready, "Sobel_U0_ap_ready");
    sc_trace(mVcdFile, Sobel_U0_p_src_data_stream_V_read, "Sobel_U0_p_src_data_stream_V_read");
    sc_trace(mVcdFile, Sobel_U0_p_dst_data_stream_V_din, "Sobel_U0_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, Sobel_U0_p_dst_data_stream_V_write, "Sobel_U0_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, Sobel_1_U0_ap_start, "Sobel_1_U0_ap_start");
    sc_trace(mVcdFile, Sobel_1_U0_ap_done, "Sobel_1_U0_ap_done");
    sc_trace(mVcdFile, Sobel_1_U0_ap_continue, "Sobel_1_U0_ap_continue");
    sc_trace(mVcdFile, Sobel_1_U0_ap_idle, "Sobel_1_U0_ap_idle");
    sc_trace(mVcdFile, Sobel_1_U0_ap_ready, "Sobel_1_U0_ap_ready");
    sc_trace(mVcdFile, Sobel_1_U0_p_src_data_stream_V_read, "Sobel_1_U0_p_src_data_stream_V_read");
    sc_trace(mVcdFile, Sobel_1_U0_p_dst_data_stream_V_din, "Sobel_1_U0_p_dst_data_stream_V_din");
    sc_trace(mVcdFile, Sobel_1_U0_p_dst_data_stream_V_write, "Sobel_1_U0_p_dst_data_stream_V_write");
    sc_trace(mVcdFile, AddWeighted_U0_ap_start, "AddWeighted_U0_ap_start");
    sc_trace(mVcdFile, AddWeighted_U0_ap_done, "AddWeighted_U0_ap_done");
    sc_trace(mVcdFile, AddWeighted_U0_ap_continue, "AddWeighted_U0_ap_continue");
    sc_trace(mVcdFile, AddWeighted_U0_ap_idle, "AddWeighted_U0_ap_idle");
    sc_trace(mVcdFile, AddWeighted_U0_ap_ready, "AddWeighted_U0_ap_ready");
    sc_trace(mVcdFile, AddWeighted_U0_start_out, "AddWeighted_U0_start_out");
    sc_trace(mVcdFile, AddWeighted_U0_start_write, "AddWeighted_U0_start_write");
    sc_trace(mVcdFile, AddWeighted_U0_src1_data_stream_V_read, "AddWeighted_U0_src1_data_stream_V_read");
    sc_trace(mVcdFile, AddWeighted_U0_src2_data_stream_V_read, "AddWeighted_U0_src2_data_stream_V_read");
    sc_trace(mVcdFile, AddWeighted_U0_dst_rows_V_read, "AddWeighted_U0_dst_rows_V_read");
    sc_trace(mVcdFile, AddWeighted_U0_dst_cols_V_read, "AddWeighted_U0_dst_cols_V_read");
    sc_trace(mVcdFile, AddWeighted_U0_dst_data_stream_V_din, "AddWeighted_U0_dst_data_stream_V_din");
    sc_trace(mVcdFile, AddWeighted_U0_dst_data_stream_V_write, "AddWeighted_U0_dst_data_stream_V_write");
    sc_trace(mVcdFile, AddWeighted_U0_dst_rows_V_out_din, "AddWeighted_U0_dst_rows_V_out_din");
    sc_trace(mVcdFile, AddWeighted_U0_dst_rows_V_out_write, "AddWeighted_U0_dst_rows_V_out_write");
    sc_trace(mVcdFile, AddWeighted_U0_dst_cols_V_out_din, "AddWeighted_U0_dst_cols_V_out_din");
    sc_trace(mVcdFile, AddWeighted_U0_dst_cols_V_out_write, "AddWeighted_U0_dst_cols_V_out_write");
    sc_trace(mVcdFile, CvtColor_U0_ap_start, "CvtColor_U0_ap_start");
    sc_trace(mVcdFile, CvtColor_U0_ap_done, "CvtColor_U0_ap_done");
    sc_trace(mVcdFile, CvtColor_U0_ap_continue, "CvtColor_U0_ap_continue");
    sc_trace(mVcdFile, CvtColor_U0_ap_idle, "CvtColor_U0_ap_idle");
    sc_trace(mVcdFile, CvtColor_U0_ap_ready, "CvtColor_U0_ap_ready");
    sc_trace(mVcdFile, CvtColor_U0_start_out, "CvtColor_U0_start_out");
    sc_trace(mVcdFile, CvtColor_U0_start_write, "CvtColor_U0_start_write");
    sc_trace(mVcdFile, CvtColor_U0_p_src_rows_V_read, "CvtColor_U0_p_src_rows_V_read");
    sc_trace(mVcdFile, CvtColor_U0_p_src_cols_V_read, "CvtColor_U0_p_src_cols_V_read");
    sc_trace(mVcdFile, CvtColor_U0_p_src_data_stream_V_read, "CvtColor_U0_p_src_data_stream_V_read");
    sc_trace(mVcdFile, CvtColor_U0_p_dst_data_stream_0_V_din, "CvtColor_U0_p_dst_data_stream_0_V_din");
    sc_trace(mVcdFile, CvtColor_U0_p_dst_data_stream_0_V_write, "CvtColor_U0_p_dst_data_stream_0_V_write");
    sc_trace(mVcdFile, CvtColor_U0_p_dst_data_stream_1_V_din, "CvtColor_U0_p_dst_data_stream_1_V_din");
    sc_trace(mVcdFile, CvtColor_U0_p_dst_data_stream_1_V_write, "CvtColor_U0_p_dst_data_stream_1_V_write");
    sc_trace(mVcdFile, CvtColor_U0_p_dst_data_stream_2_V_din, "CvtColor_U0_p_dst_data_stream_2_V_din");
    sc_trace(mVcdFile, CvtColor_U0_p_dst_data_stream_2_V_write, "CvtColor_U0_p_dst_data_stream_2_V_write");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_start, "Mat2AXIvideo_U0_ap_start");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_done, "Mat2AXIvideo_U0_ap_done");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_continue, "Mat2AXIvideo_U0_ap_continue");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_idle, "Mat2AXIvideo_U0_ap_idle");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_ready, "Mat2AXIvideo_U0_ap_ready");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_data_stream_0_V_read, "Mat2AXIvideo_U0_img_data_stream_0_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_data_stream_1_V_read, "Mat2AXIvideo_U0_img_data_stream_1_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_data_stream_2_V_read, "Mat2AXIvideo_U0_img_data_stream_2_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA, "Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID, "Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP, "Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB, "Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER, "Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST, "Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_OUTPUT_STREAM_TID, "Mat2AXIvideo_U0_OUTPUT_STREAM_TID");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST, "Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, src_rows_V_c_full_n, "src_rows_V_c_full_n");
    sc_trace(mVcdFile, src_rows_V_c_dout, "src_rows_V_c_dout");
    sc_trace(mVcdFile, src_rows_V_c_empty_n, "src_rows_V_c_empty_n");
    sc_trace(mVcdFile, src_cols_V_c_full_n, "src_cols_V_c_full_n");
    sc_trace(mVcdFile, src_cols_V_c_dout, "src_cols_V_c_dout");
    sc_trace(mVcdFile, src_cols_V_c_empty_n, "src_cols_V_c_empty_n");
    sc_trace(mVcdFile, sobel_g_rows_V_c_full_n, "sobel_g_rows_V_c_full_n");
    sc_trace(mVcdFile, sobel_g_rows_V_c_dout, "sobel_g_rows_V_c_dout");
    sc_trace(mVcdFile, sobel_g_rows_V_c_empty_n, "sobel_g_rows_V_c_empty_n");
    sc_trace(mVcdFile, sobel_g_cols_V_c_full_n, "sobel_g_cols_V_c_full_n");
    sc_trace(mVcdFile, sobel_g_cols_V_c_dout, "sobel_g_cols_V_c_dout");
    sc_trace(mVcdFile, sobel_g_cols_V_c_empty_n, "sobel_g_cols_V_c_empty_n");
    sc_trace(mVcdFile, src_data_stream_0_V_full_n, "src_data_stream_0_V_full_n");
    sc_trace(mVcdFile, src_data_stream_0_V_dout, "src_data_stream_0_V_dout");
    sc_trace(mVcdFile, src_data_stream_0_V_empty_n, "src_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, src_data_stream_1_V_full_n, "src_data_stream_1_V_full_n");
    sc_trace(mVcdFile, src_data_stream_1_V_dout, "src_data_stream_1_V_dout");
    sc_trace(mVcdFile, src_data_stream_1_V_empty_n, "src_data_stream_1_V_empty_n");
    sc_trace(mVcdFile, src_data_stream_2_V_full_n, "src_data_stream_2_V_full_n");
    sc_trace(mVcdFile, src_data_stream_2_V_dout, "src_data_stream_2_V_dout");
    sc_trace(mVcdFile, src_data_stream_2_V_empty_n, "src_data_stream_2_V_empty_n");
    sc_trace(mVcdFile, src_rows_V_c22_full_n, "src_rows_V_c22_full_n");
    sc_trace(mVcdFile, src_rows_V_c22_dout, "src_rows_V_c22_dout");
    sc_trace(mVcdFile, src_rows_V_c22_empty_n, "src_rows_V_c22_empty_n");
    sc_trace(mVcdFile, src_cols_V_c23_full_n, "src_cols_V_c23_full_n");
    sc_trace(mVcdFile, src_cols_V_c23_dout, "src_cols_V_c23_dout");
    sc_trace(mVcdFile, src_cols_V_c23_empty_n, "src_cols_V_c23_empty_n");
    sc_trace(mVcdFile, gray_data_stream_0_s_full_n, "gray_data_stream_0_s_full_n");
    sc_trace(mVcdFile, gray_data_stream_0_s_dout, "gray_data_stream_0_s_dout");
    sc_trace(mVcdFile, gray_data_stream_0_s_empty_n, "gray_data_stream_0_s_empty_n");
    sc_trace(mVcdFile, blurred_data_stream_s_full_n, "blurred_data_stream_s_full_n");
    sc_trace(mVcdFile, blurred_data_stream_s_dout, "blurred_data_stream_s_dout");
    sc_trace(mVcdFile, blurred_data_stream_s_empty_n, "blurred_data_stream_s_empty_n");
    sc_trace(mVcdFile, gray1_data_stream_0_full_n, "gray1_data_stream_0_full_n");
    sc_trace(mVcdFile, gray1_data_stream_0_dout, "gray1_data_stream_0_dout");
    sc_trace(mVcdFile, gray1_data_stream_0_empty_n, "gray1_data_stream_0_empty_n");
    sc_trace(mVcdFile, gray2_data_stream_0_full_n, "gray2_data_stream_0_full_n");
    sc_trace(mVcdFile, gray2_data_stream_0_dout, "gray2_data_stream_0_dout");
    sc_trace(mVcdFile, gray2_data_stream_0_empty_n, "gray2_data_stream_0_empty_n");
    sc_trace(mVcdFile, sobel_x_data_stream_s_full_n, "sobel_x_data_stream_s_full_n");
    sc_trace(mVcdFile, sobel_x_data_stream_s_dout, "sobel_x_data_stream_s_dout");
    sc_trace(mVcdFile, sobel_x_data_stream_s_empty_n, "sobel_x_data_stream_s_empty_n");
    sc_trace(mVcdFile, sobel_y_data_stream_s_full_n, "sobel_y_data_stream_s_full_n");
    sc_trace(mVcdFile, sobel_y_data_stream_s_dout, "sobel_y_data_stream_s_dout");
    sc_trace(mVcdFile, sobel_y_data_stream_s_empty_n, "sobel_y_data_stream_s_empty_n");
    sc_trace(mVcdFile, sobel_g_data_stream_s_full_n, "sobel_g_data_stream_s_full_n");
    sc_trace(mVcdFile, sobel_g_data_stream_s_dout, "sobel_g_data_stream_s_dout");
    sc_trace(mVcdFile, sobel_g_data_stream_s_empty_n, "sobel_g_data_stream_s_empty_n");
    sc_trace(mVcdFile, sobel_g_rows_V_c24_full_n, "sobel_g_rows_V_c24_full_n");
    sc_trace(mVcdFile, sobel_g_rows_V_c24_dout, "sobel_g_rows_V_c24_dout");
    sc_trace(mVcdFile, sobel_g_rows_V_c24_empty_n, "sobel_g_rows_V_c24_empty_n");
    sc_trace(mVcdFile, sobel_g_cols_V_c25_full_n, "sobel_g_cols_V_c25_full_n");
    sc_trace(mVcdFile, sobel_g_cols_V_c25_dout, "sobel_g_cols_V_c25_dout");
    sc_trace(mVcdFile, sobel_g_cols_V_c25_empty_n, "sobel_g_cols_V_c25_empty_n");
    sc_trace(mVcdFile, dst_data_stream_0_V_full_n, "dst_data_stream_0_V_full_n");
    sc_trace(mVcdFile, dst_data_stream_0_V_dout, "dst_data_stream_0_V_dout");
    sc_trace(mVcdFile, dst_data_stream_0_V_empty_n, "dst_data_stream_0_V_empty_n");
    sc_trace(mVcdFile, dst_data_stream_1_V_full_n, "dst_data_stream_1_V_full_n");
    sc_trace(mVcdFile, dst_data_stream_1_V_dout, "dst_data_stream_1_V_dout");
    sc_trace(mVcdFile, dst_data_stream_1_V_empty_n, "dst_data_stream_1_V_empty_n");
    sc_trace(mVcdFile, dst_data_stream_2_V_full_n, "dst_data_stream_2_V_full_n");
    sc_trace(mVcdFile, dst_data_stream_2_V_dout, "dst_data_stream_2_V_dout");
    sc_trace(mVcdFile, dst_data_stream_2_V_empty_n, "dst_data_stream_2_V_empty_n");
    sc_trace(mVcdFile, ap_sync_done, "ap_sync_done");
    sc_trace(mVcdFile, ap_sync_ready, "ap_sync_ready");
    sc_trace(mVcdFile, ap_sync_reg_Block_proc_U0_ap_ready, "ap_sync_reg_Block_proc_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_Block_proc_U0_ap_ready, "ap_sync_Block_proc_U0_ap_ready");
    sc_trace(mVcdFile, Block_proc_U0_ap_ready_count, "Block_proc_U0_ap_ready_count");
    sc_trace(mVcdFile, ap_sync_reg_AXIvideo2Mat_U0_ap_ready, "ap_sync_reg_AXIvideo2Mat_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_AXIvideo2Mat_U0_ap_ready, "ap_sync_AXIvideo2Mat_U0_ap_ready");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_ready_count, "AXIvideo2Mat_U0_ap_ready_count");
    sc_trace(mVcdFile, start_for_AddWeighted_U0_din, "start_for_AddWeighted_U0_din");
    sc_trace(mVcdFile, start_for_AddWeighted_U0_full_n, "start_for_AddWeighted_U0_full_n");
    sc_trace(mVcdFile, start_for_AddWeighted_U0_dout, "start_for_AddWeighted_U0_dout");
    sc_trace(mVcdFile, start_for_AddWeighted_U0_empty_n, "start_for_AddWeighted_U0_empty_n");
    sc_trace(mVcdFile, start_for_CvtColor_1_U0_din, "start_for_CvtColor_1_U0_din");
    sc_trace(mVcdFile, start_for_CvtColor_1_U0_full_n, "start_for_CvtColor_1_U0_full_n");
    sc_trace(mVcdFile, start_for_CvtColor_1_U0_dout, "start_for_CvtColor_1_U0_dout");
    sc_trace(mVcdFile, start_for_CvtColor_1_U0_empty_n, "start_for_CvtColor_1_U0_empty_n");
    sc_trace(mVcdFile, start_for_GaussianBlur_U0_din, "start_for_GaussianBlur_U0_din");
    sc_trace(mVcdFile, start_for_GaussianBlur_U0_full_n, "start_for_GaussianBlur_U0_full_n");
    sc_trace(mVcdFile, start_for_GaussianBlur_U0_dout, "start_for_GaussianBlur_U0_dout");
    sc_trace(mVcdFile, start_for_GaussianBlur_U0_empty_n, "start_for_GaussianBlur_U0_empty_n");
    sc_trace(mVcdFile, start_for_Duplicate_U0_din, "start_for_Duplicate_U0_din");
    sc_trace(mVcdFile, start_for_Duplicate_U0_full_n, "start_for_Duplicate_U0_full_n");
    sc_trace(mVcdFile, start_for_Duplicate_U0_dout, "start_for_Duplicate_U0_dout");
    sc_trace(mVcdFile, start_for_Duplicate_U0_empty_n, "start_for_Duplicate_U0_empty_n");
    sc_trace(mVcdFile, start_for_Sobel_U0_din, "start_for_Sobel_U0_din");
    sc_trace(mVcdFile, start_for_Sobel_U0_full_n, "start_for_Sobel_U0_full_n");
    sc_trace(mVcdFile, start_for_Sobel_U0_dout, "start_for_Sobel_U0_dout");
    sc_trace(mVcdFile, start_for_Sobel_U0_empty_n, "start_for_Sobel_U0_empty_n");
    sc_trace(mVcdFile, start_for_Sobel_1_U0_din, "start_for_Sobel_1_U0_din");
    sc_trace(mVcdFile, start_for_Sobel_1_U0_full_n, "start_for_Sobel_1_U0_full_n");
    sc_trace(mVcdFile, start_for_Sobel_1_U0_dout, "start_for_Sobel_1_U0_dout");
    sc_trace(mVcdFile, start_for_Sobel_1_U0_empty_n, "start_for_Sobel_1_U0_empty_n");
    sc_trace(mVcdFile, Sobel_U0_start_full_n, "Sobel_U0_start_full_n");
    sc_trace(mVcdFile, Sobel_U0_start_write, "Sobel_U0_start_write");
    sc_trace(mVcdFile, Sobel_1_U0_start_full_n, "Sobel_1_U0_start_full_n");
    sc_trace(mVcdFile, Sobel_1_U0_start_write, "Sobel_1_U0_start_write");
    sc_trace(mVcdFile, start_for_CvtColor_U0_din, "start_for_CvtColor_U0_din");
    sc_trace(mVcdFile, start_for_CvtColor_U0_full_n, "start_for_CvtColor_U0_full_n");
    sc_trace(mVcdFile, start_for_CvtColor_U0_dout, "start_for_CvtColor_U0_dout");
    sc_trace(mVcdFile, start_for_CvtColor_U0_empty_n, "start_for_CvtColor_U0_empty_n");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_din, "start_for_Mat2AXIvideo_U0_din");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_full_n, "start_for_Mat2AXIvideo_U0_full_n");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_dout, "start_for_Mat2AXIvideo_U0_dout");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_empty_n, "start_for_Mat2AXIvideo_U0_empty_n");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_start_full_n, "Mat2AXIvideo_U0_start_full_n");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_start_write, "Mat2AXIvideo_U0_start_write");
#endif

    }
    mHdltvinHandle.open("sobel_accel.hdltvin.dat");
    mHdltvoutHandle.open("sobel_accel.hdltvout.dat");
}

sobel_accel::~sobel_accel() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete sobel_accel_CONTROL_BUS_s_axi_U;
    delete Block_proc_U0;
    delete AXIvideo2Mat_U0;
    delete CvtColor_1_U0;
    delete GaussianBlur_U0;
    delete Duplicate_U0;
    delete Sobel_U0;
    delete Sobel_1_U0;
    delete AddWeighted_U0;
    delete CvtColor_U0;
    delete Mat2AXIvideo_U0;
    delete src_rows_V_c_U;
    delete src_cols_V_c_U;
    delete sobel_g_rows_V_c_U;
    delete sobel_g_cols_V_c_U;
    delete src_data_stream_0_V_U;
    delete src_data_stream_1_V_U;
    delete src_data_stream_2_V_U;
    delete src_rows_V_c22_U;
    delete src_cols_V_c23_U;
    delete gray_data_stream_0_s_U;
    delete blurred_data_stream_s_U;
    delete gray1_data_stream_0_U;
    delete gray2_data_stream_0_U;
    delete sobel_x_data_stream_s_U;
    delete sobel_y_data_stream_s_U;
    delete sobel_g_data_stream_s_U;
    delete sobel_g_rows_V_c24_U;
    delete sobel_g_cols_V_c25_U;
    delete dst_data_stream_0_V_U;
    delete dst_data_stream_1_V_U;
    delete dst_data_stream_2_V_U;
    delete start_for_AddWeigvdy_U;
    delete start_for_CvtColowdI_U;
    delete start_for_GaussiaxdS_U;
    delete start_for_Duplicayd2_U;
    delete start_for_Sobel_U0_U;
    delete start_for_Sobel_1zec_U;
    delete start_for_CvtColoAem_U;
    delete start_for_Mat2AXIBew_U;
}

void sobel_accel::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void sobel_accel::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()) && 
         esl_seteq<1,1,1>(AXIvideo2Mat_U0_ap_ready.read(), ap_const_logic_0))) {
        AXIvideo2Mat_U0_ap_ready_count = (!AXIvideo2Mat_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(AXIvideo2Mat_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(ap_sync_ready.read(), ap_const_logic_0) && 
                esl_seteq<1,1,1>(ap_const_logic_1, AXIvideo2Mat_U0_ap_ready.read()))) {
        AXIvideo2Mat_U0_ap_ready_count = (!AXIvideo2Mat_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(AXIvideo2Mat_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ((esl_seteq<1,1,1>(Block_proc_U0_ap_ready.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()))) {
        Block_proc_U0_ap_ready_count = (!Block_proc_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Block_proc_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, Block_proc_U0_ap_ready.read()) && 
                esl_seteq<1,1,1>(ap_sync_ready.read(), ap_const_logic_0))) {
        Block_proc_U0_ap_ready_count = (!Block_proc_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Block_proc_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_AXIvideo2Mat_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_AXIvideo2Mat_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_AXIvideo2Mat_U0_ap_ready = ap_sync_AXIvideo2Mat_U0_ap_ready.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_Block_proc_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_Block_proc_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_Block_proc_U0_ap_ready = ap_sync_Block_proc_U0_ap_ready.read();
        }
    }
}

void sobel_accel::thread_AXIvideo2Mat_U0_ap_continue() {
    AXIvideo2Mat_U0_ap_continue = ap_const_logic_1;
}

void sobel_accel::thread_AXIvideo2Mat_U0_ap_start() {
    AXIvideo2Mat_U0_ap_start = (ap_start.read() & (ap_sync_reg_AXIvideo2Mat_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void sobel_accel::thread_AddWeighted_U0_ap_continue() {
    AddWeighted_U0_ap_continue = ap_const_logic_1;
}

void sobel_accel::thread_AddWeighted_U0_ap_start() {
    AddWeighted_U0_ap_start = start_for_AddWeighted_U0_empty_n.read();
}

void sobel_accel::thread_Block_proc_U0_ap_continue() {
    Block_proc_U0_ap_continue = ap_const_logic_1;
}

void sobel_accel::thread_Block_proc_U0_ap_start() {
    Block_proc_U0_ap_start = (ap_start.read() & (ap_sync_reg_Block_proc_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void sobel_accel::thread_CvtColor_1_U0_ap_continue() {
    CvtColor_1_U0_ap_continue = ap_const_logic_1;
}

void sobel_accel::thread_CvtColor_1_U0_ap_start() {
    CvtColor_1_U0_ap_start = start_for_CvtColor_1_U0_empty_n.read();
}

void sobel_accel::thread_CvtColor_U0_ap_continue() {
    CvtColor_U0_ap_continue = ap_const_logic_1;
}

void sobel_accel::thread_CvtColor_U0_ap_start() {
    CvtColor_U0_ap_start = start_for_CvtColor_U0_empty_n.read();
}

void sobel_accel::thread_Duplicate_U0_ap_continue() {
    Duplicate_U0_ap_continue = ap_const_logic_1;
}

void sobel_accel::thread_Duplicate_U0_ap_start() {
    Duplicate_U0_ap_start = start_for_Duplicate_U0_empty_n.read();
}

void sobel_accel::thread_Duplicate_U0_start_full_n() {
    Duplicate_U0_start_full_n = (start_for_Sobel_U0_full_n.read() & start_for_Sobel_1_U0_full_n.read());
}

void sobel_accel::thread_GaussianBlur_U0_ap_continue() {
    GaussianBlur_U0_ap_continue = ap_const_logic_1;
}

void sobel_accel::thread_GaussianBlur_U0_ap_start() {
    GaussianBlur_U0_ap_start = start_for_GaussianBlur_U0_empty_n.read();
}

void sobel_accel::thread_INPUT_STREAM_TREADY() {
    INPUT_STREAM_TREADY = AXIvideo2Mat_U0_INPUT_STREAM_TREADY.read();
}

void sobel_accel::thread_Mat2AXIvideo_U0_ap_continue() {
    Mat2AXIvideo_U0_ap_continue = ap_const_logic_1;
}

void sobel_accel::thread_Mat2AXIvideo_U0_ap_start() {
    Mat2AXIvideo_U0_ap_start = start_for_Mat2AXIvideo_U0_empty_n.read();
}

void sobel_accel::thread_Mat2AXIvideo_U0_start_full_n() {
    Mat2AXIvideo_U0_start_full_n = ap_const_logic_1;
}

void sobel_accel::thread_Mat2AXIvideo_U0_start_write() {
    Mat2AXIvideo_U0_start_write = ap_const_logic_0;
}

void sobel_accel::thread_OUTPUT_STREAM_TDATA() {
    OUTPUT_STREAM_TDATA = Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA.read();
}

void sobel_accel::thread_OUTPUT_STREAM_TDEST() {
    OUTPUT_STREAM_TDEST = Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST.read();
}

void sobel_accel::thread_OUTPUT_STREAM_TID() {
    OUTPUT_STREAM_TID = Mat2AXIvideo_U0_OUTPUT_STREAM_TID.read();
}

void sobel_accel::thread_OUTPUT_STREAM_TKEEP() {
    OUTPUT_STREAM_TKEEP = Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP.read();
}

void sobel_accel::thread_OUTPUT_STREAM_TLAST() {
    OUTPUT_STREAM_TLAST = Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST.read();
}

void sobel_accel::thread_OUTPUT_STREAM_TSTRB() {
    OUTPUT_STREAM_TSTRB = Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB.read();
}

void sobel_accel::thread_OUTPUT_STREAM_TUSER() {
    OUTPUT_STREAM_TUSER = Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER.read();
}

void sobel_accel::thread_OUTPUT_STREAM_TVALID() {
    OUTPUT_STREAM_TVALID = Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID.read();
}

void sobel_accel::thread_Sobel_1_U0_ap_continue() {
    Sobel_1_U0_ap_continue = ap_const_logic_1;
}

void sobel_accel::thread_Sobel_1_U0_ap_start() {
    Sobel_1_U0_ap_start = start_for_Sobel_1_U0_empty_n.read();
}

void sobel_accel::thread_Sobel_1_U0_start_full_n() {
    Sobel_1_U0_start_full_n = ap_const_logic_1;
}

void sobel_accel::thread_Sobel_1_U0_start_write() {
    Sobel_1_U0_start_write = ap_const_logic_0;
}

void sobel_accel::thread_Sobel_U0_ap_continue() {
    Sobel_U0_ap_continue = ap_const_logic_1;
}

void sobel_accel::thread_Sobel_U0_ap_start() {
    Sobel_U0_ap_start = start_for_Sobel_U0_empty_n.read();
}

void sobel_accel::thread_Sobel_U0_start_full_n() {
    Sobel_U0_start_full_n = ap_const_logic_1;
}

void sobel_accel::thread_Sobel_U0_start_write() {
    Sobel_U0_start_write = ap_const_logic_0;
}

void sobel_accel::thread_ap_done() {
    ap_done = Mat2AXIvideo_U0_ap_done.read();
}

void sobel_accel::thread_ap_idle() {
    ap_idle = (Block_proc_U0_ap_idle.read() & AXIvideo2Mat_U0_ap_idle.read() & CvtColor_1_U0_ap_idle.read() & GaussianBlur_U0_ap_idle.read() & Duplicate_U0_ap_idle.read() & Sobel_U0_ap_idle.read() & Sobel_1_U0_ap_idle.read() & AddWeighted_U0_ap_idle.read() & CvtColor_U0_ap_idle.read() & Mat2AXIvideo_U0_ap_idle.read());
}

void sobel_accel::thread_ap_ready() {
    ap_ready = ap_sync_ready.read();
}

void sobel_accel::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void sobel_accel::thread_ap_sync_AXIvideo2Mat_U0_ap_ready() {
    ap_sync_AXIvideo2Mat_U0_ap_ready = (AXIvideo2Mat_U0_ap_ready.read() | ap_sync_reg_AXIvideo2Mat_U0_ap_ready.read());
}

void sobel_accel::thread_ap_sync_Block_proc_U0_ap_ready() {
    ap_sync_Block_proc_U0_ap_ready = (Block_proc_U0_ap_ready.read() | ap_sync_reg_Block_proc_U0_ap_ready.read());
}

void sobel_accel::thread_ap_sync_continue() {
    ap_sync_continue = ap_const_logic_1;
}

void sobel_accel::thread_ap_sync_done() {
    ap_sync_done = Mat2AXIvideo_U0_ap_done.read();
}

void sobel_accel::thread_ap_sync_ready() {
    ap_sync_ready = (ap_sync_Block_proc_U0_ap_ready.read() & ap_sync_AXIvideo2Mat_U0_ap_ready.read());
}

void sobel_accel::thread_start_for_AddWeighted_U0_din() {
    start_for_AddWeighted_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void sobel_accel::thread_start_for_CvtColor_1_U0_din() {
    start_for_CvtColor_1_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void sobel_accel::thread_start_for_CvtColor_U0_din() {
    start_for_CvtColor_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void sobel_accel::thread_start_for_Duplicate_U0_din() {
    start_for_Duplicate_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void sobel_accel::thread_start_for_GaussianBlur_U0_din() {
    start_for_GaussianBlur_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void sobel_accel::thread_start_for_Mat2AXIvideo_U0_din() {
    start_for_Mat2AXIvideo_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void sobel_accel::thread_start_for_Sobel_1_U0_din() {
    start_for_Sobel_1_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void sobel_accel::thread_start_for_Sobel_U0_din() {
    start_for_Sobel_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void sobel_accel::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"s_axi_CONTROL_BUS_AWVALID\" :  \"" << s_axi_CONTROL_BUS_AWVALID.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"s_axi_CONTROL_BUS_AWREADY\" :  \"" << s_axi_CONTROL_BUS_AWREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_AWADDR\" :  \"" << s_axi_CONTROL_BUS_AWADDR.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_WVALID\" :  \"" << s_axi_CONTROL_BUS_WVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_WREADY\" :  \"" << s_axi_CONTROL_BUS_WREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_WDATA\" :  \"" << s_axi_CONTROL_BUS_WDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_WSTRB\" :  \"" << s_axi_CONTROL_BUS_WSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_ARVALID\" :  \"" << s_axi_CONTROL_BUS_ARVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_ARREADY\" :  \"" << s_axi_CONTROL_BUS_ARREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_ARADDR\" :  \"" << s_axi_CONTROL_BUS_ARADDR.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_RVALID\" :  \"" << s_axi_CONTROL_BUS_RVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_RREADY\" :  \"" << s_axi_CONTROL_BUS_RREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_RDATA\" :  \"" << s_axi_CONTROL_BUS_RDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_RRESP\" :  \"" << s_axi_CONTROL_BUS_RRESP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_BVALID\" :  \"" << s_axi_CONTROL_BUS_BVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"s_axi_CONTROL_BUS_BREADY\" :  \"" << s_axi_CONTROL_BUS_BREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_axi_CONTROL_BUS_BRESP\" :  \"" << s_axi_CONTROL_BUS_BRESP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"interrupt\" :  \"" << interrupt.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TDATA\" :  \"" << INPUT_STREAM_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TKEEP\" :  \"" << INPUT_STREAM_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TSTRB\" :  \"" << INPUT_STREAM_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TUSER\" :  \"" << INPUT_STREAM_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TLAST\" :  \"" << INPUT_STREAM_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TID\" :  \"" << INPUT_STREAM_TID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TDEST\" :  \"" << INPUT_STREAM_TDEST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TDATA\" :  \"" << OUTPUT_STREAM_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TKEEP\" :  \"" << OUTPUT_STREAM_TKEEP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TSTRB\" :  \"" << OUTPUT_STREAM_TSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TUSER\" :  \"" << OUTPUT_STREAM_TUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TLAST\" :  \"" << OUTPUT_STREAM_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TID\" :  \"" << OUTPUT_STREAM_TID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TDEST\" :  \"" << OUTPUT_STREAM_TDEST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"INPUT_STREAM_TVALID\" :  \"" << INPUT_STREAM_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"INPUT_STREAM_TREADY\" :  \"" << INPUT_STREAM_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"OUTPUT_STREAM_TVALID\" :  \"" << OUTPUT_STREAM_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"OUTPUT_STREAM_TREADY\" :  \"" << OUTPUT_STREAM_TREADY.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

