// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _sobel_accel_HH_
#define _sobel_accel_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "Block_proc.h"
#include "AXIvideo2Mat.h"
#include "CvtColor_1.h"
#include "GaussianBlur.h"
#include "Duplicate.h"
#include "Sobel.h"
#include "Sobel_1.h"
#include "AddWeighted.h"
#include "CvtColor.h"
#include "Mat2AXIvideo.h"
#include "fifo_w12_d2_A.h"
#include "fifo_w12_d7_A.h"
#include "fifo_w8_d2_A.h"
#include "start_for_AddWeigvdy.h"
#include "start_for_CvtColowdI.h"
#include "start_for_GaussiaxdS.h"
#include "start_for_Duplicayd2.h"
#include "start_for_Sobel_U0.h"
#include "start_for_Sobel_1zec.h"
#include "start_for_CvtColoAem.h"
#include "start_for_Mat2AXIBew.h"
#include "sobel_accel_CONTROL_BUS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_CONTROL_BUS_ADDR_WIDTH = 4,
         unsigned int C_S_AXI_CONTROL_BUS_DATA_WIDTH = 32>
struct sobel_accel : public sc_module {
    // Port declarations 38
    sc_in< sc_logic > s_axi_CONTROL_BUS_AWVALID;
    sc_out< sc_logic > s_axi_CONTROL_BUS_AWREADY;
    sc_in< sc_uint<C_S_AXI_CONTROL_BUS_ADDR_WIDTH> > s_axi_CONTROL_BUS_AWADDR;
    sc_in< sc_logic > s_axi_CONTROL_BUS_WVALID;
    sc_out< sc_logic > s_axi_CONTROL_BUS_WREADY;
    sc_in< sc_uint<C_S_AXI_CONTROL_BUS_DATA_WIDTH> > s_axi_CONTROL_BUS_WDATA;
    sc_in< sc_uint<C_S_AXI_CONTROL_BUS_DATA_WIDTH/8> > s_axi_CONTROL_BUS_WSTRB;
    sc_in< sc_logic > s_axi_CONTROL_BUS_ARVALID;
    sc_out< sc_logic > s_axi_CONTROL_BUS_ARREADY;
    sc_in< sc_uint<C_S_AXI_CONTROL_BUS_ADDR_WIDTH> > s_axi_CONTROL_BUS_ARADDR;
    sc_out< sc_logic > s_axi_CONTROL_BUS_RVALID;
    sc_in< sc_logic > s_axi_CONTROL_BUS_RREADY;
    sc_out< sc_uint<C_S_AXI_CONTROL_BUS_DATA_WIDTH> > s_axi_CONTROL_BUS_RDATA;
    sc_out< sc_lv<2> > s_axi_CONTROL_BUS_RRESP;
    sc_out< sc_logic > s_axi_CONTROL_BUS_BVALID;
    sc_in< sc_logic > s_axi_CONTROL_BUS_BREADY;
    sc_out< sc_lv<2> > s_axi_CONTROL_BUS_BRESP;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_out< sc_logic > interrupt;
    sc_in< sc_lv<24> > INPUT_STREAM_TDATA;
    sc_in< sc_lv<3> > INPUT_STREAM_TKEEP;
    sc_in< sc_lv<3> > INPUT_STREAM_TSTRB;
    sc_in< sc_lv<1> > INPUT_STREAM_TUSER;
    sc_in< sc_lv<1> > INPUT_STREAM_TLAST;
    sc_in< sc_lv<1> > INPUT_STREAM_TID;
    sc_in< sc_lv<1> > INPUT_STREAM_TDEST;
    sc_out< sc_lv<24> > OUTPUT_STREAM_TDATA;
    sc_out< sc_lv<3> > OUTPUT_STREAM_TKEEP;
    sc_out< sc_lv<3> > OUTPUT_STREAM_TSTRB;
    sc_out< sc_lv<1> > OUTPUT_STREAM_TUSER;
    sc_out< sc_lv<1> > OUTPUT_STREAM_TLAST;
    sc_out< sc_lv<1> > OUTPUT_STREAM_TID;
    sc_out< sc_lv<1> > OUTPUT_STREAM_TDEST;
    sc_in< sc_logic > INPUT_STREAM_TVALID;
    sc_out< sc_logic > INPUT_STREAM_TREADY;
    sc_out< sc_logic > OUTPUT_STREAM_TVALID;
    sc_in< sc_logic > OUTPUT_STREAM_TREADY;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    sobel_accel(sc_module_name name);
    SC_HAS_PROCESS(sobel_accel);

    ~sobel_accel();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sobel_accel_CONTROL_BUS_s_axi<C_S_AXI_CONTROL_BUS_ADDR_WIDTH,C_S_AXI_CONTROL_BUS_DATA_WIDTH>* sobel_accel_CONTROL_BUS_s_axi_U;
    Block_proc* Block_proc_U0;
    AXIvideo2Mat* AXIvideo2Mat_U0;
    CvtColor_1* CvtColor_1_U0;
    GaussianBlur* GaussianBlur_U0;
    Duplicate* Duplicate_U0;
    Sobel* Sobel_U0;
    Sobel_1* Sobel_1_U0;
    AddWeighted* AddWeighted_U0;
    CvtColor* CvtColor_U0;
    Mat2AXIvideo* Mat2AXIvideo_U0;
    fifo_w12_d2_A* src_rows_V_c_U;
    fifo_w12_d2_A* src_cols_V_c_U;
    fifo_w12_d7_A* sobel_g_rows_V_c_U;
    fifo_w12_d7_A* sobel_g_cols_V_c_U;
    fifo_w8_d2_A* src_data_stream_0_V_U;
    fifo_w8_d2_A* src_data_stream_1_V_U;
    fifo_w8_d2_A* src_data_stream_2_V_U;
    fifo_w12_d2_A* src_rows_V_c22_U;
    fifo_w12_d2_A* src_cols_V_c23_U;
    fifo_w8_d2_A* gray_data_stream_0_s_U;
    fifo_w8_d2_A* blurred_data_stream_s_U;
    fifo_w8_d2_A* gray1_data_stream_0_U;
    fifo_w8_d2_A* gray2_data_stream_0_U;
    fifo_w8_d2_A* sobel_x_data_stream_s_U;
    fifo_w8_d2_A* sobel_y_data_stream_s_U;
    fifo_w8_d2_A* sobel_g_data_stream_s_U;
    fifo_w12_d2_A* sobel_g_rows_V_c24_U;
    fifo_w12_d2_A* sobel_g_cols_V_c25_U;
    fifo_w8_d2_A* dst_data_stream_0_V_U;
    fifo_w8_d2_A* dst_data_stream_1_V_U;
    fifo_w8_d2_A* dst_data_stream_2_V_U;
    start_for_AddWeigvdy* start_for_AddWeigvdy_U;
    start_for_CvtColowdI* start_for_CvtColowdI_U;
    start_for_GaussiaxdS* start_for_GaussiaxdS_U;
    start_for_Duplicayd2* start_for_Duplicayd2_U;
    start_for_Sobel_U0* start_for_Sobel_U0_U;
    start_for_Sobel_1zec* start_for_Sobel_1zec_U;
    start_for_CvtColoAem* start_for_CvtColoAem_U;
    start_for_Mat2AXIBew* start_for_Mat2AXIBew_U;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_logic > Block_proc_U0_ap_start;
    sc_signal< sc_logic > Block_proc_U0_ap_done;
    sc_signal< sc_logic > Block_proc_U0_ap_continue;
    sc_signal< sc_logic > Block_proc_U0_ap_idle;
    sc_signal< sc_logic > Block_proc_U0_ap_ready;
    sc_signal< sc_logic > Block_proc_U0_start_out;
    sc_signal< sc_logic > Block_proc_U0_start_write;
    sc_signal< sc_lv<12> > Block_proc_U0_src_rows_V_out_din;
    sc_signal< sc_logic > Block_proc_U0_src_rows_V_out_write;
    sc_signal< sc_lv<12> > Block_proc_U0_src_cols_V_out_din;
    sc_signal< sc_logic > Block_proc_U0_src_cols_V_out_write;
    sc_signal< sc_lv<12> > Block_proc_U0_sobel_g_rows_V_out_din;
    sc_signal< sc_logic > Block_proc_U0_sobel_g_rows_V_out_write;
    sc_signal< sc_lv<12> > Block_proc_U0_sobel_g_cols_V_out_din;
    sc_signal< sc_logic > Block_proc_U0_sobel_g_cols_V_out_write;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_start;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_done;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_continue;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_idle;
    sc_signal< sc_logic > AXIvideo2Mat_U0_ap_ready;
    sc_signal< sc_logic > AXIvideo2Mat_U0_start_out;
    sc_signal< sc_logic > AXIvideo2Mat_U0_start_write;
    sc_signal< sc_logic > AXIvideo2Mat_U0_INPUT_STREAM_TREADY;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_rows_V_read;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_cols_V_read;
    sc_signal< sc_lv<8> > AXIvideo2Mat_U0_img_data_stream_0_V_din;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_data_stream_0_V_write;
    sc_signal< sc_lv<8> > AXIvideo2Mat_U0_img_data_stream_1_V_din;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_data_stream_1_V_write;
    sc_signal< sc_lv<8> > AXIvideo2Mat_U0_img_data_stream_2_V_din;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_data_stream_2_V_write;
    sc_signal< sc_lv<12> > AXIvideo2Mat_U0_img_rows_V_out_din;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_rows_V_out_write;
    sc_signal< sc_lv<12> > AXIvideo2Mat_U0_img_cols_V_out_din;
    sc_signal< sc_logic > AXIvideo2Mat_U0_img_cols_V_out_write;
    sc_signal< sc_logic > CvtColor_1_U0_ap_start;
    sc_signal< sc_logic > CvtColor_1_U0_ap_done;
    sc_signal< sc_logic > CvtColor_1_U0_ap_continue;
    sc_signal< sc_logic > CvtColor_1_U0_ap_idle;
    sc_signal< sc_logic > CvtColor_1_U0_ap_ready;
    sc_signal< sc_logic > CvtColor_1_U0_start_out;
    sc_signal< sc_logic > CvtColor_1_U0_start_write;
    sc_signal< sc_logic > CvtColor_1_U0_p_src_rows_V_read;
    sc_signal< sc_logic > CvtColor_1_U0_p_src_cols_V_read;
    sc_signal< sc_logic > CvtColor_1_U0_p_src_data_stream_0_V_read;
    sc_signal< sc_logic > CvtColor_1_U0_p_src_data_stream_1_V_read;
    sc_signal< sc_logic > CvtColor_1_U0_p_src_data_stream_2_V_read;
    sc_signal< sc_lv<8> > CvtColor_1_U0_p_dst_data_stream_V_din;
    sc_signal< sc_logic > CvtColor_1_U0_p_dst_data_stream_V_write;
    sc_signal< sc_logic > GaussianBlur_U0_ap_start;
    sc_signal< sc_logic > GaussianBlur_U0_ap_done;
    sc_signal< sc_logic > GaussianBlur_U0_ap_continue;
    sc_signal< sc_logic > GaussianBlur_U0_ap_idle;
    sc_signal< sc_logic > GaussianBlur_U0_ap_ready;
    sc_signal< sc_logic > GaussianBlur_U0_start_out;
    sc_signal< sc_logic > GaussianBlur_U0_start_write;
    sc_signal< sc_logic > GaussianBlur_U0_p_src_data_stream_V_read;
    sc_signal< sc_lv<8> > GaussianBlur_U0_p_dst_data_stream_V_din;
    sc_signal< sc_logic > GaussianBlur_U0_p_dst_data_stream_V_write;
    sc_signal< sc_logic > Duplicate_U0_ap_start;
    sc_signal< sc_logic > Duplicate_U0_start_full_n;
    sc_signal< sc_logic > Duplicate_U0_ap_done;
    sc_signal< sc_logic > Duplicate_U0_ap_continue;
    sc_signal< sc_logic > Duplicate_U0_ap_idle;
    sc_signal< sc_logic > Duplicate_U0_ap_ready;
    sc_signal< sc_logic > Duplicate_U0_start_out;
    sc_signal< sc_logic > Duplicate_U0_start_write;
    sc_signal< sc_logic > Duplicate_U0_src_data_stream_V_read;
    sc_signal< sc_lv<8> > Duplicate_U0_dst1_data_stream_V_din;
    sc_signal< sc_logic > Duplicate_U0_dst1_data_stream_V_write;
    sc_signal< sc_lv<8> > Duplicate_U0_dst2_data_stream_V_din;
    sc_signal< sc_logic > Duplicate_U0_dst2_data_stream_V_write;
    sc_signal< sc_logic > Sobel_U0_ap_start;
    sc_signal< sc_logic > Sobel_U0_ap_done;
    sc_signal< sc_logic > Sobel_U0_ap_continue;
    sc_signal< sc_logic > Sobel_U0_ap_idle;
    sc_signal< sc_logic > Sobel_U0_ap_ready;
    sc_signal< sc_logic > Sobel_U0_p_src_data_stream_V_read;
    sc_signal< sc_lv<8> > Sobel_U0_p_dst_data_stream_V_din;
    sc_signal< sc_logic > Sobel_U0_p_dst_data_stream_V_write;
    sc_signal< sc_logic > Sobel_1_U0_ap_start;
    sc_signal< sc_logic > Sobel_1_U0_ap_done;
    sc_signal< sc_logic > Sobel_1_U0_ap_continue;
    sc_signal< sc_logic > Sobel_1_U0_ap_idle;
    sc_signal< sc_logic > Sobel_1_U0_ap_ready;
    sc_signal< sc_logic > Sobel_1_U0_p_src_data_stream_V_read;
    sc_signal< sc_lv<8> > Sobel_1_U0_p_dst_data_stream_V_din;
    sc_signal< sc_logic > Sobel_1_U0_p_dst_data_stream_V_write;
    sc_signal< sc_logic > AddWeighted_U0_ap_start;
    sc_signal< sc_logic > AddWeighted_U0_ap_done;
    sc_signal< sc_logic > AddWeighted_U0_ap_continue;
    sc_signal< sc_logic > AddWeighted_U0_ap_idle;
    sc_signal< sc_logic > AddWeighted_U0_ap_ready;
    sc_signal< sc_logic > AddWeighted_U0_start_out;
    sc_signal< sc_logic > AddWeighted_U0_start_write;
    sc_signal< sc_logic > AddWeighted_U0_src1_data_stream_V_read;
    sc_signal< sc_logic > AddWeighted_U0_src2_data_stream_V_read;
    sc_signal< sc_logic > AddWeighted_U0_dst_rows_V_read;
    sc_signal< sc_logic > AddWeighted_U0_dst_cols_V_read;
    sc_signal< sc_lv<8> > AddWeighted_U0_dst_data_stream_V_din;
    sc_signal< sc_logic > AddWeighted_U0_dst_data_stream_V_write;
    sc_signal< sc_lv<12> > AddWeighted_U0_dst_rows_V_out_din;
    sc_signal< sc_logic > AddWeighted_U0_dst_rows_V_out_write;
    sc_signal< sc_lv<12> > AddWeighted_U0_dst_cols_V_out_din;
    sc_signal< sc_logic > AddWeighted_U0_dst_cols_V_out_write;
    sc_signal< sc_logic > CvtColor_U0_ap_start;
    sc_signal< sc_logic > CvtColor_U0_ap_done;
    sc_signal< sc_logic > CvtColor_U0_ap_continue;
    sc_signal< sc_logic > CvtColor_U0_ap_idle;
    sc_signal< sc_logic > CvtColor_U0_ap_ready;
    sc_signal< sc_logic > CvtColor_U0_start_out;
    sc_signal< sc_logic > CvtColor_U0_start_write;
    sc_signal< sc_logic > CvtColor_U0_p_src_rows_V_read;
    sc_signal< sc_logic > CvtColor_U0_p_src_cols_V_read;
    sc_signal< sc_logic > CvtColor_U0_p_src_data_stream_V_read;
    sc_signal< sc_lv<8> > CvtColor_U0_p_dst_data_stream_0_V_din;
    sc_signal< sc_logic > CvtColor_U0_p_dst_data_stream_0_V_write;
    sc_signal< sc_lv<8> > CvtColor_U0_p_dst_data_stream_1_V_din;
    sc_signal< sc_logic > CvtColor_U0_p_dst_data_stream_1_V_write;
    sc_signal< sc_lv<8> > CvtColor_U0_p_dst_data_stream_2_V_din;
    sc_signal< sc_logic > CvtColor_U0_p_dst_data_stream_2_V_write;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_start;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_done;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_continue;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_idle;
    sc_signal< sc_logic > Mat2AXIvideo_U0_ap_ready;
    sc_signal< sc_logic > Mat2AXIvideo_U0_img_data_stream_0_V_read;
    sc_signal< sc_logic > Mat2AXIvideo_U0_img_data_stream_1_V_read;
    sc_signal< sc_logic > Mat2AXIvideo_U0_img_data_stream_2_V_read;
    sc_signal< sc_lv<24> > Mat2AXIvideo_U0_OUTPUT_STREAM_TDATA;
    sc_signal< sc_logic > Mat2AXIvideo_U0_OUTPUT_STREAM_TVALID;
    sc_signal< sc_lv<3> > Mat2AXIvideo_U0_OUTPUT_STREAM_TKEEP;
    sc_signal< sc_lv<3> > Mat2AXIvideo_U0_OUTPUT_STREAM_TSTRB;
    sc_signal< sc_lv<1> > Mat2AXIvideo_U0_OUTPUT_STREAM_TUSER;
    sc_signal< sc_lv<1> > Mat2AXIvideo_U0_OUTPUT_STREAM_TLAST;
    sc_signal< sc_lv<1> > Mat2AXIvideo_U0_OUTPUT_STREAM_TID;
    sc_signal< sc_lv<1> > Mat2AXIvideo_U0_OUTPUT_STREAM_TDEST;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > src_rows_V_c_full_n;
    sc_signal< sc_lv<12> > src_rows_V_c_dout;
    sc_signal< sc_logic > src_rows_V_c_empty_n;
    sc_signal< sc_logic > src_cols_V_c_full_n;
    sc_signal< sc_lv<12> > src_cols_V_c_dout;
    sc_signal< sc_logic > src_cols_V_c_empty_n;
    sc_signal< sc_logic > sobel_g_rows_V_c_full_n;
    sc_signal< sc_lv<12> > sobel_g_rows_V_c_dout;
    sc_signal< sc_logic > sobel_g_rows_V_c_empty_n;
    sc_signal< sc_logic > sobel_g_cols_V_c_full_n;
    sc_signal< sc_lv<12> > sobel_g_cols_V_c_dout;
    sc_signal< sc_logic > sobel_g_cols_V_c_empty_n;
    sc_signal< sc_logic > src_data_stream_0_V_full_n;
    sc_signal< sc_lv<8> > src_data_stream_0_V_dout;
    sc_signal< sc_logic > src_data_stream_0_V_empty_n;
    sc_signal< sc_logic > src_data_stream_1_V_full_n;
    sc_signal< sc_lv<8> > src_data_stream_1_V_dout;
    sc_signal< sc_logic > src_data_stream_1_V_empty_n;
    sc_signal< sc_logic > src_data_stream_2_V_full_n;
    sc_signal< sc_lv<8> > src_data_stream_2_V_dout;
    sc_signal< sc_logic > src_data_stream_2_V_empty_n;
    sc_signal< sc_logic > src_rows_V_c22_full_n;
    sc_signal< sc_lv<12> > src_rows_V_c22_dout;
    sc_signal< sc_logic > src_rows_V_c22_empty_n;
    sc_signal< sc_logic > src_cols_V_c23_full_n;
    sc_signal< sc_lv<12> > src_cols_V_c23_dout;
    sc_signal< sc_logic > src_cols_V_c23_empty_n;
    sc_signal< sc_logic > gray_data_stream_0_s_full_n;
    sc_signal< sc_lv<8> > gray_data_stream_0_s_dout;
    sc_signal< sc_logic > gray_data_stream_0_s_empty_n;
    sc_signal< sc_logic > blurred_data_stream_s_full_n;
    sc_signal< sc_lv<8> > blurred_data_stream_s_dout;
    sc_signal< sc_logic > blurred_data_stream_s_empty_n;
    sc_signal< sc_logic > gray1_data_stream_0_full_n;
    sc_signal< sc_lv<8> > gray1_data_stream_0_dout;
    sc_signal< sc_logic > gray1_data_stream_0_empty_n;
    sc_signal< sc_logic > gray2_data_stream_0_full_n;
    sc_signal< sc_lv<8> > gray2_data_stream_0_dout;
    sc_signal< sc_logic > gray2_data_stream_0_empty_n;
    sc_signal< sc_logic > sobel_x_data_stream_s_full_n;
    sc_signal< sc_lv<8> > sobel_x_data_stream_s_dout;
    sc_signal< sc_logic > sobel_x_data_stream_s_empty_n;
    sc_signal< sc_logic > sobel_y_data_stream_s_full_n;
    sc_signal< sc_lv<8> > sobel_y_data_stream_s_dout;
    sc_signal< sc_logic > sobel_y_data_stream_s_empty_n;
    sc_signal< sc_logic > sobel_g_data_stream_s_full_n;
    sc_signal< sc_lv<8> > sobel_g_data_stream_s_dout;
    sc_signal< sc_logic > sobel_g_data_stream_s_empty_n;
    sc_signal< sc_logic > sobel_g_rows_V_c24_full_n;
    sc_signal< sc_lv<12> > sobel_g_rows_V_c24_dout;
    sc_signal< sc_logic > sobel_g_rows_V_c24_empty_n;
    sc_signal< sc_logic > sobel_g_cols_V_c25_full_n;
    sc_signal< sc_lv<12> > sobel_g_cols_V_c25_dout;
    sc_signal< sc_logic > sobel_g_cols_V_c25_empty_n;
    sc_signal< sc_logic > dst_data_stream_0_V_full_n;
    sc_signal< sc_lv<8> > dst_data_stream_0_V_dout;
    sc_signal< sc_logic > dst_data_stream_0_V_empty_n;
    sc_signal< sc_logic > dst_data_stream_1_V_full_n;
    sc_signal< sc_lv<8> > dst_data_stream_1_V_dout;
    sc_signal< sc_logic > dst_data_stream_1_V_empty_n;
    sc_signal< sc_logic > dst_data_stream_2_V_full_n;
    sc_signal< sc_lv<8> > dst_data_stream_2_V_dout;
    sc_signal< sc_logic > dst_data_stream_2_V_empty_n;
    sc_signal< sc_logic > ap_sync_done;
    sc_signal< sc_logic > ap_sync_ready;
    sc_signal< sc_logic > ap_sync_reg_Block_proc_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_Block_proc_U0_ap_ready;
    sc_signal< sc_lv<2> > Block_proc_U0_ap_ready_count;
    sc_signal< sc_logic > ap_sync_reg_AXIvideo2Mat_U0_ap_ready;
    sc_signal< sc_logic > ap_sync_AXIvideo2Mat_U0_ap_ready;
    sc_signal< sc_lv<2> > AXIvideo2Mat_U0_ap_ready_count;
    sc_signal< sc_lv<1> > start_for_AddWeighted_U0_din;
    sc_signal< sc_logic > start_for_AddWeighted_U0_full_n;
    sc_signal< sc_lv<1> > start_for_AddWeighted_U0_dout;
    sc_signal< sc_logic > start_for_AddWeighted_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_CvtColor_1_U0_din;
    sc_signal< sc_logic > start_for_CvtColor_1_U0_full_n;
    sc_signal< sc_lv<1> > start_for_CvtColor_1_U0_dout;
    sc_signal< sc_logic > start_for_CvtColor_1_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_GaussianBlur_U0_din;
    sc_signal< sc_logic > start_for_GaussianBlur_U0_full_n;
    sc_signal< sc_lv<1> > start_for_GaussianBlur_U0_dout;
    sc_signal< sc_logic > start_for_GaussianBlur_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_Duplicate_U0_din;
    sc_signal< sc_logic > start_for_Duplicate_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Duplicate_U0_dout;
    sc_signal< sc_logic > start_for_Duplicate_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_Sobel_U0_din;
    sc_signal< sc_logic > start_for_Sobel_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Sobel_U0_dout;
    sc_signal< sc_logic > start_for_Sobel_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_Sobel_1_U0_din;
    sc_signal< sc_logic > start_for_Sobel_1_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Sobel_1_U0_dout;
    sc_signal< sc_logic > start_for_Sobel_1_U0_empty_n;
    sc_signal< sc_logic > Sobel_U0_start_full_n;
    sc_signal< sc_logic > Sobel_U0_start_write;
    sc_signal< sc_logic > Sobel_1_U0_start_full_n;
    sc_signal< sc_logic > Sobel_1_U0_start_write;
    sc_signal< sc_lv<1> > start_for_CvtColor_U0_din;
    sc_signal< sc_logic > start_for_CvtColor_U0_full_n;
    sc_signal< sc_lv<1> > start_for_CvtColor_U0_dout;
    sc_signal< sc_logic > start_for_CvtColor_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_Mat2AXIvideo_U0_din;
    sc_signal< sc_logic > start_for_Mat2AXIvideo_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Mat2AXIvideo_U0_dout;
    sc_signal< sc_logic > start_for_Mat2AXIvideo_U0_empty_n;
    sc_signal< sc_logic > Mat2AXIvideo_U0_start_full_n;
    sc_signal< sc_logic > Mat2AXIvideo_U0_start_write;
    static const int C_S_AXI_DATA_WIDTH;
    static const int C_S_AXI_WSTRB_WIDTH;
    static const int C_S_AXI_ADDR_WIDTH;
    static const sc_logic ap_const_logic_1;
    static const sc_lv<24> ap_const_lv24_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<2> ap_const_lv2_1;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_AXIvideo2Mat_U0_ap_continue();
    void thread_AXIvideo2Mat_U0_ap_start();
    void thread_AddWeighted_U0_ap_continue();
    void thread_AddWeighted_U0_ap_start();
    void thread_Block_proc_U0_ap_continue();
    void thread_Block_proc_U0_ap_start();
    void thread_CvtColor_1_U0_ap_continue();
    void thread_CvtColor_1_U0_ap_start();
    void thread_CvtColor_U0_ap_continue();
    void thread_CvtColor_U0_ap_start();
    void thread_Duplicate_U0_ap_continue();
    void thread_Duplicate_U0_ap_start();
    void thread_Duplicate_U0_start_full_n();
    void thread_GaussianBlur_U0_ap_continue();
    void thread_GaussianBlur_U0_ap_start();
    void thread_INPUT_STREAM_TREADY();
    void thread_Mat2AXIvideo_U0_ap_continue();
    void thread_Mat2AXIvideo_U0_ap_start();
    void thread_Mat2AXIvideo_U0_start_full_n();
    void thread_Mat2AXIvideo_U0_start_write();
    void thread_OUTPUT_STREAM_TDATA();
    void thread_OUTPUT_STREAM_TDEST();
    void thread_OUTPUT_STREAM_TID();
    void thread_OUTPUT_STREAM_TKEEP();
    void thread_OUTPUT_STREAM_TLAST();
    void thread_OUTPUT_STREAM_TSTRB();
    void thread_OUTPUT_STREAM_TUSER();
    void thread_OUTPUT_STREAM_TVALID();
    void thread_Sobel_1_U0_ap_continue();
    void thread_Sobel_1_U0_ap_start();
    void thread_Sobel_1_U0_start_full_n();
    void thread_Sobel_1_U0_start_write();
    void thread_Sobel_U0_ap_continue();
    void thread_Sobel_U0_ap_start();
    void thread_Sobel_U0_start_full_n();
    void thread_Sobel_U0_start_write();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_ap_sync_AXIvideo2Mat_U0_ap_ready();
    void thread_ap_sync_Block_proc_U0_ap_ready();
    void thread_ap_sync_continue();
    void thread_ap_sync_done();
    void thread_ap_sync_ready();
    void thread_start_for_AddWeighted_U0_din();
    void thread_start_for_CvtColor_1_U0_din();
    void thread_start_for_CvtColor_U0_din();
    void thread_start_for_Duplicate_U0_din();
    void thread_start_for_GaussianBlur_U0_din();
    void thread_start_for_Mat2AXIvideo_U0_din();
    void thread_start_for_Sobel_1_U0_din();
    void thread_start_for_Sobel_U0_din();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
