// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "ConvertScaleAbs.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic ConvertScaleAbs::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic ConvertScaleAbs::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> ConvertScaleAbs::ap_ST_fsm_state1 = "1";
const sc_lv<4> ConvertScaleAbs::ap_ST_fsm_state2 = "10";
const sc_lv<4> ConvertScaleAbs::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<4> ConvertScaleAbs::ap_ST_fsm_state11 = "1000";
const sc_lv<32> ConvertScaleAbs::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool ConvertScaleAbs::ap_const_boolean_1 = true;
const sc_lv<32> ConvertScaleAbs::ap_const_lv32_2 = "10";
const bool ConvertScaleAbs::ap_const_boolean_0 = false;
const sc_lv<1> ConvertScaleAbs::ap_const_lv1_0 = "0";
const sc_lv<32> ConvertScaleAbs::ap_const_lv32_1 = "1";
const sc_lv<1> ConvertScaleAbs::ap_const_lv1_1 = "1";
const sc_lv<11> ConvertScaleAbs::ap_const_lv11_0 = "00000000000";
const sc_lv<32> ConvertScaleAbs::ap_const_lv32_3 = "11";
const sc_lv<11> ConvertScaleAbs::ap_const_lv11_438 = "10000111000";
const sc_lv<11> ConvertScaleAbs::ap_const_lv11_1 = "1";
const sc_lv<11> ConvertScaleAbs::ap_const_lv11_780 = "11110000000";
const sc_lv<32> ConvertScaleAbs::ap_const_lv32_34 = "110100";
const sc_lv<32> ConvertScaleAbs::ap_const_lv32_3E = "111110";
const sc_lv<11> ConvertScaleAbs::ap_const_lv11_7FF = "11111111111";
const sc_lv<52> ConvertScaleAbs::ap_const_lv52_0 = "0000000000000000000000000000000000000000000000000000";
const sc_lv<63> ConvertScaleAbs::ap_const_lv63_0 = "000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<12> ConvertScaleAbs::ap_const_lv12_433 = "10000110011";
const sc_lv<12> ConvertScaleAbs::ap_const_lv12_0 = "000000000000";
const sc_lv<11> ConvertScaleAbs::ap_const_lv11_433 = "10000110011";
const sc_lv<12> ConvertScaleAbs::ap_const_lv12_36 = "110110";
const sc_lv<32> ConvertScaleAbs::ap_const_lv32_B = "1011";
const sc_lv<9> ConvertScaleAbs::ap_const_lv9_0 = "000000000";
const sc_lv<8> ConvertScaleAbs::ap_const_lv8_0 = "00000000";
const sc_lv<12> ConvertScaleAbs::ap_const_lv12_FFF = "111111111111";
const sc_lv<32> ConvertScaleAbs::ap_const_lv32_7 = "111";
const sc_lv<12> ConvertScaleAbs::ap_const_lv12_8 = "1000";
const sc_lv<12> ConvertScaleAbs::ap_const_lv12_9 = "1001";
const sc_lv<54> ConvertScaleAbs::ap_const_lv54_3FFFFFFFFFFFFF = "111111111111111111111111111111111111111111111111111111";
const sc_lv<54> ConvertScaleAbs::ap_const_lv54_0 = "000000000000000000000000000000000000000000000000000000";
const sc_lv<8> ConvertScaleAbs::ap_const_lv8_FF = "11111111";

ConvertScaleAbs::ConvertScaleAbs(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sobel_accel_sitodtde_U84 = new sobel_accel_sitodtde<1,4,32,64>("sobel_accel_sitodtde_U84");
    sobel_accel_sitodtde_U84->clk(ap_clk);
    sobel_accel_sitodtde_U84->reset(ap_rst);
    sobel_accel_sitodtde_U84->din0(grp_fu_171_p0);
    sobel_accel_sitodtde_U84->ce(grp_fu_171_ce);
    sobel_accel_sitodtde_U84->dout(grp_fu_171_p1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_F2_4_fu_281_p3);
    sensitive << ( F2_fu_263_p2 );
    sensitive << ( icmp_ln581_fu_269_p2 );
    sensitive << ( sub_ln581_fu_275_p2 );

    SC_METHOD(thread_F2_fu_263_p2);
    sensitive << ( zext_ln461_fu_241_p1 );

    SC_METHOD(thread_Range1_all_ones_2_fu_585_p2);
    sensitive << ( and_ln621_fu_579_p2 );
    sensitive << ( icmp_ln621_fu_545_p2 );

    SC_METHOD(thread_Range1_all_ones_fu_653_p2);
    sensitive << ( select_ln631_fu_639_p3 );
    sensitive << ( Range1_all_ones_2_fu_585_p2 );

    SC_METHOD(thread_Range1_all_zeros_2_fu_683_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_834_pp0_iter5_reg );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( p_Result_12_fu_253_p1 );

    SC_METHOD(thread_Range1_all_zeros_fu_665_p2);
    sensitive << ( Range1_all_ones_2_fu_585_p2 );

    SC_METHOD(thread_Range2_V_2_fu_621_p2);
    sensitive << ( p_Result_12_fu_253_p1 );
    sensitive << ( zext_ln635_fu_617_p1 );

    SC_METHOD(thread_Range2_all_ones_fu_633_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_834_pp0_iter5_reg );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( Range2_V_2_fu_621_p2 );
    sensitive << ( r_V_fu_627_p2 );

    SC_METHOD(thread_add_ln591_fu_363_p2);
    sensitive << ( F2_fu_263_p2 );

    SC_METHOD(thread_and_ln403_2_fu_461_p2);
    sensitive << ( and_ln581_fu_435_p2 );
    sensitive << ( xor_ln403_fu_455_p2 );

    SC_METHOD(thread_and_ln403_fu_441_p2);
    sensitive << ( and_ln581_fu_435_p2 );
    sensitive << ( p_Result_13_fu_389_p3 );

    SC_METHOD(thread_and_ln428_2_fu_773_p2);
    sensitive << ( icmp_ln833_fu_223_p2 );
    sensitive << ( icmp_ln837_fu_229_p2 );

    SC_METHOD(thread_and_ln428_fu_235_p2);
    sensitive << ( icmp_ln833_fu_223_p2 );
    sensitive << ( icmp_ln837_fu_229_p2 );

    SC_METHOD(thread_and_ln571_fu_785_p2);
    sensitive << ( icmp_ln571_fu_257_p2 );
    sensitive << ( xor_ln428_fu_779_p2 );

    SC_METHOD(thread_and_ln581_fu_435_p2);
    sensitive << ( icmp_ln581_fu_269_p2 );
    sensitive << ( xor_ln582_fu_429_p2 );

    SC_METHOD(thread_and_ln603_3_fu_513_p2);
    sensitive << ( or_ln603_fu_507_p2 );
    sensitive << ( xor_ln416_fu_415_p2 );

    SC_METHOD(thread_and_ln603_4_fu_519_p2);
    sensitive << ( and_ln403_fu_441_p2 );
    sensitive << ( and_ln603_3_fu_513_p2 );

    SC_METHOD(thread_and_ln603_fu_487_p2);
    sensitive << ( icmp_ln603_fu_323_p2 );
    sensitive << ( xor_ln581_fu_481_p2 );

    SC_METHOD(thread_and_ln621_fu_579_p2);
    sensitive << ( lD_fu_575_p1 );
    sensitive << ( xor_ln621_2_fu_559_p2 );

    SC_METHOD(thread_and_ln631_fu_611_p2);
    sensitive << ( icmp_ln631_fu_605_p2 );
    sensitive << ( xor_ln631_fu_599_p2 );

    SC_METHOD(thread_and_ln639_fu_647_p2);
    sensitive << ( xor_ln621_2_fu_559_p2 );
    sensitive << ( icmp_ln631_fu_605_p2 );

    SC_METHOD(thread_and_ln641_fu_671_p2);
    sensitive << ( icmp_ln641_fu_659_p2 );
    sensitive << ( Range1_all_zeros_fu_665_p2 );

    SC_METHOD(thread_and_ln642_fu_707_p2);
    sensitive << ( icmp_ln642_fu_677_p2 );
    sensitive << ( or_ln639_fu_701_p2 );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( p_src_data_stream_V_empty_n );
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln2527_reg_834 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( icmp_ln2527_reg_834_pp0_iter6_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( p_src_data_stream_V_empty_n );
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln2527_reg_834 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( icmp_ln2527_reg_834_pp0_iter6_reg );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( p_src_data_stream_V_empty_n );
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln2527_reg_834 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( icmp_ln2527_reg_834_pp0_iter6_reg );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state10_pp0_stage0_iter7);
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( icmp_ln2527_reg_834_pp0_iter6_reg );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);
    sensitive << ( p_src_data_stream_V_empty_n );
    sensitive << ( icmp_ln2527_reg_834 );

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state9_pp0_stage0_iter6);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state3);
    sensitive << ( icmp_ln2527_fu_186_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( icmp_ln2526_fu_174_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( icmp_ln2526_fu_174_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ashr_ln586_fu_333_p2);
    sensitive << ( p_Result_12_fu_253_p1 );
    sensitive << ( zext_ln586_fu_329_p1 );

    SC_METHOD(thread_ashr_ln623_fu_569_p2);
    sensitive << ( p_Result_12_fu_253_p1 );
    sensitive << ( zext_ln623_fu_565_p1 );

    SC_METHOD(thread_deleted_zeros_fu_745_p3);
    sensitive << ( and_ln603_4_fu_519_p2 );
    sensitive << ( select_ln639_fu_721_p3 );
    sensitive << ( select_ln639_2_fu_737_p3 );

    SC_METHOD(thread_grp_fu_171_ce);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_grp_fu_171_p0);
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_reg_843 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_i_fu_180_p2);
    sensitive << ( i_0_reg_149 );

    SC_METHOD(thread_icmp_ln2526_fu_174_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_149 );

    SC_METHOD(thread_icmp_ln2527_fu_186_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( j_0_reg_160 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_icmp_ln571_fu_257_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_834_pp0_iter5_reg );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( trunc_ln368_fu_205_p1 );

    SC_METHOD(thread_icmp_ln581_fu_269_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_834_pp0_iter5_reg );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( F2_fu_263_p2 );

    SC_METHOD(thread_icmp_ln582_fu_297_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_834_pp0_iter5_reg );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( tmp_V_fu_209_p4 );

    SC_METHOD(thread_icmp_ln585_fu_307_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_834_pp0_iter5_reg );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( F2_4_fu_281_p3 );

    SC_METHOD(thread_icmp_ln591_fu_357_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_834_pp0_iter5_reg );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( F2_fu_263_p2 );

    SC_METHOD(thread_icmp_ln603_fu_323_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_834_pp0_iter5_reg );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( tmp_56_fu_313_p4 );

    SC_METHOD(thread_icmp_ln621_fu_545_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_834_pp0_iter5_reg );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( pos1_fu_525_p2 );

    SC_METHOD(thread_icmp_ln631_fu_605_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_834_pp0_iter5_reg );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( pos2_fu_535_p2 );

    SC_METHOD(thread_icmp_ln641_fu_659_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_834_pp0_iter5_reg );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( Range2_V_2_fu_621_p2 );

    SC_METHOD(thread_icmp_ln642_fu_677_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_834_pp0_iter5_reg );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( pos2_fu_535_p2 );

    SC_METHOD(thread_icmp_ln833_fu_223_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_834_pp0_iter5_reg );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( tmp_V_fu_209_p4 );

    SC_METHOD(thread_icmp_ln837_fu_229_p2);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( icmp_ln2527_reg_834_pp0_iter5_reg );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( tmp_V_4_fu_219_p1 );

    SC_METHOD(thread_j_fu_192_p2);
    sensitive << ( j_0_reg_160 );

    SC_METHOD(thread_lD_fu_575_p1);
    sensitive << ( ashr_ln623_fu_569_p2 );

    SC_METHOD(thread_or_ln571_2_fu_805_p2);
    sensitive << ( icmp_ln571_fu_257_p2 );
    sensitive << ( and_ln428_fu_235_p2 );

    SC_METHOD(thread_or_ln571_fu_791_p2);
    sensitive << ( and_ln571_fu_785_p2 );
    sensitive << ( and_ln428_fu_235_p2 );

    SC_METHOD(thread_or_ln581_fu_475_p2);
    sensitive << ( icmp_ln581_fu_269_p2 );
    sensitive << ( icmp_ln582_fu_297_p2 );

    SC_METHOD(thread_or_ln603_fu_507_p2);
    sensitive << ( or_ln581_fu_475_p2 );
    sensitive << ( xor_ln603_fu_501_p2 );

    SC_METHOD(thread_or_ln639_fu_701_p2);
    sensitive << ( tmp_59_fu_551_p3 );
    sensitive << ( xor_ln639_2_fu_695_p2 );

    SC_METHOD(thread_or_ln645_fu_689_p2);
    sensitive << ( xor_ln621_2_fu_559_p2 );
    sensitive << ( Range1_all_zeros_2_fu_683_p2 );

    SC_METHOD(thread_or_ln658_fu_759_p2);
    sensitive << ( xor_ln621_fu_753_p2 );
    sensitive << ( deleted_zeros_fu_745_p3 );

    SC_METHOD(thread_p_Result_12_fu_253_p1);
    sensitive << ( tmp_1_i_fu_245_p3 );

    SC_METHOD(thread_p_Result_13_fu_389_p3);
    sensitive << ( p_Val2_18_fu_349_p3 );

    SC_METHOD(thread_p_Result_s_fu_373_p3);
    sensitive << ( p_Result_12_fu_253_p1 );
    sensitive << ( zext_ln591_fu_369_p1 );

    SC_METHOD(thread_p_Val2_18_fu_349_p3);
    sensitive << ( icmp_ln585_fu_307_p2 );
    sensitive << ( trunc_ln586_fu_339_p1 );

    SC_METHOD(thread_p_Val2_19_fu_401_p2);
    sensitive << ( p_Val2_18_fu_349_p3 );
    sensitive << ( zext_ln415_fu_397_p1 );

    SC_METHOD(thread_p_Val2_20_fu_493_p3);
    sensitive << ( and_ln603_fu_487_p2 );
    sensitive << ( shl_ln604_fu_343_p2 );
    sensitive << ( select_ln403_2_fu_467_p3 );

    SC_METHOD(thread_p_Val2_s_fu_202_p1);
    sensitive << ( x_assign_reg_853 );

    SC_METHOD(thread_p_dst_data_stream_V_blk_n);
    sensitive << ( p_dst_data_stream_V_full_n );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( icmp_ln2527_reg_834_pp0_iter6_reg );

    SC_METHOD(thread_p_dst_data_stream_V_din);
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( icmp_ln2527_reg_834_pp0_iter6_reg );
    sensitive << ( tmp_61_reg_858 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_p_dst_data_stream_V_write);
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( icmp_ln2527_reg_834_pp0_iter6_reg );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_p_src_data_stream_V_blk_n);
    sensitive << ( p_src_data_stream_V_empty_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln2527_reg_834 );

    SC_METHOD(thread_p_src_data_stream_V_read);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln2527_reg_834 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_pos1_fu_525_p2);
    sensitive << ( F2_fu_263_p2 );

    SC_METHOD(thread_pos2_fu_535_p2);
    sensitive << ( F2_fu_263_p2 );

    SC_METHOD(thread_qb_fu_381_p3);
    sensitive << ( icmp_ln591_fu_357_p2 );
    sensitive << ( p_Result_s_fu_373_p3 );

    SC_METHOD(thread_r_V_fu_627_p2);
    sensitive << ( zext_ln635_fu_617_p1 );

    SC_METHOD(thread_select_ln340_fu_765_p3);
    sensitive << ( or_ln658_fu_759_p2 );
    sensitive << ( p_Val2_20_fu_493_p3 );

    SC_METHOD(thread_select_ln403_2_fu_467_p3);
    sensitive << ( p_Val2_19_fu_401_p2 );
    sensitive << ( and_ln403_2_fu_461_p2 );
    sensitive << ( select_ln403_fu_447_p3 );

    SC_METHOD(thread_select_ln403_fu_447_p3);
    sensitive << ( p_Val2_19_fu_401_p2 );
    sensitive << ( and_ln403_fu_441_p2 );
    sensitive << ( select_ln582_fu_421_p3 );

    SC_METHOD(thread_select_ln571_fu_797_p3);
    sensitive << ( p_Val2_20_fu_493_p3 );
    sensitive << ( or_ln571_fu_791_p2 );

    SC_METHOD(thread_select_ln582_fu_421_p3);
    sensitive << ( trunc_ln583_fu_303_p1 );
    sensitive << ( icmp_ln582_fu_297_p2 );

    SC_METHOD(thread_select_ln631_fu_639_p3);
    sensitive << ( xor_ln631_fu_599_p2 );
    sensitive << ( and_ln631_fu_611_p2 );
    sensitive << ( Range2_all_ones_fu_633_p2 );

    SC_METHOD(thread_select_ln639_2_fu_737_p3);
    sensitive << ( and_ln639_fu_647_p2 );
    sensitive << ( and_ln641_fu_671_p2 );
    sensitive << ( select_ln642_2_fu_729_p3 );

    SC_METHOD(thread_select_ln639_fu_721_p3);
    sensitive << ( and_ln639_fu_647_p2 );
    sensitive << ( Range1_all_ones_fu_653_p2 );
    sensitive << ( select_ln642_fu_713_p3 );

    SC_METHOD(thread_select_ln642_2_fu_729_p3);
    sensitive << ( Range1_all_zeros_fu_665_p2 );
    sensitive << ( and_ln642_fu_707_p2 );
    sensitive << ( or_ln645_fu_689_p2 );

    SC_METHOD(thread_select_ln642_fu_713_p3);
    sensitive << ( xor_ln621_2_fu_559_p2 );
    sensitive << ( Range1_all_ones_2_fu_585_p2 );
    sensitive << ( and_ln642_fu_707_p2 );

    SC_METHOD(thread_sext_ln581_fu_293_p1);
    sensitive << ( F2_4_fu_281_p3 );

    SC_METHOD(thread_sext_ln618_fu_531_p1);
    sensitive << ( pos1_fu_525_p2 );

    SC_METHOD(thread_sext_ln619_fu_541_p1);
    sensitive << ( pos2_fu_535_p2 );

    SC_METHOD(thread_shl_ln604_fu_343_p2);
    sensitive << ( trunc_ln583_fu_303_p1 );
    sensitive << ( trunc_ln581_fu_289_p1 );

    SC_METHOD(thread_sub_ln581_fu_275_p2);
    sensitive << ( F2_fu_263_p2 );

    SC_METHOD(thread_tmp_1_i_fu_245_p3);
    sensitive << ( tmp_V_4_fu_219_p1 );

    SC_METHOD(thread_tmp_56_fu_313_p4);
    sensitive << ( F2_4_fu_281_p3 );

    SC_METHOD(thread_tmp_58_fu_407_p3);
    sensitive << ( p_Val2_19_fu_401_p2 );

    SC_METHOD(thread_tmp_59_fu_551_p3);
    sensitive << ( pos1_fu_525_p2 );

    SC_METHOD(thread_tmp_60_fu_591_p3);
    sensitive << ( pos2_fu_535_p2 );

    SC_METHOD(thread_tmp_61_fu_817_p3);
    sensitive << ( xor_ln571_fu_811_p2 );
    sensitive << ( select_ln340_fu_765_p3 );
    sensitive << ( select_ln571_fu_797_p3 );

    SC_METHOD(thread_tmp_V_4_fu_219_p1);
    sensitive << ( p_Val2_s_fu_202_p1 );

    SC_METHOD(thread_tmp_V_fu_209_p4);
    sensitive << ( p_Val2_s_fu_202_p1 );

    SC_METHOD(thread_trunc_ln368_fu_205_p1);
    sensitive << ( p_Val2_s_fu_202_p1 );

    SC_METHOD(thread_trunc_ln581_fu_289_p1);
    sensitive << ( F2_4_fu_281_p3 );

    SC_METHOD(thread_trunc_ln583_fu_303_p1);
    sensitive << ( p_Val2_s_fu_202_p1 );

    SC_METHOD(thread_trunc_ln586_fu_339_p1);
    sensitive << ( ashr_ln586_fu_333_p2 );

    SC_METHOD(thread_xor_ln403_fu_455_p2);
    sensitive << ( p_Result_13_fu_389_p3 );

    SC_METHOD(thread_xor_ln416_fu_415_p2);
    sensitive << ( tmp_58_fu_407_p3 );

    SC_METHOD(thread_xor_ln428_fu_779_p2);
    sensitive << ( and_ln428_2_fu_773_p2 );

    SC_METHOD(thread_xor_ln571_fu_811_p2);
    sensitive << ( or_ln571_2_fu_805_p2 );

    SC_METHOD(thread_xor_ln581_fu_481_p2);
    sensitive << ( or_ln581_fu_475_p2 );

    SC_METHOD(thread_xor_ln582_fu_429_p2);
    sensitive << ( icmp_ln582_fu_297_p2 );

    SC_METHOD(thread_xor_ln603_fu_501_p2);
    sensitive << ( icmp_ln603_fu_323_p2 );

    SC_METHOD(thread_xor_ln621_2_fu_559_p2);
    sensitive << ( tmp_59_fu_551_p3 );

    SC_METHOD(thread_xor_ln621_fu_753_p2);
    sensitive << ( icmp_ln621_fu_545_p2 );

    SC_METHOD(thread_xor_ln631_fu_599_p2);
    sensitive << ( tmp_60_fu_591_p3 );

    SC_METHOD(thread_xor_ln639_2_fu_695_p2);
    sensitive << ( icmp_ln631_fu_605_p2 );

    SC_METHOD(thread_zext_ln415_fu_397_p1);
    sensitive << ( qb_fu_381_p3 );

    SC_METHOD(thread_zext_ln461_fu_241_p1);
    sensitive << ( tmp_V_fu_209_p4 );

    SC_METHOD(thread_zext_ln586_fu_329_p1);
    sensitive << ( sext_ln581_fu_293_p1 );

    SC_METHOD(thread_zext_ln591_fu_369_p1);
    sensitive << ( add_ln591_fu_363_p2 );

    SC_METHOD(thread_zext_ln623_fu_565_p1);
    sensitive << ( sext_ln618_fu_531_p1 );

    SC_METHOD(thread_zext_ln635_fu_617_p1);
    sensitive << ( sext_ln619_fu_541_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( icmp_ln2526_fu_174_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln2527_fu_186_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter6 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter7 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter6 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "ConvertScaleAbs_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, p_src_data_stream_V_dout, "(port)p_src_data_stream_V_dout");
    sc_trace(mVcdFile, p_src_data_stream_V_empty_n, "(port)p_src_data_stream_V_empty_n");
    sc_trace(mVcdFile, p_src_data_stream_V_read, "(port)p_src_data_stream_V_read");
    sc_trace(mVcdFile, p_dst_data_stream_V_din, "(port)p_dst_data_stream_V_din");
    sc_trace(mVcdFile, p_dst_data_stream_V_full_n, "(port)p_dst_data_stream_V_full_n");
    sc_trace(mVcdFile, p_dst_data_stream_V_write, "(port)p_dst_data_stream_V_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, p_src_data_stream_V_blk_n, "p_src_data_stream_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln2527_reg_834, "icmp_ln2527_reg_834");
    sc_trace(mVcdFile, p_dst_data_stream_V_blk_n, "p_dst_data_stream_V_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter7, "ap_enable_reg_pp0_iter7");
    sc_trace(mVcdFile, icmp_ln2527_reg_834_pp0_iter6_reg, "icmp_ln2527_reg_834_pp0_iter6_reg");
    sc_trace(mVcdFile, j_0_reg_160, "j_0_reg_160");
    sc_trace(mVcdFile, icmp_ln2526_fu_174_p2, "icmp_ln2526_fu_174_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_fu_180_p2, "i_fu_180_p2");
    sc_trace(mVcdFile, i_reg_829, "i_reg_829");
    sc_trace(mVcdFile, icmp_ln2527_fu_186_p2, "icmp_ln2527_fu_186_p2");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter2, "ap_block_state5_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter3, "ap_block_state6_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter4, "ap_block_state7_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter5, "ap_block_state8_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage0_iter6, "ap_block_state9_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_state10_pp0_stage0_iter7, "ap_block_state10_pp0_stage0_iter7");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, icmp_ln2527_reg_834_pp0_iter1_reg, "icmp_ln2527_reg_834_pp0_iter1_reg");
    sc_trace(mVcdFile, icmp_ln2527_reg_834_pp0_iter2_reg, "icmp_ln2527_reg_834_pp0_iter2_reg");
    sc_trace(mVcdFile, icmp_ln2527_reg_834_pp0_iter3_reg, "icmp_ln2527_reg_834_pp0_iter3_reg");
    sc_trace(mVcdFile, icmp_ln2527_reg_834_pp0_iter4_reg, "icmp_ln2527_reg_834_pp0_iter4_reg");
    sc_trace(mVcdFile, icmp_ln2527_reg_834_pp0_iter5_reg, "icmp_ln2527_reg_834_pp0_iter5_reg");
    sc_trace(mVcdFile, j_fu_192_p2, "j_fu_192_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, tmp_reg_843, "tmp_reg_843");
    sc_trace(mVcdFile, grp_fu_171_p1, "grp_fu_171_p1");
    sc_trace(mVcdFile, x_assign_reg_853, "x_assign_reg_853");
    sc_trace(mVcdFile, tmp_61_fu_817_p3, "tmp_61_fu_817_p3");
    sc_trace(mVcdFile, tmp_61_reg_858, "tmp_61_reg_858");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state3, "ap_condition_pp0_exit_iter0_state3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter6, "ap_enable_reg_pp0_iter6");
    sc_trace(mVcdFile, i_0_reg_149, "i_0_reg_149");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, grp_fu_171_p0, "grp_fu_171_p0");
    sc_trace(mVcdFile, p_Val2_s_fu_202_p1, "p_Val2_s_fu_202_p1");
    sc_trace(mVcdFile, tmp_V_fu_209_p4, "tmp_V_fu_209_p4");
    sc_trace(mVcdFile, tmp_V_4_fu_219_p1, "tmp_V_4_fu_219_p1");
    sc_trace(mVcdFile, icmp_ln833_fu_223_p2, "icmp_ln833_fu_223_p2");
    sc_trace(mVcdFile, icmp_ln837_fu_229_p2, "icmp_ln837_fu_229_p2");
    sc_trace(mVcdFile, tmp_1_i_fu_245_p3, "tmp_1_i_fu_245_p3");
    sc_trace(mVcdFile, trunc_ln368_fu_205_p1, "trunc_ln368_fu_205_p1");
    sc_trace(mVcdFile, zext_ln461_fu_241_p1, "zext_ln461_fu_241_p1");
    sc_trace(mVcdFile, F2_fu_263_p2, "F2_fu_263_p2");
    sc_trace(mVcdFile, icmp_ln581_fu_269_p2, "icmp_ln581_fu_269_p2");
    sc_trace(mVcdFile, sub_ln581_fu_275_p2, "sub_ln581_fu_275_p2");
    sc_trace(mVcdFile, F2_4_fu_281_p3, "F2_4_fu_281_p3");
    sc_trace(mVcdFile, tmp_56_fu_313_p4, "tmp_56_fu_313_p4");
    sc_trace(mVcdFile, sext_ln581_fu_293_p1, "sext_ln581_fu_293_p1");
    sc_trace(mVcdFile, p_Result_12_fu_253_p1, "p_Result_12_fu_253_p1");
    sc_trace(mVcdFile, zext_ln586_fu_329_p1, "zext_ln586_fu_329_p1");
    sc_trace(mVcdFile, ashr_ln586_fu_333_p2, "ashr_ln586_fu_333_p2");
    sc_trace(mVcdFile, trunc_ln583_fu_303_p1, "trunc_ln583_fu_303_p1");
    sc_trace(mVcdFile, trunc_ln581_fu_289_p1, "trunc_ln581_fu_289_p1");
    sc_trace(mVcdFile, icmp_ln585_fu_307_p2, "icmp_ln585_fu_307_p2");
    sc_trace(mVcdFile, trunc_ln586_fu_339_p1, "trunc_ln586_fu_339_p1");
    sc_trace(mVcdFile, add_ln591_fu_363_p2, "add_ln591_fu_363_p2");
    sc_trace(mVcdFile, zext_ln591_fu_369_p1, "zext_ln591_fu_369_p1");
    sc_trace(mVcdFile, icmp_ln591_fu_357_p2, "icmp_ln591_fu_357_p2");
    sc_trace(mVcdFile, p_Result_s_fu_373_p3, "p_Result_s_fu_373_p3");
    sc_trace(mVcdFile, p_Val2_18_fu_349_p3, "p_Val2_18_fu_349_p3");
    sc_trace(mVcdFile, qb_fu_381_p3, "qb_fu_381_p3");
    sc_trace(mVcdFile, zext_ln415_fu_397_p1, "zext_ln415_fu_397_p1");
    sc_trace(mVcdFile, p_Val2_19_fu_401_p2, "p_Val2_19_fu_401_p2");
    sc_trace(mVcdFile, tmp_58_fu_407_p3, "tmp_58_fu_407_p3");
    sc_trace(mVcdFile, icmp_ln582_fu_297_p2, "icmp_ln582_fu_297_p2");
    sc_trace(mVcdFile, xor_ln582_fu_429_p2, "xor_ln582_fu_429_p2");
    sc_trace(mVcdFile, and_ln581_fu_435_p2, "and_ln581_fu_435_p2");
    sc_trace(mVcdFile, p_Result_13_fu_389_p3, "p_Result_13_fu_389_p3");
    sc_trace(mVcdFile, and_ln403_fu_441_p2, "and_ln403_fu_441_p2");
    sc_trace(mVcdFile, select_ln582_fu_421_p3, "select_ln582_fu_421_p3");
    sc_trace(mVcdFile, xor_ln403_fu_455_p2, "xor_ln403_fu_455_p2");
    sc_trace(mVcdFile, and_ln403_2_fu_461_p2, "and_ln403_2_fu_461_p2");
    sc_trace(mVcdFile, select_ln403_fu_447_p3, "select_ln403_fu_447_p3");
    sc_trace(mVcdFile, or_ln581_fu_475_p2, "or_ln581_fu_475_p2");
    sc_trace(mVcdFile, icmp_ln603_fu_323_p2, "icmp_ln603_fu_323_p2");
    sc_trace(mVcdFile, xor_ln581_fu_481_p2, "xor_ln581_fu_481_p2");
    sc_trace(mVcdFile, and_ln603_fu_487_p2, "and_ln603_fu_487_p2");
    sc_trace(mVcdFile, shl_ln604_fu_343_p2, "shl_ln604_fu_343_p2");
    sc_trace(mVcdFile, select_ln403_2_fu_467_p3, "select_ln403_2_fu_467_p3");
    sc_trace(mVcdFile, xor_ln603_fu_501_p2, "xor_ln603_fu_501_p2");
    sc_trace(mVcdFile, or_ln603_fu_507_p2, "or_ln603_fu_507_p2");
    sc_trace(mVcdFile, xor_ln416_fu_415_p2, "xor_ln416_fu_415_p2");
    sc_trace(mVcdFile, and_ln603_3_fu_513_p2, "and_ln603_3_fu_513_p2");
    sc_trace(mVcdFile, pos1_fu_525_p2, "pos1_fu_525_p2");
    sc_trace(mVcdFile, pos2_fu_535_p2, "pos2_fu_535_p2");
    sc_trace(mVcdFile, tmp_59_fu_551_p3, "tmp_59_fu_551_p3");
    sc_trace(mVcdFile, sext_ln618_fu_531_p1, "sext_ln618_fu_531_p1");
    sc_trace(mVcdFile, zext_ln623_fu_565_p1, "zext_ln623_fu_565_p1");
    sc_trace(mVcdFile, ashr_ln623_fu_569_p2, "ashr_ln623_fu_569_p2");
    sc_trace(mVcdFile, lD_fu_575_p1, "lD_fu_575_p1");
    sc_trace(mVcdFile, xor_ln621_2_fu_559_p2, "xor_ln621_2_fu_559_p2");
    sc_trace(mVcdFile, and_ln621_fu_579_p2, "and_ln621_fu_579_p2");
    sc_trace(mVcdFile, icmp_ln621_fu_545_p2, "icmp_ln621_fu_545_p2");
    sc_trace(mVcdFile, tmp_60_fu_591_p3, "tmp_60_fu_591_p3");
    sc_trace(mVcdFile, icmp_ln631_fu_605_p2, "icmp_ln631_fu_605_p2");
    sc_trace(mVcdFile, xor_ln631_fu_599_p2, "xor_ln631_fu_599_p2");
    sc_trace(mVcdFile, sext_ln619_fu_541_p1, "sext_ln619_fu_541_p1");
    sc_trace(mVcdFile, zext_ln635_fu_617_p1, "zext_ln635_fu_617_p1");
    sc_trace(mVcdFile, Range2_V_2_fu_621_p2, "Range2_V_2_fu_621_p2");
    sc_trace(mVcdFile, r_V_fu_627_p2, "r_V_fu_627_p2");
    sc_trace(mVcdFile, and_ln631_fu_611_p2, "and_ln631_fu_611_p2");
    sc_trace(mVcdFile, Range2_all_ones_fu_633_p2, "Range2_all_ones_fu_633_p2");
    sc_trace(mVcdFile, select_ln631_fu_639_p3, "select_ln631_fu_639_p3");
    sc_trace(mVcdFile, Range1_all_ones_2_fu_585_p2, "Range1_all_ones_2_fu_585_p2");
    sc_trace(mVcdFile, icmp_ln641_fu_659_p2, "icmp_ln641_fu_659_p2");
    sc_trace(mVcdFile, Range1_all_zeros_fu_665_p2, "Range1_all_zeros_fu_665_p2");
    sc_trace(mVcdFile, Range1_all_zeros_2_fu_683_p2, "Range1_all_zeros_2_fu_683_p2");
    sc_trace(mVcdFile, xor_ln639_2_fu_695_p2, "xor_ln639_2_fu_695_p2");
    sc_trace(mVcdFile, icmp_ln642_fu_677_p2, "icmp_ln642_fu_677_p2");
    sc_trace(mVcdFile, or_ln639_fu_701_p2, "or_ln639_fu_701_p2");
    sc_trace(mVcdFile, and_ln642_fu_707_p2, "and_ln642_fu_707_p2");
    sc_trace(mVcdFile, and_ln639_fu_647_p2, "and_ln639_fu_647_p2");
    sc_trace(mVcdFile, Range1_all_ones_fu_653_p2, "Range1_all_ones_fu_653_p2");
    sc_trace(mVcdFile, select_ln642_fu_713_p3, "select_ln642_fu_713_p3");
    sc_trace(mVcdFile, or_ln645_fu_689_p2, "or_ln645_fu_689_p2");
    sc_trace(mVcdFile, and_ln641_fu_671_p2, "and_ln641_fu_671_p2");
    sc_trace(mVcdFile, select_ln642_2_fu_729_p3, "select_ln642_2_fu_729_p3");
    sc_trace(mVcdFile, and_ln603_4_fu_519_p2, "and_ln603_4_fu_519_p2");
    sc_trace(mVcdFile, select_ln639_fu_721_p3, "select_ln639_fu_721_p3");
    sc_trace(mVcdFile, select_ln639_2_fu_737_p3, "select_ln639_2_fu_737_p3");
    sc_trace(mVcdFile, xor_ln621_fu_753_p2, "xor_ln621_fu_753_p2");
    sc_trace(mVcdFile, deleted_zeros_fu_745_p3, "deleted_zeros_fu_745_p3");
    sc_trace(mVcdFile, or_ln658_fu_759_p2, "or_ln658_fu_759_p2");
    sc_trace(mVcdFile, p_Val2_20_fu_493_p3, "p_Val2_20_fu_493_p3");
    sc_trace(mVcdFile, and_ln428_2_fu_773_p2, "and_ln428_2_fu_773_p2");
    sc_trace(mVcdFile, icmp_ln571_fu_257_p2, "icmp_ln571_fu_257_p2");
    sc_trace(mVcdFile, xor_ln428_fu_779_p2, "xor_ln428_fu_779_p2");
    sc_trace(mVcdFile, and_ln571_fu_785_p2, "and_ln571_fu_785_p2");
    sc_trace(mVcdFile, and_ln428_fu_235_p2, "and_ln428_fu_235_p2");
    sc_trace(mVcdFile, or_ln571_fu_791_p2, "or_ln571_fu_791_p2");
    sc_trace(mVcdFile, or_ln571_2_fu_805_p2, "or_ln571_2_fu_805_p2");
    sc_trace(mVcdFile, xor_ln571_fu_811_p2, "xor_ln571_fu_811_p2");
    sc_trace(mVcdFile, select_ln340_fu_765_p3, "select_ln340_fu_765_p3");
    sc_trace(mVcdFile, select_ln571_fu_797_p3, "select_ln571_fu_797_p3");
    sc_trace(mVcdFile, grp_fu_171_ce, "grp_fu_171_ce");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

ConvertScaleAbs::~ConvertScaleAbs() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete sobel_accel_sitodtde_U84;
}

void ConvertScaleAbs::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(icmp_ln2526_fu_174_p2.read(), ap_const_lv1_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2526_fu_174_p2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state3.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter6 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter6 = ap_enable_reg_pp0_iter5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter7 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter7 = ap_enable_reg_pp0_iter6.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2526_fu_174_p2.read()))) {
            ap_enable_reg_pp0_iter7 = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        i_0_reg_149 = i_reg_829.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        i_0_reg_149 = ap_const_lv11_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2527_fu_186_p2.read()))) {
        j_0_reg_160 = j_fu_192_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2526_fu_174_p2.read()))) {
        j_0_reg_160 = ap_const_lv11_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_829 = i_fu_180_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln2527_reg_834 = icmp_ln2527_fu_186_p2.read();
        icmp_ln2527_reg_834_pp0_iter1_reg = icmp_ln2527_reg_834.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        icmp_ln2527_reg_834_pp0_iter2_reg = icmp_ln2527_reg_834_pp0_iter1_reg.read();
        icmp_ln2527_reg_834_pp0_iter3_reg = icmp_ln2527_reg_834_pp0_iter2_reg.read();
        icmp_ln2527_reg_834_pp0_iter4_reg = icmp_ln2527_reg_834_pp0_iter3_reg.read();
        icmp_ln2527_reg_834_pp0_iter5_reg = icmp_ln2527_reg_834_pp0_iter4_reg.read();
        icmp_ln2527_reg_834_pp0_iter6_reg = icmp_ln2527_reg_834_pp0_iter5_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2527_reg_834_pp0_iter5_reg.read()))) {
        tmp_61_reg_858 = tmp_61_fu_817_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(icmp_ln2527_reg_834.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_reg_843 = p_src_data_stream_V_dout.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2527_reg_834_pp0_iter4_reg.read()))) {
        x_assign_reg_853 = grp_fu_171_p1.read();
    }
}

void ConvertScaleAbs::thread_F2_4_fu_281_p3() {
    F2_4_fu_281_p3 = (!icmp_ln581_fu_269_p2.read()[0].is_01())? sc_lv<12>(): ((icmp_ln581_fu_269_p2.read()[0].to_bool())? F2_fu_263_p2.read(): sub_ln581_fu_275_p2.read());
}

void ConvertScaleAbs::thread_F2_fu_263_p2() {
    F2_fu_263_p2 = (!ap_const_lv12_433.is_01() || !zext_ln461_fu_241_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_433) - sc_biguint<12>(zext_ln461_fu_241_p1.read()));
}

void ConvertScaleAbs::thread_Range1_all_ones_2_fu_585_p2() {
    Range1_all_ones_2_fu_585_p2 = (and_ln621_fu_579_p2.read() & icmp_ln621_fu_545_p2.read());
}

void ConvertScaleAbs::thread_Range1_all_ones_fu_653_p2() {
    Range1_all_ones_fu_653_p2 = (select_ln631_fu_639_p3.read() & Range1_all_ones_2_fu_585_p2.read());
}

void ConvertScaleAbs::thread_Range1_all_zeros_2_fu_683_p2() {
    Range1_all_zeros_2_fu_683_p2 = (!p_Result_12_fu_253_p1.read().is_01() || !ap_const_lv54_0.is_01())? sc_lv<1>(): sc_lv<1>(p_Result_12_fu_253_p1.read() == ap_const_lv54_0);
}

void ConvertScaleAbs::thread_Range1_all_zeros_fu_665_p2() {
    Range1_all_zeros_fu_665_p2 = (Range1_all_ones_2_fu_585_p2.read() ^ ap_const_lv1_1);
}

void ConvertScaleAbs::thread_Range2_V_2_fu_621_p2() {
    Range2_V_2_fu_621_p2 = (!zext_ln635_fu_617_p1.read().is_01())? sc_lv<54>(): p_Result_12_fu_253_p1.read() >> (unsigned short)zext_ln635_fu_617_p1.read().to_uint();
}

void ConvertScaleAbs::thread_Range2_all_ones_fu_633_p2() {
    Range2_all_ones_fu_633_p2 = (!Range2_V_2_fu_621_p2.read().is_01() || !r_V_fu_627_p2.read().is_01())? sc_lv<1>(): sc_lv<1>(Range2_V_2_fu_621_p2.read() == r_V_fu_627_p2.read());
}

void ConvertScaleAbs::thread_add_ln591_fu_363_p2() {
    add_ln591_fu_363_p2 = (!ap_const_lv12_FFF.is_01() || !F2_fu_263_p2.read().is_01())? sc_lv<12>(): (sc_bigint<12>(ap_const_lv12_FFF) + sc_biguint<12>(F2_fu_263_p2.read()));
}

void ConvertScaleAbs::thread_and_ln403_2_fu_461_p2() {
    and_ln403_2_fu_461_p2 = (and_ln581_fu_435_p2.read() & xor_ln403_fu_455_p2.read());
}

void ConvertScaleAbs::thread_and_ln403_fu_441_p2() {
    and_ln403_fu_441_p2 = (and_ln581_fu_435_p2.read() & p_Result_13_fu_389_p3.read());
}

void ConvertScaleAbs::thread_and_ln428_2_fu_773_p2() {
    and_ln428_2_fu_773_p2 = (icmp_ln833_fu_223_p2.read() & icmp_ln837_fu_229_p2.read());
}

void ConvertScaleAbs::thread_and_ln428_fu_235_p2() {
    and_ln428_fu_235_p2 = (icmp_ln833_fu_223_p2.read() & icmp_ln837_fu_229_p2.read());
}

void ConvertScaleAbs::thread_and_ln571_fu_785_p2() {
    and_ln571_fu_785_p2 = (icmp_ln571_fu_257_p2.read() & xor_ln428_fu_779_p2.read());
}

void ConvertScaleAbs::thread_and_ln581_fu_435_p2() {
    and_ln581_fu_435_p2 = (icmp_ln581_fu_269_p2.read() & xor_ln582_fu_429_p2.read());
}

void ConvertScaleAbs::thread_and_ln603_3_fu_513_p2() {
    and_ln603_3_fu_513_p2 = (or_ln603_fu_507_p2.read() & xor_ln416_fu_415_p2.read());
}

void ConvertScaleAbs::thread_and_ln603_4_fu_519_p2() {
    and_ln603_4_fu_519_p2 = (and_ln603_3_fu_513_p2.read() & and_ln403_fu_441_p2.read());
}

void ConvertScaleAbs::thread_and_ln603_fu_487_p2() {
    and_ln603_fu_487_p2 = (icmp_ln603_fu_323_p2.read() & xor_ln581_fu_481_p2.read());
}

void ConvertScaleAbs::thread_and_ln621_fu_579_p2() {
    and_ln621_fu_579_p2 = (lD_fu_575_p1.read() & xor_ln621_2_fu_559_p2.read());
}

void ConvertScaleAbs::thread_and_ln631_fu_611_p2() {
    and_ln631_fu_611_p2 = (icmp_ln631_fu_605_p2.read() & xor_ln631_fu_599_p2.read());
}

void ConvertScaleAbs::thread_and_ln639_fu_647_p2() {
    and_ln639_fu_647_p2 = (icmp_ln631_fu_605_p2.read() & xor_ln621_2_fu_559_p2.read());
}

void ConvertScaleAbs::thread_and_ln641_fu_671_p2() {
    and_ln641_fu_671_p2 = (icmp_ln641_fu_659_p2.read() & Range1_all_zeros_fu_665_p2.read());
}

void ConvertScaleAbs::thread_and_ln642_fu_707_p2() {
    and_ln642_fu_707_p2 = (icmp_ln642_fu_677_p2.read() & or_ln639_fu_701_p2.read());
}

void ConvertScaleAbs::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void ConvertScaleAbs::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void ConvertScaleAbs::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[3];
}

void ConvertScaleAbs::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void ConvertScaleAbs::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ConvertScaleAbs::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(icmp_ln2527_reg_834.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2527_reg_834_pp0_iter6_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_dst_data_stream_V_full_n.read())));
}

void ConvertScaleAbs::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(icmp_ln2527_reg_834.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2527_reg_834_pp0_iter6_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_dst_data_stream_V_full_n.read())));
}

void ConvertScaleAbs::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(icmp_ln2527_reg_834.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_V_empty_n.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2527_reg_834_pp0_iter6_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, p_dst_data_stream_V_full_n.read())));
}

void ConvertScaleAbs::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void ConvertScaleAbs::thread_ap_block_state10_pp0_stage0_iter7() {
    ap_block_state10_pp0_stage0_iter7 = (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2527_reg_834_pp0_iter6_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_0, p_dst_data_stream_V_full_n.read()));
}

void ConvertScaleAbs::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ConvertScaleAbs::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = (esl_seteq<1,1,1>(icmp_ln2527_reg_834.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, p_src_data_stream_V_empty_n.read()));
}

void ConvertScaleAbs::thread_ap_block_state5_pp0_stage0_iter2() {
    ap_block_state5_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ConvertScaleAbs::thread_ap_block_state6_pp0_stage0_iter3() {
    ap_block_state6_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ConvertScaleAbs::thread_ap_block_state7_pp0_stage0_iter4() {
    ap_block_state7_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ConvertScaleAbs::thread_ap_block_state8_pp0_stage0_iter5() {
    ap_block_state8_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ConvertScaleAbs::thread_ap_block_state9_pp0_stage0_iter6() {
    ap_block_state9_pp0_stage0_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void ConvertScaleAbs::thread_ap_condition_pp0_exit_iter0_state3() {
    if (esl_seteq<1,1,1>(icmp_ln2527_fu_186_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_0;
    }
}

void ConvertScaleAbs::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln2526_fu_174_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void ConvertScaleAbs::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void ConvertScaleAbs::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void ConvertScaleAbs::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void ConvertScaleAbs::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln2526_fu_174_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void ConvertScaleAbs::thread_ashr_ln586_fu_333_p2() {
    ashr_ln586_fu_333_p2 = (!p_Result_12_fu_253_p1.read().is_01() || !zext_ln586_fu_329_p1.read().is_01())? sc_lv<54>(): sc_bigint<54>(p_Result_12_fu_253_p1.read()) >> (unsigned short)zext_ln586_fu_329_p1.read().to_uint();
}

void ConvertScaleAbs::thread_ashr_ln623_fu_569_p2() {
    ashr_ln623_fu_569_p2 = (!p_Result_12_fu_253_p1.read().is_01() || !zext_ln623_fu_565_p1.read().is_01())? sc_lv<54>(): sc_bigint<54>(p_Result_12_fu_253_p1.read()) >> (unsigned short)zext_ln623_fu_565_p1.read().to_uint();
}

void ConvertScaleAbs::thread_deleted_zeros_fu_745_p3() {
    deleted_zeros_fu_745_p3 = (!and_ln603_4_fu_519_p2.read()[0].is_01())? sc_lv<1>(): ((and_ln603_4_fu_519_p2.read()[0].to_bool())? select_ln639_fu_721_p3.read(): select_ln639_2_fu_737_p3.read());
}

void ConvertScaleAbs::thread_grp_fu_171_ce() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        grp_fu_171_ce = ap_const_logic_1;
    } else {
        grp_fu_171_ce = ap_const_logic_0;
    }
}

void ConvertScaleAbs::thread_grp_fu_171_p0() {
    grp_fu_171_p0 = esl_sext<32,16>(tmp_reg_843.read());
}

void ConvertScaleAbs::thread_i_fu_180_p2() {
    i_fu_180_p2 = (!i_0_reg_149.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(i_0_reg_149.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void ConvertScaleAbs::thread_icmp_ln2526_fu_174_p2() {
    icmp_ln2526_fu_174_p2 = (!i_0_reg_149.read().is_01() || !ap_const_lv11_438.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_149.read() == ap_const_lv11_438);
}

void ConvertScaleAbs::thread_icmp_ln2527_fu_186_p2() {
    icmp_ln2527_fu_186_p2 = (!j_0_reg_160.read().is_01() || !ap_const_lv11_780.is_01())? sc_lv<1>(): sc_lv<1>(j_0_reg_160.read() == ap_const_lv11_780);
}

void ConvertScaleAbs::thread_icmp_ln571_fu_257_p2() {
    icmp_ln571_fu_257_p2 = (!trunc_ln368_fu_205_p1.read().is_01() || !ap_const_lv63_0.is_01())? sc_lv<1>(): sc_lv<1>(trunc_ln368_fu_205_p1.read() == ap_const_lv63_0);
}

void ConvertScaleAbs::thread_icmp_ln581_fu_269_p2() {
    icmp_ln581_fu_269_p2 = (!F2_fu_263_p2.read().is_01() || !ap_const_lv12_0.is_01())? sc_lv<1>(): (sc_bigint<12>(F2_fu_263_p2.read()) > sc_bigint<12>(ap_const_lv12_0));
}

void ConvertScaleAbs::thread_icmp_ln582_fu_297_p2() {
    icmp_ln582_fu_297_p2 = (!tmp_V_fu_209_p4.read().is_01() || !ap_const_lv11_433.is_01())? sc_lv<1>(): sc_lv<1>(tmp_V_fu_209_p4.read() == ap_const_lv11_433);
}

void ConvertScaleAbs::thread_icmp_ln585_fu_307_p2() {
    icmp_ln585_fu_307_p2 = (!F2_4_fu_281_p3.read().is_01() || !ap_const_lv12_36.is_01())? sc_lv<1>(): (sc_biguint<12>(F2_4_fu_281_p3.read()) < sc_biguint<12>(ap_const_lv12_36));
}

void ConvertScaleAbs::thread_icmp_ln591_fu_357_p2() {
    icmp_ln591_fu_357_p2 = (!F2_fu_263_p2.read().is_01() || !ap_const_lv12_36.is_01())? sc_lv<1>(): (sc_bigint<12>(F2_fu_263_p2.read()) > sc_bigint<12>(ap_const_lv12_36));
}

void ConvertScaleAbs::thread_icmp_ln603_fu_323_p2() {
    icmp_ln603_fu_323_p2 = (!tmp_56_fu_313_p4.read().is_01() || !ap_const_lv9_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_56_fu_313_p4.read() == ap_const_lv9_0);
}

void ConvertScaleAbs::thread_icmp_ln621_fu_545_p2() {
    icmp_ln621_fu_545_p2 = (!pos1_fu_525_p2.read().is_01() || !ap_const_lv12_36.is_01())? sc_lv<1>(): (sc_bigint<12>(pos1_fu_525_p2.read()) < sc_bigint<12>(ap_const_lv12_36));
}

void ConvertScaleAbs::thread_icmp_ln631_fu_605_p2() {
    icmp_ln631_fu_605_p2 = (!pos2_fu_535_p2.read().is_01() || !ap_const_lv12_36.is_01())? sc_lv<1>(): (sc_bigint<12>(pos2_fu_535_p2.read()) < sc_bigint<12>(ap_const_lv12_36));
}

void ConvertScaleAbs::thread_icmp_ln641_fu_659_p2() {
    icmp_ln641_fu_659_p2 = (!Range2_V_2_fu_621_p2.read().is_01() || !ap_const_lv54_0.is_01())? sc_lv<1>(): sc_lv<1>(Range2_V_2_fu_621_p2.read() == ap_const_lv54_0);
}

void ConvertScaleAbs::thread_icmp_ln642_fu_677_p2() {
    icmp_ln642_fu_677_p2 = (!pos2_fu_535_p2.read().is_01() || !ap_const_lv12_36.is_01())? sc_lv<1>(): sc_lv<1>(pos2_fu_535_p2.read() == ap_const_lv12_36);
}

void ConvertScaleAbs::thread_icmp_ln833_fu_223_p2() {
    icmp_ln833_fu_223_p2 = (!tmp_V_fu_209_p4.read().is_01() || !ap_const_lv11_7FF.is_01())? sc_lv<1>(): sc_lv<1>(tmp_V_fu_209_p4.read() == ap_const_lv11_7FF);
}

void ConvertScaleAbs::thread_icmp_ln837_fu_229_p2() {
    icmp_ln837_fu_229_p2 = (!tmp_V_4_fu_219_p1.read().is_01() || !ap_const_lv52_0.is_01())? sc_lv<1>(): sc_lv<1>(tmp_V_4_fu_219_p1.read() != ap_const_lv52_0);
}

void ConvertScaleAbs::thread_j_fu_192_p2() {
    j_fu_192_p2 = (!j_0_reg_160.read().is_01() || !ap_const_lv11_1.is_01())? sc_lv<11>(): (sc_biguint<11>(j_0_reg_160.read()) + sc_biguint<11>(ap_const_lv11_1));
}

void ConvertScaleAbs::thread_lD_fu_575_p1() {
    lD_fu_575_p1 = ashr_ln623_fu_569_p2.read().range(1-1, 0);
}

void ConvertScaleAbs::thread_or_ln571_2_fu_805_p2() {
    or_ln571_2_fu_805_p2 = (and_ln428_fu_235_p2.read() | icmp_ln571_fu_257_p2.read());
}

void ConvertScaleAbs::thread_or_ln571_fu_791_p2() {
    or_ln571_fu_791_p2 = (and_ln571_fu_785_p2.read() | and_ln428_fu_235_p2.read());
}

void ConvertScaleAbs::thread_or_ln581_fu_475_p2() {
    or_ln581_fu_475_p2 = (icmp_ln582_fu_297_p2.read() | icmp_ln581_fu_269_p2.read());
}

void ConvertScaleAbs::thread_or_ln603_fu_507_p2() {
    or_ln603_fu_507_p2 = (or_ln581_fu_475_p2.read() | xor_ln603_fu_501_p2.read());
}

void ConvertScaleAbs::thread_or_ln639_fu_701_p2() {
    or_ln639_fu_701_p2 = (tmp_59_fu_551_p3.read() | xor_ln639_2_fu_695_p2.read());
}

void ConvertScaleAbs::thread_or_ln645_fu_689_p2() {
    or_ln645_fu_689_p2 = (Range1_all_zeros_2_fu_683_p2.read() | xor_ln621_2_fu_559_p2.read());
}

void ConvertScaleAbs::thread_or_ln658_fu_759_p2() {
    or_ln658_fu_759_p2 = (xor_ln621_fu_753_p2.read() | deleted_zeros_fu_745_p3.read());
}

void ConvertScaleAbs::thread_p_Result_12_fu_253_p1() {
    p_Result_12_fu_253_p1 = esl_zext<54,53>(tmp_1_i_fu_245_p3.read());
}

void ConvertScaleAbs::thread_p_Result_13_fu_389_p3() {
    p_Result_13_fu_389_p3 = p_Val2_18_fu_349_p3.read().range(7, 7);
}

void ConvertScaleAbs::thread_p_Result_s_fu_373_p3() {
    p_Result_s_fu_373_p3 = (!zext_ln591_fu_369_p1.read().is_01() || sc_biguint<32>(zext_ln591_fu_369_p1.read()).to_uint() >= 54)? sc_lv<1>(): p_Result_12_fu_253_p1.read().range(sc_biguint<32>(zext_ln591_fu_369_p1.read()).to_uint(), sc_biguint<32>(zext_ln591_fu_369_p1.read()).to_uint());
}

void ConvertScaleAbs::thread_p_Val2_18_fu_349_p3() {
    p_Val2_18_fu_349_p3 = (!icmp_ln585_fu_307_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_ln585_fu_307_p2.read()[0].to_bool())? trunc_ln586_fu_339_p1.read(): ap_const_lv8_0);
}

void ConvertScaleAbs::thread_p_Val2_19_fu_401_p2() {
    p_Val2_19_fu_401_p2 = (!p_Val2_18_fu_349_p3.read().is_01() || !zext_ln415_fu_397_p1.read().is_01())? sc_lv<8>(): (sc_biguint<8>(p_Val2_18_fu_349_p3.read()) + sc_biguint<8>(zext_ln415_fu_397_p1.read()));
}

void ConvertScaleAbs::thread_p_Val2_20_fu_493_p3() {
    p_Val2_20_fu_493_p3 = (!and_ln603_fu_487_p2.read()[0].is_01())? sc_lv<8>(): ((and_ln603_fu_487_p2.read()[0].to_bool())? shl_ln604_fu_343_p2.read(): select_ln403_2_fu_467_p3.read());
}

void ConvertScaleAbs::thread_p_Val2_s_fu_202_p1() {
    p_Val2_s_fu_202_p1 = x_assign_reg_853.read();
}

void ConvertScaleAbs::thread_p_dst_data_stream_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2527_reg_834_pp0_iter6_reg.read()))) {
        p_dst_data_stream_V_blk_n = p_dst_data_stream_V_full_n.read();
    } else {
        p_dst_data_stream_V_blk_n = ap_const_logic_1;
    }
}

void ConvertScaleAbs::thread_p_dst_data_stream_V_din() {
    p_dst_data_stream_V_din = tmp_61_reg_858.read();
}

void ConvertScaleAbs::thread_p_dst_data_stream_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln2527_reg_834_pp0_iter6_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        p_dst_data_stream_V_write = ap_const_logic_1;
    } else {
        p_dst_data_stream_V_write = ap_const_logic_0;
    }
}

void ConvertScaleAbs::thread_p_src_data_stream_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln2527_reg_834.read(), ap_const_lv1_0))) {
        p_src_data_stream_V_blk_n = p_src_data_stream_V_empty_n.read();
    } else {
        p_src_data_stream_V_blk_n = ap_const_logic_1;
    }
}

void ConvertScaleAbs::thread_p_src_data_stream_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(icmp_ln2527_reg_834.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        p_src_data_stream_V_read = ap_const_logic_1;
    } else {
        p_src_data_stream_V_read = ap_const_logic_0;
    }
}

void ConvertScaleAbs::thread_pos1_fu_525_p2() {
    pos1_fu_525_p2 = (!ap_const_lv12_8.is_01() || !F2_fu_263_p2.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_8) + sc_biguint<12>(F2_fu_263_p2.read()));
}

void ConvertScaleAbs::thread_pos2_fu_535_p2() {
    pos2_fu_535_p2 = (!ap_const_lv12_9.is_01() || !F2_fu_263_p2.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_9) + sc_biguint<12>(F2_fu_263_p2.read()));
}

void ConvertScaleAbs::thread_qb_fu_381_p3() {
    qb_fu_381_p3 = (!icmp_ln591_fu_357_p2.read()[0].is_01())? sc_lv<1>(): ((icmp_ln591_fu_357_p2.read()[0].to_bool())? ap_const_lv1_0: p_Result_s_fu_373_p3.read());
}

void ConvertScaleAbs::thread_r_V_fu_627_p2() {
    r_V_fu_627_p2 = (!zext_ln635_fu_617_p1.read().is_01())? sc_lv<54>(): ap_const_lv54_3FFFFFFFFFFFFF >> (unsigned short)zext_ln635_fu_617_p1.read().to_uint();
}

void ConvertScaleAbs::thread_select_ln340_fu_765_p3() {
    select_ln340_fu_765_p3 = (!or_ln658_fu_759_p2.read()[0].is_01())? sc_lv<8>(): ((or_ln658_fu_759_p2.read()[0].to_bool())? p_Val2_20_fu_493_p3.read(): ap_const_lv8_FF);
}

void ConvertScaleAbs::thread_select_ln403_2_fu_467_p3() {
    select_ln403_2_fu_467_p3 = (!and_ln403_2_fu_461_p2.read()[0].is_01())? sc_lv<8>(): ((and_ln403_2_fu_461_p2.read()[0].to_bool())? p_Val2_19_fu_401_p2.read(): select_ln403_fu_447_p3.read());
}

void ConvertScaleAbs::thread_select_ln403_fu_447_p3() {
    select_ln403_fu_447_p3 = (!and_ln403_fu_441_p2.read()[0].is_01())? sc_lv<8>(): ((and_ln403_fu_441_p2.read()[0].to_bool())? p_Val2_19_fu_401_p2.read(): select_ln582_fu_421_p3.read());
}

void ConvertScaleAbs::thread_select_ln571_fu_797_p3() {
    select_ln571_fu_797_p3 = (!or_ln571_fu_791_p2.read()[0].is_01())? sc_lv<8>(): ((or_ln571_fu_791_p2.read()[0].to_bool())? ap_const_lv8_0: p_Val2_20_fu_493_p3.read());
}

void ConvertScaleAbs::thread_select_ln582_fu_421_p3() {
    select_ln582_fu_421_p3 = (!icmp_ln582_fu_297_p2.read()[0].is_01())? sc_lv<8>(): ((icmp_ln582_fu_297_p2.read()[0].to_bool())? trunc_ln583_fu_303_p1.read(): ap_const_lv8_0);
}

void ConvertScaleAbs::thread_select_ln631_fu_639_p3() {
    select_ln631_fu_639_p3 = (!and_ln631_fu_611_p2.read()[0].is_01())? sc_lv<1>(): ((and_ln631_fu_611_p2.read()[0].to_bool())? Range2_all_ones_fu_633_p2.read(): xor_ln631_fu_599_p2.read());
}

void ConvertScaleAbs::thread_select_ln639_2_fu_737_p3() {
    select_ln639_2_fu_737_p3 = (!and_ln639_fu_647_p2.read()[0].is_01())? sc_lv<1>(): ((and_ln639_fu_647_p2.read()[0].to_bool())? and_ln641_fu_671_p2.read(): select_ln642_2_fu_729_p3.read());
}

void ConvertScaleAbs::thread_select_ln639_fu_721_p3() {
    select_ln639_fu_721_p3 = (!and_ln639_fu_647_p2.read()[0].is_01())? sc_lv<1>(): ((and_ln639_fu_647_p2.read()[0].to_bool())? Range1_all_ones_fu_653_p2.read(): select_ln642_fu_713_p3.read());
}

void ConvertScaleAbs::thread_select_ln642_2_fu_729_p3() {
    select_ln642_2_fu_729_p3 = (!and_ln642_fu_707_p2.read()[0].is_01())? sc_lv<1>(): ((and_ln642_fu_707_p2.read()[0].to_bool())? Range1_all_zeros_fu_665_p2.read(): or_ln645_fu_689_p2.read());
}

void ConvertScaleAbs::thread_select_ln642_fu_713_p3() {
    select_ln642_fu_713_p3 = (!and_ln642_fu_707_p2.read()[0].is_01())? sc_lv<1>(): ((and_ln642_fu_707_p2.read()[0].to_bool())? Range1_all_ones_2_fu_585_p2.read(): xor_ln621_2_fu_559_p2.read());
}

void ConvertScaleAbs::thread_sext_ln581_fu_293_p1() {
    sext_ln581_fu_293_p1 = esl_sext<32,12>(F2_4_fu_281_p3.read());
}

void ConvertScaleAbs::thread_sext_ln618_fu_531_p1() {
    sext_ln618_fu_531_p1 = esl_sext<32,12>(pos1_fu_525_p2.read());
}

void ConvertScaleAbs::thread_sext_ln619_fu_541_p1() {
    sext_ln619_fu_541_p1 = esl_sext<32,12>(pos2_fu_535_p2.read());
}

void ConvertScaleAbs::thread_shl_ln604_fu_343_p2() {
    shl_ln604_fu_343_p2 = (!trunc_ln581_fu_289_p1.read().is_01())? sc_lv<8>(): trunc_ln583_fu_303_p1.read() << (unsigned short)trunc_ln581_fu_289_p1.read().to_uint();
}

void ConvertScaleAbs::thread_sub_ln581_fu_275_p2() {
    sub_ln581_fu_275_p2 = (!ap_const_lv12_0.is_01() || !F2_fu_263_p2.read().is_01())? sc_lv<12>(): (sc_biguint<12>(ap_const_lv12_0) - sc_biguint<12>(F2_fu_263_p2.read()));
}

void ConvertScaleAbs::thread_tmp_1_i_fu_245_p3() {
    tmp_1_i_fu_245_p3 = esl_concat<1,52>(ap_const_lv1_1, tmp_V_4_fu_219_p1.read());
}

void ConvertScaleAbs::thread_tmp_56_fu_313_p4() {
    tmp_56_fu_313_p4 = F2_4_fu_281_p3.read().range(11, 3);
}

void ConvertScaleAbs::thread_tmp_58_fu_407_p3() {
    tmp_58_fu_407_p3 = p_Val2_19_fu_401_p2.read().range(7, 7);
}

void ConvertScaleAbs::thread_tmp_59_fu_551_p3() {
    tmp_59_fu_551_p3 = pos1_fu_525_p2.read().range(11, 11);
}

void ConvertScaleAbs::thread_tmp_60_fu_591_p3() {
    tmp_60_fu_591_p3 = pos2_fu_535_p2.read().range(11, 11);
}

void ConvertScaleAbs::thread_tmp_61_fu_817_p3() {
    tmp_61_fu_817_p3 = (!xor_ln571_fu_811_p2.read()[0].is_01())? sc_lv<8>(): ((xor_ln571_fu_811_p2.read()[0].to_bool())? select_ln340_fu_765_p3.read(): select_ln571_fu_797_p3.read());
}

void ConvertScaleAbs::thread_tmp_V_4_fu_219_p1() {
    tmp_V_4_fu_219_p1 = p_Val2_s_fu_202_p1.read().range(52-1, 0);
}

void ConvertScaleAbs::thread_tmp_V_fu_209_p4() {
    tmp_V_fu_209_p4 = p_Val2_s_fu_202_p1.read().range(62, 52);
}

void ConvertScaleAbs::thread_trunc_ln368_fu_205_p1() {
    trunc_ln368_fu_205_p1 = p_Val2_s_fu_202_p1.read().range(63-1, 0);
}

void ConvertScaleAbs::thread_trunc_ln581_fu_289_p1() {
    trunc_ln581_fu_289_p1 = F2_4_fu_281_p3.read().range(8-1, 0);
}

void ConvertScaleAbs::thread_trunc_ln583_fu_303_p1() {
    trunc_ln583_fu_303_p1 = p_Val2_s_fu_202_p1.read().range(8-1, 0);
}

void ConvertScaleAbs::thread_trunc_ln586_fu_339_p1() {
    trunc_ln586_fu_339_p1 = ashr_ln586_fu_333_p2.read().range(8-1, 0);
}

void ConvertScaleAbs::thread_xor_ln403_fu_455_p2() {
    xor_ln403_fu_455_p2 = (p_Result_13_fu_389_p3.read() ^ ap_const_lv1_1);
}

void ConvertScaleAbs::thread_xor_ln416_fu_415_p2() {
    xor_ln416_fu_415_p2 = (tmp_58_fu_407_p3.read() ^ ap_const_lv1_1);
}

void ConvertScaleAbs::thread_xor_ln428_fu_779_p2() {
    xor_ln428_fu_779_p2 = (and_ln428_2_fu_773_p2.read() ^ ap_const_lv1_1);
}

void ConvertScaleAbs::thread_xor_ln571_fu_811_p2() {
    xor_ln571_fu_811_p2 = (or_ln571_2_fu_805_p2.read() ^ ap_const_lv1_1);
}

void ConvertScaleAbs::thread_xor_ln581_fu_481_p2() {
    xor_ln581_fu_481_p2 = (or_ln581_fu_475_p2.read() ^ ap_const_lv1_1);
}

void ConvertScaleAbs::thread_xor_ln582_fu_429_p2() {
    xor_ln582_fu_429_p2 = (icmp_ln582_fu_297_p2.read() ^ ap_const_lv1_1);
}

void ConvertScaleAbs::thread_xor_ln603_fu_501_p2() {
    xor_ln603_fu_501_p2 = (icmp_ln603_fu_323_p2.read() ^ ap_const_lv1_1);
}

void ConvertScaleAbs::thread_xor_ln621_2_fu_559_p2() {
    xor_ln621_2_fu_559_p2 = (tmp_59_fu_551_p3.read() ^ ap_const_lv1_1);
}

void ConvertScaleAbs::thread_xor_ln621_fu_753_p2() {
    xor_ln621_fu_753_p2 = (icmp_ln621_fu_545_p2.read() ^ ap_const_lv1_1);
}

void ConvertScaleAbs::thread_xor_ln631_fu_599_p2() {
    xor_ln631_fu_599_p2 = (tmp_60_fu_591_p3.read() ^ ap_const_lv1_1);
}

void ConvertScaleAbs::thread_xor_ln639_2_fu_695_p2() {
    xor_ln639_2_fu_695_p2 = (icmp_ln631_fu_605_p2.read() ^ ap_const_lv1_1);
}

void ConvertScaleAbs::thread_zext_ln415_fu_397_p1() {
    zext_ln415_fu_397_p1 = esl_zext<8,1>(qb_fu_381_p3.read());
}

void ConvertScaleAbs::thread_zext_ln461_fu_241_p1() {
    zext_ln461_fu_241_p1 = esl_zext<12,11>(tmp_V_fu_209_p4.read());
}

void ConvertScaleAbs::thread_zext_ln586_fu_329_p1() {
    zext_ln586_fu_329_p1 = esl_zext<54,32>(sext_ln581_fu_293_p1.read());
}

void ConvertScaleAbs::thread_zext_ln591_fu_369_p1() {
    zext_ln591_fu_369_p1 = esl_zext<32,12>(add_ln591_fu_363_p2.read());
}

void ConvertScaleAbs::thread_zext_ln623_fu_565_p1() {
    zext_ln623_fu_565_p1 = esl_zext<54,32>(sext_ln618_fu_531_p1.read());
}

void ConvertScaleAbs::thread_zext_ln635_fu_617_p1() {
    zext_ln635_fu_617_p1 = esl_zext<54,32>(sext_ln619_fu_541_p1.read());
}

void ConvertScaleAbs::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln2526_fu_174_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter6.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln2527_fu_186_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter6.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln2527_fu_186_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state11;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

